### ISSUE TITLE
Composer-playground docker container hangs trying to use a hlfv1 connection profile

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1058]
It looks like composer playground has problems if grpc throws an error. grpc throws an error, composer-playground terminates and is restarted but the user is left with a spinning icon on the connect with identity dialog without any notification of a problem.

the logs in the composer-playground container are as follows
```
0|composer | HLFConnection            :constructor()             <
0|composer | HLFConnectionManager     :connect()                 < {}
0|composer | ConnectorServer          :connectionManagerConnect() < 538447b0-df87-4d8e-aebd-4cc79fe1e284
0|composer | Error: Connect Failed
0|composer |     at ClientDuplexStream._emitStatusIfDone (/usr/local/lib/node_modules/composer-playground/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:201:19)
0|composer |     at ClientDuplexStream._readsDone (/usr/local/lib/node_modules/composer-playground/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:169:8)
0|composer |     at readCallback (/usr/local/lib/node_modules/composer-playground/node_modules/fabric-client/node_modules/grpc/src/node/src/client.js:229:12)
PM2        | App [composer-playground] with id [0] and pid [21], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:composer-playground id:0
PM2        | App name:composer-playground id:0 online
0|composer | PlaygroundAPI            :createServer()            > 8080
0|composer | ConnectionProfileManager :constructor()             Created a new ConnectionProfileManager {"fs":{"constants":{"O_RDONLY":0,"O_WRONLY":1,"O_RDWR":2,"S_IFMT":61440,"S_IFREG":32768,"S_IFDIR":16384,"S_IFCHR":8192,"S_IFBLK":24576,"S_IFIFO":4096,"S_IFLNK":40960,"S_IFSOCK":49152,"O_CREAT":64,"O_EXCL":128,"O_NOCTTY":256,"O_TRUNC":512,"O_APPEND":1024,"O_DIRECTORY":65536,"O_NOATIME":262144,"O_NOFOLLOW":131072,"O_SYNC":1052672,"O_DIRECT":16384,"O_NONBLOCK":2048,"S_IRWXU":448,"S_IRUSR":256,"S_IWUSR":128,"S_IXUSR":64,"S_IRWXG":56,"S_IRGRP":32,"S_IWGRP":16,"S_IXGRP":8,"S_IRWXO":7,"S_IROTH":4,"S_IWOTH":2,"S_IXOTH":1,"F_OK":0,"R_OK":4,"W_OK":2,"X_OK":1},"F_OK":0,"R_OK":4,"W_OK":2,"X_OK":1}}
0|composer | PlaygroundAPI            :createServer()            Playground API started on port 8080
0|composer | PlaygroundAPI            :createServer()            <
0|composer | Composer                 :main()                    >
0|composer | PlaygroundAPI            :createServer()            Client with ID 'CaJyhnHrdsmLgzGJAAAA' on host '::ffff:10.0.2.2' connected
0|composer | ConnectorServer          :constructor()             > {"fs":{"constants":{"O_RDONLY":0,"O_WRONLY":1,"O_RDWR":2,"S_IFMT":61440,"S_IFREG":32768,"S_IFDIR":16384,"S_IFCHR":8192,"S_IFBLK":24576,"S_IFIFO":4096,"S_IFLNK":40960,"S_IFSOCK":49152,"O_CREAT":64,"O_EXCL":128,"O_NOCTTY":256,"O_TRUNC":512,"O_APPEND":1024,"O_DIRECTORY":65536,"O_NOATIME":262144,"O_NOFOLLOW":131072,"O_SYNC":1052672,"O_DIRECT":16384,"O_NONBLOCK":2048,"S_IRWXU":448,"S_IRUSR":256,"S_IWUSR":128,"S_IXUSR":64,"S_IRWXG":56,"S_IRGRP":32,"S_IWGRP":16,"S_IXGRP":8,"S_IRWXO":7,"S_IROTH":4,"S_IWOTH":2,"S_IXOTH":1,"F_OK":0,"R_OK":4,"W_OK":2,"X_OK":1},"F_OK":0,"R_OK":4,"W_OK":2,"X_OK":1}}, {}, [object Object]
0|composer | ConnectorServer          :constructor()             <
```
We see that the playground is restarted using pm2

**Comment by davidkel** [comment]
![screen shot 2016-07-27 at 17 25 53](https://cloud.githubusercontent.com/assets/25582377/26317976/4d09c528-3f11-11e7-91db-0fb92eaa94e0.png)

**Comment by davidkel** [comment]
<img width="779" alt="screen shot 2017-05-22 at 17 07 56" src="https://cloud.githubusercontent.com/assets/25582377/26317988/5a7746ae-3f11-11e7-805c-0732f7da377c.png">

**Comment by caroline-church** [comment]
done so closing

**Comment by arsulegai** [comment]
The PR which closes this issue isn't noted. Probably because this is because Hyperledger was at infancy in 2017.
