### ISSUE TITLE
Testing of my-network is failing at license-check

### ISSUE THREAD

**Issue by nehalshah50** [hyperledger/composer#1156]
Today I am trying to set up my network using guide 

[https://hyperledger.github.io/composer/tutorials/developer-guide.html ]

but keep getting following error about license header. I checked the logic.js file and content is same as given in the instructions. Also it says the look at the log file produced but I never see any log files getting produced.....> my-network@0.0.1 pretest /Users/nxshah5/Documents/Fabric/1.0/composer-sample-networks/packages/my-network
> npm run lint

> my-network@0.0.1 lint /Users/nxshah5/Documents/Fabric/1.0/composer-sample-networks/packages/my-network
> eslint .

> my-network@0.0.1 postlint /Users/nxshah5/Documents/Fabric/1.0/composer-sample-networks/packages/my-network
> npm run licchk

> my-network@0.0.1 licchk /Users/nxshah5/Documents/Fabric/1.0/composer-sample-networks/packages/my-network
> license-check

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: The following file doesn`t contain the license header /Users/nxshah5/Documents/Fabric/1.0/composer-sample-networks/packages/my-network/lib/logic.js
    at error (/Users/nxshah5/Documents/Fabric/1.0/composer-sample-networks/packages/my-network/node_modules/gulp-license-check/index.js:140:54)
    at checkHeaderFromBuffer (/Users/nxshah5/Documents/Fabric/1.0/composer-sample-networks/packages/my-network/node_modules/gulp-license-check/index.js:84:4)
    at DestroyableTransform._transform (/Users/nxshah5/Documents/Fabric/1.0/composer-sample-networks/packages/my-network/node_modules/gulp-license-check/index.js:41:5)
    at DestroyableTransform.Transform._read (/Users/nxshah5/Documents/Fabric/1.0/composer-sample-networks/packages/my-network/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/nxshah5/Documents/Fabric/1.0/composer-sample-networks/packages/my-network/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/nxshah5/Documents/Fabric/1.0/composer-sample-networks/packages/my-network/node_modules/readable-stream/lib/_stream_writable.js:338:64)
    at writeOrBuffer (/Users/nxshah5/Documents/Fabric/1.0/composer-sample-networks/packages/my-network/node_modules/readable-stream/lib/_stream_writable.js:327:5)
    at DestroyableTransform.Writable.write (/Users/nxshah5/Documents/Fabric/1.0/composer-sample-networks/packages/my-network/node_modules/readable-stream/lib/_stream_writable.js:264:11)
    at DestroyableTransform.ondata (/Users/nxshah5/Documents/Fabric/1.0/composer-sample-networks/packages/my-network/node_modules/readable-stream/lib/_stream_readable.js:541:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "licchk"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! my-network@0.0.1 licchk: `license-check`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-network@0.0.1 licchk script 'license-check'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the my-network package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     license-check
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my-network
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls my-network
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nxshah5/Documents/Fabric/1.0/composer-sample-networks/packages/my-network/npm-debug.log

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! my-network@0.0.1 postlint: `npm run licchk`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-network@0.0.1 postlint script 'npm run licchk'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the my-network package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run licchk
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my-network
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls my-network
npm ERR! There is likely additional logging output above.

## Your Environment

* Version used: Composer 0.7.4
* Environment name and version (MacOS, Chrome 57, node.js 6.10):

**Comment by davidkel** [comment]
Missing a single space before the * of the comment block which was fine for eslint but unfortunately causes the license check to fail, sigh.

**Comment by ramarahul** [comment]
If you follow this link https://hyperledger.github.io/composer/unstable/tutorials/developer-guide.html , you will not get the error.

**Comment by sidney803** [comment]
Thanks for davidkel's hint. I got the same error and was fixed by adding back a single space before the * of the comment block in sample.js and logic.js.

**Comment by davidkel** [comment]
Another workaround is to just disable the license check, it's irrelevant for a tutorial.
In the package.json file find the scripts section and 
In the scripts section there is a line `"licchk": "license-check",` and change it to `"licchk": "echo license-check",` (ie insert the word echo)

**Comment by sstone1** [comment]
This is fixed in the unstable docs, so closing.
