### ISSUE TITLE
Hyperledger Composer error Authenticating to the REST server

### ISSUE THREAD

**Issue by hernandezramiro** [hyperledger/composer#1203]
I have been following this Hyperledger Composer tutorial https://hyperledger.github.io/composer/integrating/enabling-rest-authentication.html and when I try to authenticate to the rest server via http://localhost:3000/auth/github I am not being redirected to the GitHub site to perform the OAuth web server authentication flow. Instead of redirecting, I am getting a 404 error message.

## Expected Behavior
According to the Composer tutorial, I would expect being redirected to the Github site to perform the OAuth.

## Actual Behavior
When I enter http://localhost:3000/auth/github I am getting a 404 error

## Your Environment
* Domposer v0.7.4
* Docker 17.03.1-ce
* Fedora 25 workstation
* Node.js 6.10.3
* Hyperledger Fabric v1.0

**Comment by dselman** [comment]
Please create a StackOverflow question for this and attach logs.

**Comment by brankoterzic** [comment]
I faced the same issue.  Here is the error stack trace:

Unhandled error for request GET /explorer/auth/github: Error: Cannot GET /explorer/auth/github
    at raiseUrlNotFoundError (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at /home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:635:15
    at next (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:174:3)
    at router (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:635:15)
Unhandled error for request GET /explorer/auth/github: Error: Cannot GET /explorer/auth/github
    at raiseUrlNotFoundError (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at /home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:635:15
    at next (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:174:3)
    at router (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:635:15)
Unhandled error for request GET /explorer/auth/github: Error: Cannot GET /explorer/auth/github
    at raiseUrlNotFoundError (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at /home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:635:15
    at next (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:174:3)
    at router (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:635:15)
Unhandled error for request GET /explorer/auth/github: Error: Cannot GET /explorer/auth/github
    at raiseUrlNotFoundError (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at /home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:635:15
    at next (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:174:3)
    at router (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:635:15)
Unhandled error for request GET /explorer/auth/github: Error: Cannot GET /explorer/auth/github
    at raiseUrlNotFoundError (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at /home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:635:15
    at next (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:174:3)
    at router (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/home/brankoterzic/.nvm/versions/node/v6.11.1/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:635:15)

**Comment by majestade** [comment]
having the same problem? did anyone solved it?

**Comment by nikosheng** [comment]
having the same problem? did anyone solved it?

**Comment by kissdani06** [comment]
I was facing the same issue. Here is my solution:

Make sure your COMPOSER_PROVIDERS enviroment variable is set.

After execute 
`export COMPOSER_PROVIDERS = {....}`
it is ONLY set the enviroment variable to THIS terminal instance.

To check this:
1.) Open a new Terminal instance

2.) Execute 
`export COMPOSER_PROVIDERS = .... `
command

3.) Execute 
  `printenv | grep ^COMPOSER_PROVIDERS `
command. It should print out your COMPOSER_PROVIDERS enviroment variables.

![kepernyokep 2018-03-13 10-01-28](https://user-images.githubusercontent.com/17273413/37332354-bdc59fa8-26a6-11e8-844e-98b72f2829c0.png)

4.) Open a new Terminal instance

5.) Execute the same command as in the 3. point
And it should print out nothing.

![kepernyokep 2018-03-13 10-11-36](https://user-images.githubusercontent.com/17273413/37332453-0a52b996-26a7-11e8-8a64-64985b886abf.png)

**SOLUTION:**

So you should set your COMPOSER_PROVIDER enviroment variable permanently.
[How do I set a user environment variable? (permanently, not session)](https://unix.stackexchange.com/questions/21598/how-do-i-set-a-user-environment-variable-permanently-not-session)

OR...

Set your enviroment variable and execute 

`composer-rest-server -c admin@my-network -m true`

in the same terminal instance.

After these you can enter:
http://localhost:3000/auth/github

**Comment by majestade** [comment]
Thanks Daniel! I have done it and worked! Do you by any chance did a client
to login with diff users in this multi user rest api?

Regards,
Pedro garcia

A terça, 13/03/2018, 09:27, Kiss Dániel <notifications@github.com> escreveu:

**Comment by AsterixMechant** [comment]
@kissdani06, sorry for the stupid question, but I'm an absolute beginner on this: where am I supposed to find the array of data to populate the COMPOSER_PROVIDERS variable? I've tried checking on the official documentation, but at the time I'm posting this, the official page is offline. Thank you very much for the solution you posted, btw! Thumbs up! Cheers

**Comment by nikosheng** [comment]
@AsterixMechant 
export COMPOSER_PROVIDERS='{"github":{"provider":"github","module":"passport-github2","clientID":"05ee45c06dbf72166d6a","clientSecret":"80419fdf374834e9a3ebfd16aacd1f1c81949ce9","authPath":"/auth/github","callbackURL":"/auth/github/callback","successRedirect":"/","failureRedirect":"/"}}'

Here is my environment variable and you have to change the oauth setting by yourself

**Comment by nikosheng** [comment]
@AsterixMechant 

COMPOSER_PROVIDERS='{"github":{"provider":"github","module":"passport-github2","clientID":"","clientSecret":"","authPath":"/auth/github","callbackURL":"/auth/github/callback","successRedirect":"/","failureRedirect":"/"}}'

Here is my environment variable and you have to fill in the oauth setting by yourself

**Comment by LeoMoonStar** [comment]
@kissdani06 
Hey buddy, i used your solution, and the browser jumped to explore page, i assume it has already passed the authorization.

But right now i tried send a request, the server tells me a business network card has not been specified

I really don't know what happened since i init the server with one business network card.

**Comment by mallapurbharat** [comment]
@LeoMoonStar If you already import this business card into the wallet which contains a 'one-time' secret, then that secret has already been used up. Hence it will not be usable after that session. 
After creation of the card, import the card to the network. Then using composer export command export this card to a new ".card" file in your folder. This exported card now has credentials in it instead of a "one-time secret" so it can be re-used any number of times!

HTH

**Comment by mallikarjunasai995** [comment]
hey everyone , am also getting the below error 

SyntaxError: Unexpected string in JSON at position 864
at JSON.parse (<anonymous>)
at Promise.then (/usr/lib/node_modules/composer-rest-server/server/server.js:147:34)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7 

in server.js file this is the following line that causing the error 
  providers = JSON.parse(process.env.COMPOSER_PROVIDERS);

**Comment by mallikarjunasai995** [comment]
hi am using ldap authentication for composer and getting the below error ... already set the envirornment variables ... 

Unhandled error for request GET /auth/ldap: Error: Cannot GET /auth/ldap
    at raiseUrlNotFoundError (/usr/lib/node_modules/composer-rest-server/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /usr/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
