### ISSUE TITLE
Error on test

### ISSUE THREAD

**Issue by djKooks** [hyperledger/composer#1232]
I have failure on running test command `lerna run test`.

## Expected Behavior
Success test

## Actual Behavior
Failure on test.
```
$ lerna run test
lerna info version 2.0.0-rc.4
lerna ERR! test Errored while running script in 'composer-common'
lerna ERR! execute Error: Command failed: npm run test
lerna ERR! execute /Users/kwangin/workspace/composer/node_modules/nyc/node_modules/semver/semver.js:293
lerna ERR! execute     throw new TypeError('Invalid Version: ' + version);
lerna ERR! execute     ^
lerna ERR! execute 
lerna ERR! execute TypeError: Invalid Version: https://registry.npmjs.org/istanbul-lib-instrument/-/istanbul-lib-instrument-1.7.1.tgz
lerna ERR! execute     at new SemVer (/Users/kwangin/workspace/composer/node_modules/nyc/node_modules/semver/semver.js:293:11)
lerna ERR! execute     at major (/Users/kwangin/workspace/composer/node_modules/nyc/node_modules/semver/semver.js:551:10)
lerna ERR! execute     at Object.<anonymous> (/Users/kwangin/workspace/composer/node_modules/nyc/node_modules/istanbul-lib-instrument/dist/constants.js:19:117)
lerna ERR! execute     at Module._compile (module.js:569:30)
lerna ERR! execute     at Object.Module._extensions..js (module.js:580:10)
lerna ERR! execute     at Module.load (module.js:503:32)
lerna ERR! execute     at tryModuleLoad (module.js:466:12)
lerna ERR! execute     at Function.Module._load (module.js:458:3)
lerna ERR! execute     at Module.require (module.js:513:17)
lerna ERR! execute     at require (internal/module.js:11:18)
lerna ERR! execute npm ERR! code ELIFECYCLE
lerna ERR! execute npm ERR! errno 1
lerna ERR! execute npm ERR! composer-common@0.7.6 test: `node ./scripts/api-changelog.js && nyc mocha --recursive -t 5000`
lerna ERR! execute npm ERR! Exit status 1
lerna ERR! execute npm ERR! 
lerna ERR! execute npm ERR! Failed at the composer-common@0.7.6 test script.
lerna ERR! execute npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR! execute 
lerna ERR! execute npm ERR! A complete log of this run can be found in:
lerna ERR! execute npm ERR!     /Users/kwangin/.npm/_logs/2017-06-10T12_28_22_031Z-debug.log
lerna ERR! execute 
lerna ERR! execute > composer-common@0.7.6 pretest /Users/kwangin/workspace/composer/packages/composer-common
lerna ERR! execute > npm run prepublish && npm run lint
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute > composer-common@0.7.6 prepublish /Users/kwangin/workspace/composer/packages/composer-common
lerna ERR! execute > pegjs ./lib/introspect/parser.pegjs && pegjs ./lib/acl/parser.pegjs && node ./scripts/tsgen.js
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute > composer-common@0.7.6 lint /Users/kwangin/workspace/composer/packages/composer-common
lerna ERR! execute > eslint .
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute /Users/kwangin/workspace/composer/packages/composer-common/lib/codegen/fromjs/plantumlgenerator.js
```

## Your Environment
I am working on MacOS Sierra. Is this project not supporting MacOS?

**Comment by dselman** [comment]
I've never seen that error and use/develop Composer on Mac OS X. Can you please check you are using the supported versions of npm and node.

**Comment by DavideDaniel** [comment]
we do not use composer and are seeing this also.. most likely it's a lerna issue since we have a lerna repo as well
