### ISSUE TITLE
The Acorn parser should specify a filename when a Javascript error occurs

### ISSUE THREAD

**Issue by pd93** [hyperledger/composer#1372]
## Context
When running `npm install` to create a `.bna` file, Javascript errors are caught by the Acorn parser. Unfortunately, the output does not specify a filename. This makes it difficult to debug projects with many Javascript files or for beginners who don't understand where the error is coming from. Providing a filename would make it much easier to debug without help from others. The line/column numbers could also be made more explicit.

## Expected Behavior
The error should be clear and concise:
eg. `<error_type>: <error>: <filename> (<line>, <column>)`
Below is an amended version of the actual output
```
.....
SyntaxError: Unexpected token: <filename> (Line 19, Column 16)
.....
```

## Actual Behavior
Below is the **full** output currently given by the Acorn parser
```
Creating Business Network Archive

Looking for package.json of Business Network Definition
	Input directory: <project_dir>
<project_dir>/node_modules/composer-cli/node_modules/yargs/yargs.js:1079
      else throw err
           ^

SyntaxError: Unexpected token (19:16)
    at Parser.pp$4.raise (<project_dir>/node_modules/acorn/dist/acorn.js:2488:13)
    at Parser.pp.unexpected (<project_dir>/node_modules/acorn/dist/acorn.js:623:8)
    at Parser.pp$3.parseExprAtom (<project_dir>/node_modules/acorn/dist/acorn.js:2011:10)
    at Parser.pp$3.parseExprSubscripts (<project_dir>/node_modules/acorn/dist/acorn.js:1872:19)
    at Parser.pp$3.parseMaybeUnary (<project_dir>/node_modules/acorn/dist/acorn.js:1849:17)
    at Parser.pp$3.parseExprOps (<project_dir>/node_modules/acorn/dist/acorn.js:1791:19)
    at Parser.pp$3.parseMaybeConditional (<project_dir>/node_modules/acorn/dist/acorn.js:1774:19)
    at Parser.pp$3.parseMaybeAssign (<project_dir>/node_modules/acorn/dist/acorn.js:1750:19)
    at Parser.pp$3.parseMaybeAssign (<project_dir>/node_modules/acorn/dist/acorn.js:1761:23)
    at Parser.pp$3.parseExprList (<project_dir>/node_modules/acorn/dist/acorn.js:2418:20)
```

## Steps to Reproduce
1. Open up the `basic-sample-network` in an editor
2. Open up `/lib/logic.js` and create an error.
    - I accidentally used the `.then(() => {});` syntax instead of the traditional `.then(function() {});` when running into this problem, but any syntax error should work.
3. Save the file and run `npm install`.

## Your Environment
* Version used: Composer v0.8.0
* Environment: VSCode, Node 6.11.0, NPM 3.10.10
* Operating System: Ubuntu 16.04

**Comment by bestbeforetoday** [comment]
This issue is resolved by pull request #1883.

Parse errors should now look something like:
> SyntaxError: Failed to parse yourFilename.js: Unexpected token: (Line 19, Column 16)

Trace is also captured, which includes this error and the content of the file being parsed.
