### ISSUE TITLE
Parser error during archiving business network: const is reserved

### ISSUE THREAD

**Issue by aabdulwahed** [hyperledger/composer#1439]
I'm unable to create an archive using basic network samples "Digital Property network model". 
## Context

I always get the following error 

## Expected Behavior

Network archived!

## Actual Behavior

```
azureuser@hyperledger101:~/.nvm/v6.9.5/lib/node_modules/composer-cli$ composer archive create --archiveFile digitialPropertyNetwork.zip --sourceType module --sourceName digitalproperty-network

Creating Business Network Archive


Looking for package.json of Business Network Definition
        Input directory: /home/azureuser/.nvm/v6.9.5/lib/node_modules/digitalproperty-network
/home/azureuser/.nvm/v6.9.5/lib/node_modules/composer-cli/node_modules/yargs/yargs.js:1079
      else throw err
           ^

SyntaxError: The keyword 'const' is reserved (17:0)
    at Parser.pp$4.raise (/home/azureuser/.nvm/v6.9.5/lib/node_modules/composer-cli/node_modules/acorn/dist/acorn.js:2488:13)
    at Parser.pp$3.parseIdent (/home/azureuser/.nvm/v6.9.5/lib/node_modules/composer-cli/node_modules/acorn/dist/acorn.js:2436:12)
    at Parser.pp$3.parseExprAtom (/home/azureuser/.nvm/v6.9.5/lib/node_modules/composer-cli/node_modules/acorn/dist/acorn.js:1946:19)
    at Parser.pp$3.parseExprSubscripts (/home/azureuser/.nvm/v6.9.5/lib/node_modules/composer-cli/node_modules/acorn/dist/acorn.js:1872:19)
    at Parser.pp$3.parseMaybeUnary (/home/azureuser/.nvm/v6.9.5/lib/node_modules/composer-cli/node_modules/acorn/dist/acorn.js:1849:17)
    at Parser.pp$3.parseExprOps (/home/azureuser/.nvm/v6.9.5/lib/node_modules/composer-cli/node_modules/acorn/dist/acorn.js:1791:19)
    at Parser.pp$3.parseMaybeConditional (/home/azureuser/.nvm/v6.9.5/lib/node_modules/composer-cli/node_modules/acorn/dist/acorn.js:1774:19)
    at Parser.pp$3.parseMaybeAssign (/home/azureuser/.nvm/v6.9.5/lib/node_modules/composer-cli/node_modules/acorn/dist/acorn.js:1750:19)
    at Parser.pp$3.parseExpression (/home/azureuser/.nvm/v6.9.5/lib/node_modules/composer-cli/node_modules/acorn/dist/acorn.js:1722:19)
    at Parser.pp$1.parseStatement (/home/azureuser/.nvm/v6.9.5/lib/node_modules/composer-cli/node_modules/acorn/dist/acorn.js:777:45)
```

## Your Environment
* Version used: composer-cli v0.9.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
 nodejs --version
v0.10.25
* Operating System and version (desktop or mobile): Ubuntu 14.04

**Comment by dselman** [comment]
I was able to run `npm test` for the digitialproperty-network without any issues. Can you check your node version please.

$ node --version
v6.9.5

Please open a question of StackOverflow if you still have issues.
