### ISSUE TITLE
Build sometimes fails with ENDORSEMENT_POLICY_FAILURE

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1840]
Due to the fact that we invoke another transaction before the peer in the org we don't belong to hasn't committed the block in time.

We need to find a way to be able to listen for events from a peer not in the same organisation as the requester or we change it around and be a single org with 2 peers to catch nondeterministic problems.

**Comment by davidkel** [comment]
The problem probably still exists but is now circumvented by mocha retries

**Comment by davidkel** [comment]
This will be addressed with the new channel events implementation.

**Comment by davidkel** [comment]
The assumption has always been for this that we submit a transaction too soon after the previous one because we can't listen for transaction events from the other organisation. However with the new channel events implementation which can listen for transaction committed events we get this
```
  1) Historian "before all" hook:
     Error: Error trying invoke business network. Error: Peer localhost:7051 has rejected transaction 'dc3adabf8b6ab0ba82aff66dfbbfc72cd5a861959a33b71c1244b99353731c60' with code ENDORSEMENT_POLICY_FAILURE
      at _initializeChannel.then.then.then.then.catch (/home/travis/build/hyperledger/composer/packages/composer-connector-hlfv1/lib/hlfconnection.js:1004:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```
so the endorsement policy failure still occurs.

**Comment by davidkel** [comment]
Closing as the build retry capability now hides this problem and have never been able to recreate.
