### ISSUE TITLE
ModelManager.addModelFiles error message is incomplete

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1968]
We have a lot of error messages that don't include information about what was wrong and where for example:

```
Error: namespace already exists
    at ModelManager.addModelFiles (/usr/lib/node_modules/composer-cli/node_modules/composer-common/lib/modelmanager.js:234:31)
    at Function.fromDirectory (/usr/lib/node_modules/composer-cli/node_modules/composer-common/lib/businessnetworkdefinition.js:493:43)
    at Function.handler (/usr/lib/node_modules/composer-cli/lib/cmds/archive/lib/create.js:80:42)
    at Object.module.exports.handler (/usr/lib/node_modules/composer-cli/lib/cmds/archive/createCommand.js:31:30)
    at Object.self.runCommand (/usr/lib/node_modules/composer-cli/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/usr/lib/node_modules/composer-cli/node_modules/yargs/yargs.js:990:30)
    at Object.self.runCommand (/usr/lib/node_modules/composer-cli/node_modules/yargs/lib/command.js:204:45)
    at Object.Yargs.self._parseArgs (/usr/lib/node_modules/composer-cli/node_modules/yargs/yargs.js:990:30)
    at Object.get [as argv] (/usr/lib/node_modules/composer-cli/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/usr/lib/node_modules/composer-cli/cli.js:58:5)
```
It would be more user friendly to say which namespace, and the files/lines where the conflict occurs.

**Comment by shacshar** [comment]
I fix this

**Comment by shacshar** [comment]
The trick to add callee file/line number is to read this information from the stack. So one has to get handle of stack by throwing a dummy error and then read desired information from the stack. 
The earlier method to get line number etc directly has been deprecated.

**Comment by davidkel** [comment]
Looks like the fix could just be
```
            throw new Error ('namespace '+m.getNamespace()+' in model file ' +m.getName()+' already defined in '+this.modelFiles[m.getNamespace().getName()]  );
```
in ModelManager.js where the following is called
```
            throw new Error('namespace already exists');
```
