### ISSUE TITLE
LoopbackVisitor fails with valid model file

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#2193]
## Context

A valid model file causes the LoopbackVisitor to crash due to a recursion issue.

## Expected Behavior
It should not crash with a hard to debug RangeError.

## Actual Behavior
It crashed due to an infinite recursion due to visiting a property with the same type as the owning class.
https://github.com/hyperledger/composer/blob/master/packages/composer-common/lib/codegen/fromcto/loopback/loopbackvisitor.js#L373

Stack:

```
1) LoopbackVisitor namespaces = undefined #visit should generate Loopback model files for each type when given a model manager:
     RangeError: Maximum call stack size exceeded
      at LoopbackVisitor.visitClassDeclarationCommon (lib/codegen/fromcto/loopback/loopbackvisitor.js:352:23)
      at LoopbackVisitor.visitAssetDeclaration (lib/codegen/fromcto/loopback/loopbackvisitor.js:187:21)
      at LoopbackVisitor.visit (lib/codegen/fromcto/loopback/loopbackvisitor.js:74:25)
      at AssetDeclaration.accept (lib/introspect/decorated.js:54:24)
      at LoopbackVisitor.visitField (lib/codegen/fromcto/loopback/loopbackvisitor.js:494:18)
      at LoopbackVisitor.visit (lib/codegen/fromcto/loopback/loopbackvisitor.js:86:25)
      at Field.accept (lib/introspect/decorated.js:54:24)
      at classDeclaration.getProperties.forEach (lib/codegen/fromcto/loopback/loopbackvisitor.js:373:66)
      at Array.forEach (<anonymous>)
      at LoopbackVisitor.visitClassDeclarationCommon (lib/codegen/fromcto/loopback/loopbackvisitor.js:370:42)
      at LoopbackVisitor.visitAssetDeclaration (lib/codegen/fromcto/loopback/loopbackvisitor.js:187:21)
      at LoopbackVisitor.visit (lib/codegen/fromcto/loopback/loopbackvisitor.js:74:25)
      at AssetDeclaration.accept (lib/introspect/decorated.js:54:24)
      at LoopbackVisitor.visitField (lib/codegen/fromcto/loopback/loopbackvisitor.js:494:18)
      at LoopbackVisitor.visit (lib/codegen/fromcto/loopback/loopbackvisitor.js:86:25)
      at Field.accept (lib/introspect/decorated.js:54:24)
      at classDeclaration.getProperties.forEach (lib/codegen/fromcto/loopback/loopbackvisitor.js:373:66)
      at Array.forEach (<anonymous>)
      at LoopbackVisitor.visitClassDeclarationCommon (lib/codegen/fromcto/loopback/loopbackvisitor.js:370:42)
      at LoopbackVisitor.visitAssetDeclaration (lib/codegen/fromcto/loopback/loopbackvisitor.js:187:21)
      at LoopbackVisitor.visit (lib/codegen/fromcto/loopback/loopbackvisitor.js:74:25)
      at AssetDeclaration.accept (lib/introspect/decorated.js:54:24)
      at LoopbackVisitor.visitField (lib/codegen/fromcto/loopback/loopbackvisitor.js:494:18)
      at LoopbackVisitor.visit (lib/codegen/fromcto/loopback/loopbackvisitor.js:86:25)
      at Field.accept (lib/introspect/decorated.js:54:24)
      at classDeclaration.getProperties.forEach (lib/codegen/fromcto/loopback/loopbackvisitor.js:373:66)
      at Array.forEach (<anonymous>)
```

## Steps to Reproduce
1. Run the LoopbackVisitor agains the attached CTO file
2.
3.
4.

## Existing issues
https://stackoverflow.com/questions/46241749/rangeerror-deploying-bna-file-to-composer-rest-server/46319130?noredirect=1#comment79606250_46319130

## Your Environment
* Version used: 0.12.2
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by dselman** [comment]
[circular.txt](https://github.com/hyperledger/composer/files/1320590/circular.txt)

**Comment by dselman** [comment]
Fixed
