### ISSUE TITLE
Unable to connect to CouchDB

### ISSUE THREAD

**Issue by ronaldpetty** [hyperledger/composer#2218]
It seems fabric-peer is looking at the wrong IP for couchDB (or is this phoning home?)

```
export FABRIC_START_TIMEOUT=180
curl -sSL https://hyperledger.github.io/composer/install-hlfv1.sh | bash
...
# Create the channel
docker exec peer0.org1.example.com peer channel create -o orderer.example.com:7050 -c composerchannel -f /etc/hyperledger/configtx/composer-channel.tx
Error response from daemon: Container f8e4835b68e8f92e1133439b9fc9a76ddbebd8e463fea5114c9daf6dff67da6c is not running
```

```
docker container logs f8
...
2017-09-24 10:09:18.413 UTC [couchdb] handleRequest -> WARN 024 Retrying couchdb request in 1m4s. Attempt:10  Error:Get http://couchdb:5984/: dial tcp 66.96.162.149:5984: getsockopt: connection refused
2017-09-24 10:10:22.414 UTC [couchdb] VerifyCouchConfig -> DEBU 025 Exiting VerifyCouchConfig()
panic: Error in instantiating ledger provider: Unable to connect to CouchDB, check the hostname and port: Get http://couchdb:5984/: dial tcp 66.96.162.149:5984: getsockopt: connection refused

goroutine 1 [running]:
panic(0xc970e0, 0xc420302100)
	/opt/go/src/runtime/panic.go:500 +0x1a1
github.com/hyperledger/fabric/core/ledger/ledgermgmt.initialize()
	/opt/gopath/src/github.com/hyperledger/fabric/core/ledger/ledgermgmt/ledger_mgmt.go:61 +0x2fe
github.com/hyperledger/fabric/core/ledger/ledgermgmt.Initialize.func1()
	/opt/gopath/src/github.com/hyperledger/fabric/core/ledger/ledgermgmt/ledger_mgmt.go:49 +0x14
sync.(*Once).Do(0x1446828, 0xe2fa88)
	/opt/go/src/sync/once.go:44 +0xdb
github.com/hyperledger/fabric/core/ledger/ledgermgmt.Initialize()
	/opt/gopath/src/github.com/hyperledger/fabric/core/ledger/ledgermgmt/ledger_mgmt.go:50 +0x39
github.com/hyperledger/fabric/peer/node.serve(0xc420303ab0, 0x0, 0x1, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/peer/node/start.go:88 +0x113
github.com/hyperledger/fabric/peer/node.glob..func1(0x13ed260, 0xc420303ab0, 0x0, 0x1, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/peer/node/start.go:75 +0x3f
github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).execute(0x13ed260, 0xc420303a90, 0x1, 0x1, 0x13ed260, 0xc420303a90)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:599 +0x234
github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x13ed8c0, 0xf, 0xc420012035, 0x7)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:689 +0x367
github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).Execute(0x13ed8c0, 0x19, 0xc420012035)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/opt/gopath/src/github.com/hyperledger/fabric/peer/main.go:118 +0x54e
user@ubuntu:~$
```

**Comment by gabrielpsilva** [comment]
I had this problem, but with the peer image instead of the couchdb. I didn't resolve the issue but here is a work around.

add this line under the image name in the files composer-data/docker-compose-playground.yml and 
composer-data/fabric-dev-servers/fabric-scripts/hlfv1/composer/docker-compose.yml

 `  dns_search: .  `

the file should look like this:

`peer0.org1.example.com:

    container_name: peer0.org1.example.com

    image: hyperledger/fabric-peer:x86_64-1.0.0

    dns_search: .

    environment:

       - CORE_LOGGING_PEER=debug`


just keep in mind that composer.sh deletes and rewrites the folder composer-data every time you run the script, so you should comment the lines responsible to delete and rewrite it.

here are the lines I have commented:
`34: rm -rf "${WORKDIR}" && mkdir -p "${WORKDIR}"`
`44: tail -n +${PAYLOAD_START} "${SOURCE}" | tar -xzf -`

**Comment by dselman** [comment]
What system and docker version are you seeing this on?

**Comment by ronaldpetty** [comment]
@gabrielpsilva thanks for the detailed response.  I had actually rebooted and it started working.  I had a hunch there was some memory issue on my laptop.  So odd, if it happens again will try your path.  Thanks again.
