### ISSUE TITLE
status: 500, message: Error: The current identity has not been registered: Admin@node007.example.com

### ISSUE THREAD

**Issue by denisglotov** [hyperledger/composer#2435]
It all works with 0.13.2. The problems started when I switched to 0.14.1:

My workflow is the following:
1. Start fabric network with TLS, create my-channel, join orgs to it.
2. composer identity import -p mainorg -u MainPeerAdmin \
       -c crypto-config/.../Admin@example.com-cert.pem -k crypto-config/.../keystore/..._sk
3. composer runtime install -n my-network -p mainorg -i MainPeerAdmin -s randomString
4. composer network start -a my-network.bna -p mainorg -i MainPeerAdmin -s randomString \
       -A admin -S
5. composer-rest-server -p mainorg -n my-network -i MainPeerAdmin -s randomString \
       -N never -w true

Step (5) brings the error:

```
Discovering types from business network definition ...
Connection fails: Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered:
Admin@node007.example.com)
It will be retried for the next request.
Exception: Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered: Admin@node007.example.com)
Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered: Admin@node007.example.com)
    at _checkRuntimeVersions.then.catch (/home/denis/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:663:34) 
```

Now if I try admin:
5'. composer-rest-server -p mainorg -n my-network -i admin -s adminpw -N never -w true

I get the error
```
Discovering types from business network definition ...
Connection fails: Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: write EPROTO 140340025800512:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
]
It will be retried for the next request.
Exception: Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: write EPROTO 140340025800512:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
]
Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: write EPROTO 140340025800512:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
]
    at client.getUserContext.then.then.catch (/home/denis/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:302:34)
```
and I continue seeing this error even if I use fake `-i admin111 -s adminpw111`.

I have read [Release notes for 0.14](https://github.com/hyperledger/composer/releases/tag/v0.14.0) and applied changes from there, in particular that `-A admin -S` at step 4.

For Composer 0.13.2, this workflow works as intended.

## Your Environment
```
denis@node007:~$ composer-rest-server --version
v0.14.1
denis@node007:~$ composer --version
v0.14.1
denis@node007:~$ docker --version
Docker version 17.09.0-ce, build afdb6d4
denis@node007:~$ docker-compose --version
docker-compose version 1.13.0, build 1719ceb
denis@node007:~$ uname
Linux
denis@node007:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
```

**Comment by davidkel** [comment]
@denisglotov PeerAdmin definitions should only be used to install and start or deploy business networks. As you bound admin as a network admin try starting the rest server with admin
composer-rest-server -p mainorg -n my-network -i admin -s adminpw 
-N never -w true

**Comment by denisglotov** [comment]
This is what step 5' above is about, does not work.

**Comment by davidkel** [comment]
The error now is that you look as though you are trying to connect over TLS to a system that isn't expecting TLS. Specifically It looks like the fabric ca server you are trying to contact over TLS but it isn't expecting TLS. What does your connection profile look like ?

**Comment by denisglotov** [comment]
This is the connection profile for mainorg:
```{
    "type": "hlfv1",
    "orderers": [
        {
            "url": "grpcs://localhost:7050",
            "hostnameOverride": "orderer.node007.example.com",
            "cert": "crypto-config/ordererOrganizations/node007.example.com/orderers/orderer.node007.example.com/tls/ca.crt"
        }
    ],
    "ca": {
        "url": "https://localhost:7054",
        "name": "ca.node007.example.com",
        "trustedRoots": [],
        "verify": true
    },
    "peers": [
        {
            "requestURL": "grpcs://localhost:7051",
            "eventURL": "grpcs://localhost:7053",
            "hostnameOverride": "peer0.node007.example.com",
            "cert": "crypto-config/peerOrganizations/node007.example.com/peers/peer0.node007.example.com/tls/ca.crt"
        }
    ],
    "keyValStore": ".composer-credentials/mainorg",
    "channel": "my-channel",
    "mspID": "MainOrgMSP",
    "timeout": "300"
}```

**Comment by davidkel** [comment]
So try changing the following to see if it works
```
"ca": {
        "url": "http://localhost:7054",
        "name": "ca.node007.example.com"
    }
```
Because the error implies you are trying to communicate with the CA over TLS but the CA is not configured to work over TLS.
Also can you post how you define your fabric setup ?

**Comment by denisglotov** [comment]
Thank you, right, it worked after changing https -> http. Bad for my ca's...
