### ISSUE TITLE
npm test fails for all sample networks

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2612]
All the npm tests on the sample networks when 0.15.0 is released with errors like
```
  1) Vehicle Lifecycle Network "before all" hook:
     Error: Card not found: defaultProfile
      at IdCard.fromDirectory.catch.cause (node_modules/composer-common/lib/cardstore/filesystemcardstore.js:73:27)
      at <anonymous>

  2) Vehicle Lifecycle Network "before all" hook:
     Error: Card not found: defaultProfile
      at IdCard.fromDirectory.catch.cause (node_modules/composer-common/lib/cardstore/filesystemcardstore.js:73:27)
      at <anonymous>

  3) Vehicle Lifecycle Network "before each" hook for "should be able to transfer a vehicle between two private owners":
     Error: Card not found: defaultProfile
      at IdCard.fromDirectory.catch.cause (node_modules/composer-common/lib/cardstore/filesystemcardstore.js:73:27)
      at <anonymous>
```
The samples need updating and have to be pushed once the release goes live, also these samples will then not work with previous versions of composer.

**Comment by davidkel** [comment]
The sample networks are still using 0.14.x modules we should move them to 0.15.x and fix the tests.

**Comment by bestbeforetoday** [comment]
Already covered by #2523
