### ISSUE TITLE
Rest Server explorer hangs when issuing an identity

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2647]
Made the noob mistake (cause people will) tried to issue an identity to a participant through explorer with Json of
```
{
  "participant": "JD",
  "userID": "JackDaniels"
}
```
And explorer hangs with working animation as seen here
![image](https://user-images.githubusercontent.com/25582377/32602910-ced6709c-c53f-11e7-8fcc-8e620130f8de.png)

In the rest console I see
```
Unhandled error for request POST /api/system/identities/issue: Error: Missing namespace
    at new ResourceId (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/model/resourceid.js:42:19)
    at Function.fromURI (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/model/resourceid.js:96:16)
    at Function.fromURI (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/model/relationship.js:77:39)
    at BusinessNetworkConnection.issueIdentity (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/composer-client/lib/businessnetworkconnection.js:826:40)
    at ensureConnected.then (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/loopback-connector-composer/lib/businessnetworkconnector.js:909:50)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by davidkel** [comment]
Re-opening as the fix was backed out due to other issues it was causing.

**Comment by tanaybhartia** [comment]
I am having the same issue. Explorer hangs with the same animation.

**Comment by 17Deepika** [comment]
@davidkel Getting the same error while trying to issue a participant identity using composer REST api. How can I fix the issue.?
