### ISSUE TITLE
Rest server multiuser mode, explorer hangs on any request if no default card in wallet.

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2651]
No card imported into wallet, but tried to issue an identity. UI hangs with no response, error received in console
```
Treating unknown remoting type "issueidentityrequest" as "any"
Unhandled error for request POST /api/system/identities/issue: Error: A business network card has not been specified
    at BusinessNetworkConnector.getConnectionWrapper (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/loopback-connector-composer/lib/businessnetworkconnector.js:90:23)
    at BusinessNetworkConnector.ensureConnected (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/loopback-connector-composer/lib/businessnetworkconnector.js:129:21)
    at BusinessNetworkConnector.issueIdentity (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/loopback-connector-composer/lib/businessnetworkconnector.js:905:21)
    at Promise (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/server/boot/composer-discovery.js:385:23)
    at new Promise (<anonymous>)
    at Function.System.issueIdentity (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/server/boot/composer-discovery.js:384:16)
    at SharedMethod.invoke (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/strong-remoting/lib/shared-method.js:270:25)
    at HttpContext.invoke (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/strong-remoting/lib/http-context.js:297:12)
    at phaseInvoke (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/strong-remoting/lib/remote-objects.js:677:9)
    at runHandler (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/strong-remoting/node_modules/loopback-phase/lib/phase.js:135:5)
    at iterate (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)
    at Object.async.eachSeries (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:162:9)
    at runHandlers (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/strong-remoting/node_modules/loopback-phase/lib/phase.js:144:13)
    at iterate (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)
    at /home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:157:25
    at /home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25
```

**Comment by sstone1** [comment]
Collapsing into defect #2647 which is bound to be the same thing; @andrew-coleman is looking at it.

**Comment by userksm** [comment]
Got any solution for this. After adding new transaction processor function i am also getting same error. I have even updated .cto file accordingly. On the console i got this error.
Unhandled error for request POST /api/Cash: TypeNotFoundException: Type Cash is not defined in namespace org.abc.network

On browser i am getting: Error: 500 - Internal Server Error
