### ISSUE TITLE
Composer network deploy gives unhelpful error if missing a parameter

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2671]
```
$ composer network deploy -a decentralized-energy-network.bna -A admin -S adminpw
Deploying business network from archive: decentralized-energy-network.bna
/usr/local/lib/node_modules/composer-cli/node_modules/yargs/yargs.js:1100
      else throw err
           ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at FileSystemCardStore._cardPath (/usr/local/lib/node_modules/composer-cli/node_modules/composer-common/lib/cardstore/filesystemcardstore.js:63:21)
    at FileSystemCardStore.get (/usr/local/lib/node_modules/composer-cli/node_modules/composer-common/lib/cardstore/filesystemcardstore.js:71:42)
    at AdminConnection.getCard (/usr/local/lib/node_modules/composer-cli/node_modules/composer-admin/lib/adminconnection.js:150:31)
    at Function.handler (/usr/local/lib/node_modules/composer-cli/lib/cmds/network/lib/deploy.js:56:32)
    at Object.module.exports.handler (/usr/local/lib/node_modules/composer-cli/lib/cmds/network/deployCommand.js:43:37)
    at Object.runCommand (/usr/local/lib/node_modules/composer-cli/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/composer-cli/node_modules/yargs/yargs.js:1013:30)
    at Object.runCommand (/usr/local/lib/node_modules/composer-cli/node_modules/yargs/lib/command.js:194:45)
```
There are probably more cli commands which have the same problem, some have been fixed already but not all.
Also it would seem the help is not saying the -c option is a required parameter

**Comment by mbwhite** [comment]
Updated command
```
composer network deploy [options]

Deploys a business network to the Hyperledger Fabric

Deploy Options
  --loglevel, -l                     The initial loglevel to set  [choices: "INFO", "WARNING", "ERROR", "DEBUG"]
  --file, -f                         File name of the card to be created  [string]
  --archiveFile, -a                  The business network archive file name  [string] [required]
  --networkAdmin, -A                 The identity name of the business network administrator  [string] [required]
  --networkAdminCertificateFile, -C  The certificate of the business network administrator  [string]
  --networkAdminEnrollSecret, -S     The enrollment secret for the business network administrator  [string]
  --card, -c                         The cardname to use to deploy the network  [string] [required]

Options:
  --help             Show help  [boolean]
  -v, --version      Show version number  [boolean]
  --option, -o       Options that are specific specific to connection. Multiple options are specified by repeating this option  [string]
  --optionsFile, -O  A file containing options that are specific to connection  [string]

Missing required argument: card
```

**Comment by vpramoth** [comment]
I also got a similar error. When I followed the tutorials, while deploying in hyperledger fabric I got this error.
Missing argument value: networkAdminEnrollSecret
![ex](https://user-images.githubusercontent.com/8606203/32690584-0f040bb2-c71f-11e7-92cc-3852b0572337.png)

**Comment by mbwhite** [comment]
Resolved in PR #2692

**Comment by bhemeswararao** [comment]
![image](https://user-images.githubusercontent.com/37216008/51591031-e77aca80-1f11-11e9-9602-11d266381c1f.png)

**Comment by bhemeswararao** [comment]
how to resolve this above error
