### ISSUE TITLE
Programmatic network start/deploy does not produce a usable network admin identity

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#2752]
Tested with the embedded connector...

First issue is that there is no mechanism documented on the API for binding the network admin identity on network start/deploy.

More significant problem is that, using the (undocumented) _card_ optional property to supply an identity to use as the network admin produces the following errors:
- With a card containing _enrollmentSecret_ and no credentials:
```javascript
     ValidationException: Instance org.hyperledger.composer.system.BindIdentity#99c415e4-402a-4228-aea3-b4503aa79fd8 missing required field certificate
      at Function.reportMissingRequiredProperty (node_modules/composer-common/lib/serializer/resourcevalidator.js:480:15)
      at ResourceValidator.visitClassDeclaration (node_modules/composer-common/lib/serializer/resourcevalidator.js:178:39)
      at ResourceValidator.visit (node_modules/composer-common/lib/serializer/resourcevalidator.js:74:25)
      at TransactionDeclaration.accept (node_modules/composer-common/lib/introspect/decorated.js:54:24)
      at ResourceValidator.checkItem (node_modules/composer-common/lib/serializer/resourcevalidator.js:345:30)
      at ResourceValidator.checkArray (node_modules/composer-common/lib/serializer/resourcevalidator.js:272:18)
      at ResourceValidator.visitField (node_modules/composer-common/lib/serializer/resourcevalidator.js:218:22)
      at ResourceValidator.visit (node_modules/composer-common/lib/serializer/resourcevalidator.js:78:25)
      at Field.accept (node_modules/composer-common/lib/introspect/decorated.js:54:24)
      at ResourceValidator.visitClassDeclaration (node_modules/composer-common/lib/serializer/resourcevalidator.js:174:26)
      at ResourceValidator.visit (node_modules/composer-common/lib/serializer/resourcevalidator.js:74:25)
      at TransactionDeclaration.accept (node_modules/composer-common/lib/introspect/decorated.js:54:24)
      at Serializer.toJSON (node_modules/composer-common/lib/serializer.js:97:30)
      at Promise.resolve.then.then.then (node_modules/composer-admin/lib/adminconnection.js:534:57)
      at <anonymous>
```
- Using a card containing credentials (in this case a dummy certificate and private key), when subsequently attempting to issue a new identity for a participant:
```javascript
     TypeError: Cannot read property 'issuer' of undefined
      at EmbeddedConnection.createIdentity (node_modules/composer-connector-embedded/lib/embeddedconnection.js:390:38)
      at getParticipantRegistry.then.then (node_modules/composer-client/lib/businessnetworkconnection.js:839:44)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by bestbeforetoday** [comment]
This should be resolved by #2753
