### ISSUE TITLE
Failed to execute transaction (Timeout expired while executing transaction) - using CouchDB/LevelDB

### ISSUE THREAD

**Issue by ykcai** [hyperledger/composer#2801]
## Context
Flooding the Composer Network with a bunch of REST API calls to create assets/participants and other transactions (around 1000+ transactions) will slow the network down and eventually throw timeout errors when querying the HistorianRecords

## Expected Behavior
Should return my results throw the REST API interface.

## Actual Behavior
Throw the error
```
{"error":{"statusCode":500,"name":"Error","message":"Error trying to query business network. Error: Error executing chaincode: Failed to execute transaction (Timeout expired while executing transaction)","stack":"Error: Error trying to query business network. Error: Error executing chaincode: Failed to execute transaction (Timeout expired while executing transaction)\n    at channel.queryByChaincode.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:749:34)"}}
```
## Steps to Reproduce
1. Fresh install of Hyperledger Composer and all its dependencies for `composer-cli@0.14.2`
2. Deploy the network to Kubernetes with `ibm-container-service` or run the local setup scripts in from fabric-tools
3. Create a script that will interact and call the APIs generated from `composer-rest-server@0.14.2`. This script needs to loop maybe 1000 times, create random things (assets, participants, transactions)
4. Write a query to the Historian or just query the API endpoint `/api/system/historian` and wait for the response - should give you error if you have more than 1000+ transactions on the ledger. 

## Existing issues
Found an older issue but it was closed a while back
https://github.com/hyperledger/composer/issues/2758
https://github.com/hyperledger/composer/issues/1670

## Context
In a production level or a traffic dev environment this would cause a lot of issues especially if other queries start to fail as well. 

## Your Environment
* `composer-cli@v0.14.2`
* `node@8.9.1`
* `npm@5.5.1`
* Kubernetes : 
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.4-1+1540c973d4ff9d", GitCommit:"1540c973d4ff9da2d6a204a7709084488a459ed4", GitTreeState:"clean", BuildDate:"2017-10-06T15:08:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Docker: 
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
### Peer Logs: 
```
...
2017-11-21 23:09:49.463 UTC [lockbasedtxmgr] Next -> DEBU 109077 queryResultsItr.Next() returned a record:{"$class":"org.hyperledger.composer.system.HistorianRecord","$registryId":"org.hyperledger.composer.system.HistorianRecord","$registryType":"Asset","eventsEmitted":[],"identityUsed":"resource:org.hyperledger.composer.system.Identity#77749324a1668aa449cfbd91f6ed455a1aff154a53c0712cd302a22e7da7fd13","participantInvoking":"resource:org.hyperledger.composer.system.NetworkAdmin#admin","transactionId":"56af80b08cbbf2162b7eb0b733294c7a2cd68136b389c4c53c2af649c824c3c6","transactionInvoked":"resource:org.hyperledger.composer.system.AddParticipant#56af80b08cbbf2162b7eb0b733294c7a2cd68136b389c4c53c2af649c824c3c6","transactionTimestamp":"2017-11-21T18:13:39.031Z","transactionType":"org.hyperledger.composer.system.AddParticipant"}
2017-11-21 23:09:49.464 UTC [chaincode] func1 -> DEBU 109078 Got keys and values. Sending RESPONSE
2017-11-21 23:09:49.464 UTC [chaincode] 1 -> DEBU 109079 [987669f4]handleQueryStateNext serial send RESPONSE
2017-11-21 23:09:49.481 UTC [chaincode] processStream -> DEBU 10907a [987669f4]Received message QUERY_STATE_NEXT from shim
2017-11-21 23:09:49.481 UTC [chaincode] HandleMessage -> DEBU 10907b [987669f4]Fabric side Handling ChaincodeMessage of type: QUERY_STATE_NEXT in state ready
2017-11-21 23:09:49.481 UTC [chaincode] afterQueryStateNext -> DEBU 10907c Received QUERY_STATE_NEXT, invoking query state next from ledger
2017-11-21 23:09:49.481 UTC [chaincode] afterQueryStateNext -> DEBU 10907d Exiting QUERY_STATE_NEXT
2017-11-21 23:09:49.481 UTC [chaincode] filterError -> DEBU 10907e Ignoring NoTransitionError: no transition
2017-11-21 23:09:49.481 UTC [lockbasedtxmgr] Next -> DEBU 10907f queryResultsItr.Next() returned a record:{"$class":"org.hyperledger.composer.system.HistorianRecord","$registryId":"org.hyperledger.composer.system.HistorianRecord","$registryType":"Asset","eventsEmitted":[],"identityUsed":"resource:org.hyperledger.composer.system.Identity#7d195e0cbc77f47d78f39e21ec879210cdff2f8506d5f326af245563ebfcbb69","transactionId":"ae6ab750-1a91-4729-aa39-a7808298cb4c","transactionInvoked":"resource:org.hyperledger.composer.system.ActivateCurrentIdentity#ae6ab750-1a91-4729-aa39-a7808298cb4c","transactionTimestamp":"2017-11-21T18:09:33.731Z","transactionType":"org.hyperledger.composer.system.ActivateCurrentIdentity"}
2017-11-21 23:09:49.481 UTC [lockbasedtxmgr] Next -> DEBU 109080 queryResultsItr.Next() returned a record:{"$class":"org.hyperledger.composer.system.HistorianRecord","$registryId":"org.hyperledger.composer.system.HistorianRecord","$registryType":"Asset","eventsEmitted":[],"transactionId":"fa614b8b-4d68-40c0-b5e7-eb22de640715","transactionInvoked":"resource:org.hyperledger.composer.system.StartBusinessNetwork#fa614b8b-4d68-40c0-b5e7-eb22de640715","transactionTimestamp":"2017-11-21T18:08:34.745Z","transactionType":"org.hyperledger.composer.system.StartBusinessNetwork"}
2017-11-21 23:09:49.482 UTC [lockbasedtxmgr] Next -> DEBU 109081 queryResultsItr.Next() returned a record:{"$class":"org.hyperledger.composer.system.HistorianRecord","$registryId":"org.hyperledger.composer.system.HistorianRecord","$registryType":"Asset","eventsEmitted":[],"transactionId":"fa614b8b-4d68-40c0-b5e7-eb22de640715#1","transactionInvoked":"resource:org.hyperledger.composer.system.IssueIdentity#fa614b8b-4d68-40c0-b5e7-eb22de640715%231","transactionTimestamp":"2017-11-21T18:08:34.744Z","transactionType":"org.hyperledger.composer.system.IssueIdentity"}
2017-11-21 23:09:49.482 UTC [lockbasedtxmgr] Next -> DEBU 109082 queryResultsItr.Next() returned a record:{"$class":"org.hyperledger.composer.system.HistorianRecord","$registryId":"org.hyperledger.composer.system.HistorianRecord","$registryType":"Asset","eventsEmitted":[],"transactionId":"fa614b8b-4d68-40c0-b5e7-eb22de640715#0","transactionInvoked":"resource:org.hyperledger.composer.system.AddParticipant#fa614b8b-4d68-40c0-b5e7-eb22de640715%230","transactionTimestamp":"2017-11-21T18:08:34.743Z","transactionType":"org.hyperledger.composer.system.AddParticipant"}
2017-11-21 23:09:49.482 UTC [chaincode] func1 -> DEBU 109083 Got keys and values. Sending RESPONSE
2017-11-21 23:09:49.482 UTC [chaincode] 1 -> DEBU 109084 [987669f4]handleQueryStateNext serial send RESPONSE
2017-11-21 23:09:49.502 UTC [chaincode] processStream -> DEBU 109085 [987669f4]Received message QUERY_STATE_CLOSE from shim
2017-11-21 23:09:49.502 UTC [chaincode] HandleMessage -> DEBU 109086 [987669f4]Fabric side Handling ChaincodeMessage of type: QUERY_STATE_CLOSE in state ready
2017-11-21 23:09:49.502 UTC [chaincode] afterQueryStateClose -> DEBU 109087 Received QUERY_STATE_CLOSE, invoking query state close from ledger
2017-11-21 23:09:49.502 UTC [chaincode] afterQueryStateClose -> DEBU 109088 Exiting QUERY_STATE_CLOSE
2017-11-21 23:09:49.502 UTC [chaincode] filterError -> DEBU 109089 Ignoring NoTransitionError: no transition
2017-11-21 23:09:49.503 UTC [chaincode] func1 -> DEBU 10908a Closed. Sending RESPONSE
2017-11-21 23:09:49.503 UTC [chaincode] 1 -> DEBU 10908b [987669f4]handleQueryStateClose serial send RESPONSE
2017-11-21 23:09:50.970 UTC [gossip/discovery] periodicalSendAlive -> DEBU 10908c Sleeping 5s
2017-11-21 23:09:50.980 UTC [msp] DeserializeIdentity -> INFO 10908d Obtaining identity
2017-11-21 23:09:54.268 UTC [gossip/discovery] periodicalReconnectToDead -> DEBU 10908e Sleeping 25s
2017-11-21 23:09:55.991 UTC [gossip/discovery] periodicalSendAlive -> DEBU 10908f Sleeping 5s
2017-11-21 23:09:56.031 UTC [msp] DeserializeIdentity -> INFO 109090 Obtaining identity
2017-11-21 23:10:01.152 UTC [gossip/discovery] periodicalSendAlive -> DEBU 109091 Sleeping 5s
2017-11-21 23:10:01.173 UTC [msp] DeserializeIdentity -> INFO 109092 Obtaining identity
2017-11-21 23:10:06.177 UTC [gossip/discovery] periodicalSendAlive -> DEBU 109093 Sleeping 5s
2017-11-21 23:10:06.181 UTC [msp] DeserializeIdentity -> INFO 109094 Obtaining identity
```
### Logs from Playground
```
0|composer | ConnectorServer         :connectionQueryChainCode > 79d38342-a6a6-4906-afc7-361cddedef51, 87f86f50-4f95-4c44-81a2-7156c25d4ace, getRegistry, ["Asset","org.hyperledger.composer.system.Identity"]
0|composer | HLFConnection           :queryChainCode()         > [object Object], getRegistry, ["Asset","org.hyperledger.composer.system.Identity"]
0|composer | HLFConnectionManager    :fabric-client()          [TransactionID.js]: const - start 
0|composer | HLFConnectionManager    :fabric-client()          [TransactionID.js]: const - transaction_id d786b3018dedd41040fa0810f81f1cad4ef236d08f32d8ba8be233221bab3ddd 
0|composer | HLFConnectionManager    :fabric-client()          [Channel.js]: queryByChaincodel - start 
0|composer | HLFConnectionManager    :fabric-client()          [TransactionID.js]: const - start 
0|composer | HLFConnectionManager    :fabric-client()          [TransactionID.js]: const - transaction_id d0c7ad8e782c2a7b232db616fc076d87ac539a6d124ba96c182a8aace8a6d789 
0|composer | HLFConnectionManager    :fabric-client()          [Channel.js]: sendTransactionProposal - start 
0|composer | HLFConnectionManager    :fabric-client()          [Channel.js]: sendTransactionProposal - request does not have targets using this channels endorsing peers 
0|composer | HLFConnectionManager    :fabric-client()          [Channel.js]: getPeers - list size: 1. 
0|composer | HLFConnectionManager    :fabric-client()          [Channel.js]: sendTransactionProposal - adding function arg:getRegistry 
0|composer | HLFConnectionManager    :fabric-client()          [Channel.js]: sendTransactionProposal - adding arg:Asset 
0|composer | HLFConnectionManager    :fabric-client()          [Channel.js]: sendTransactionProposal - adding arg:org.hyperledger.composer.system.Identity 
0|composer | HLFConnectionManager    :fabric-client()          [Channel.js]: sendTransactionProposal - not adding the argument :: argbytes 
0|composer | HLFConnectionManager    :fabric-client()          [client-utils.js]: buildChannelHeader - type 3 channel_id channel1 tx_id NaN epoch % chaincode_id null giveback 
0|composer | HLFConnectionManager    :fabric-client()          [client-utils.js]: buildProposal - not adding a transientMap 
0|composer | HLFConnectionManager    :fabric-client()          [crypto_ecdsa_aes]: ecdsa signature:  Signature {
0|composer |   r: <BN: 22cff5f795a6834edd011a45ee981f5324bbab00cd41421ffa7f30043b0e5278>,
0|composer |   s: <BN: 27e945d4fd88a56757988fbc4544e335e2dc3d09be87affbc16b26ab0f21eef8>,
0|composer |   recoveryParam: 0 } 
0|composer | HLFConnectionManager    :fabric-client()          [Peer.js]: Peer.sendProposal - Start 
0|composer | HLFConnectionManager    :fabric-client()          [Peer.js]: Received proposal response from peer "grpc://blockchain-org1peer1:30110": status - 200 
0|composer | HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is fulfilled: [object Object] 
0|composer | HLFConnectionManager    :fabric-client()          [Channel.js]: queryByChaincode - results received 
0|composer | HLFConnection           :queryChainCode()         Received 1 payloads(s) from querying the composer runtime chaincode [{"type":"Buffer","data":[123,34,116,121,112,101,34,58,34,65,115,115,101,116,34,44,34,105,100,34,58,34,111,114,103,46,104,121,112,101,114,108,101,100,103,101,114,46,99,111,109,112,111,115,101,114,46,115,121,115,116,101,109,46,73,100,101,110,116,105,116,121,34,44,34,110,97,109,101,34,58,34,65,115,115,101,116,32,114,101,103,105,115,116,114,121,32,102,111,114,32,111,114,103,46,104,121,112,101,114,108,101,100,103,101,114,46,99,111,109,112,111,115,101,114,46,115,121,115,116,101,109,46,73,100,101,110,116,105,116,121,34,125]}]
0|composer | HLFConnection           :{"type":"Asset","id":"or < 
0|composer | ConnectorServer         :connectionQueryChainCode < {"type":"Asset","id":"org.hyperledger.composer.system.Identity","name":"Asset registry for org.hyperledger.composer.system.Identity"}
0|composer | ConnectorServer         :connectionQueryChainCode > 79d38342-a6a6-4906-afc7-361cddedef51, 87f86f50-4f95-4c44-81a2-7156c25d4ace, getAllResourcesInRegistry, ["Asset","org.hyperledger.composer.system.Identity"]
0|composer | HLFConnection           :queryChainCode()         > [object Object], getAllResourcesInRegistry, ["Asset","org.hyperledger.composer.system.Identity"]
0|composer | HLFConnectionManager    :fabric-client()          [TransactionID.js]: const - start 
0|composer | HLFConnectionManager    :fabric-client()          [TransactionID.js]: const - transaction_id 50d082fce6b57ffb8e0d44c5f25fa895b79c43a8ac5486902ed3b9c1828f18be 
0|composer | HLFConnectionManager    :fabric-client()          [Channel.js]: queryByChaincodel - start 
0|composer | HLFConnectionManager    :fabric-client()          [TransactionID.js]: const - start 
0|composer | HLFConnectionManager    :fabric-client()          [TransactionID.js]: const - transaction_id 2a1f931f9023769ae06756d3d0951e9cdbbe7f23ca7b50acb3611008db6bc7df 
0|composer | HLFConnectionManager    :fabric-client()          [Channel.js]: sendTransactionProposal - start 
0|composer | HLFConnectionManager    :fabric-client()          [Channel.js]: sendTransactionProposal - request does not have targets using this channels endorsing peers 
0|composer | HLFConnectionManager    :fabric-client()          [Channel.js]: getPeers - list size: 1. 
0|composer | HLFConnectionManager    :fabric-client()          [Channel.js]: sendTransactionProposal - adding function arg:getAllResourcesInRegistry 
0|composer | HLFConnectionManager    :fabric-client()          [Channel.js]: sendTransactionProposal - adding arg:Asset 
0|composer | HLFConnectionManager    :fabric-client()          [Channel.js]: sendTransactionProposal - adding arg:org.hyperledger.composer.system.Identity 
0|composer | HLFConnectionManager    :fabric-client()          [Channel.js]: sendTransactionProposal - not adding the argument :: argbytes 
0|composer | HLFConnectionManager    :fabric-client()          [client-utils.js]: buildChannelHeader - type 3 channel_id channel1 tx_id NaN epoch % chaincode_id null giveback 
0|composer | HLFConnectionManager    :fabric-client()          [client-utils.js]: buildProposal - not adding a transientMap 
0|composer | HLFConnectionManager    :fabric-client()          [crypto_ecdsa_aes]: ecdsa signature:  Signature {
0|composer |   r: <BN: af40351d29f0ac3e448036ed23b525c879d416f247b021dad34abcd2cb3eb812>,
0|composer |   s: <BN: 6027238a23719d98fb1208c952d6ad6184f5fdfad9abc9b4c210d466f894754c>,
0|composer |   recoveryParam: 0 } 
0|composer | HLFConnectionManager    :fabric-client()          [Peer.js]: Peer.sendProposal - Start 
0|composer | HLFConnectionManager    :fabric-client()          [Peer.js]: Received proposal response from peer "grpc://blockchain-org1peer1:30110": status - 200 
0|composer | HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is fulfilled: [object Object] 
0|composer | HLFConnectionManager    :fabric-client()          [Channel.js]: queryByChaincode - results received 
0|composer | HLFConnection           :queryChainCode()         Received 1 payloads(s) from querying the composer runtime chaincode [{"type":"Buffer","data":[91,123,34,36,99,108,97,115,115,34,58,34,111,114,103,46,104,121,112,101,114,108,101,100,103,101,114,46,99,111,109,112,111,115,101,114,46,115,121,115,116,101,109,46,73,100,101,110,116,105,116,121,34,44,34,105,100,101,110,116,105,116,121,73,100,34,58,34,50,53,52,50,54,48,56,54,53,50,102,51,98,49,51,51,101,57,49,55,102,97,50,99,102,99,100,98,99,49,97,48,51,102,49,99,99,54,98,102,98,52,97,50,55,55,54,99,100,57,50,57,55,98,55,99,102,99,102,57,49,55,52,97,34,44,34,110,97,109,101,34,58,34,100,101,118,83,108,97,99,107,34,44,34,105,115,115,117,101,114,34,58,34,50,55,99,53,56,50,100,54,55,52,100,100,102,48,102,50,51,48,56,53,52,56,49,52,98,55,99,102,100,48,52,53,53,51,102,51,100,48,101,97,99,53,53,101,51,55,100,57,49,53,51,56,54,99,54,49,52,97,53,97,49,100,101,57,34,44,34,99,1
```
### Logs from CouchDB
```
[WARN  tini (5)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
****************************************************
WARNING: CouchDB is running in Admin Party mode.
         This will allow anyone with access to the
         CouchDB port to access your database. In
         Docker's default configuration, this is
         effectively any other container on the same
         system.
         Use "-e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password"
         to set it in "docker run".
****************************************************
[os_mon] cpu supervisor port (cpu_sup): Error writing to Erlang
```
I am not sure what other logs to include, not really sure where to find memory usages on Kubernetes.

**Comment by davidkel** [comment]
@ykcai could you try this against the composer dev server in a local environment rather than within k8s. That way you would be able to use docker commands to monitor the memory usage of the chaincode container. I think one of the problems you might be seeing is a known memory leak within the chaincode container.

**Comment by ykcai** [comment]
I ran this locally using Docker and the fabric-tools for setting my local fabric. When I performed around 1500 transactions I saw that the chaincode container was using about 80% memory capacity. 
<img width="781" alt="screen shot 2017-11-22 at 3 55 51 pm" src="https://user-images.githubusercontent.com/8824230/33151120-9ca9e990-cfa4-11e7-8e8e-541c25d4ee30.png">

Afterwards, I did several queries to the `/api/system/historian` endpoint to which I got the error 
```
{"error":{"statusCode":500,"name":"Error","message":"Error trying to query business network. Error: Error executing chaincode: Failed to execute transaction (Timeout expired while executing transaction)","stack":"Error: Error trying to query business network. Error: Error executing chaincode: Failed to execute transaction (Timeout expired while executing transaction)\n    at channel.queryByChaincode.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:765:34)\n    at <anonymous>"}}
``` 
and my chaincode container crashed sometime during the query to the Historian.

**Comment by ykcai** [comment]
I guess a very bad temporary work around is to expose the CouchDB and make my queries directly without going through Composer APIs. This seems to do the trick and I can avoid crashing my chaincode container.

**Comment by davidkel** [comment]
@ykcai Please could you try 0.15.2 work has been done to improve performance and address some memory leaks which could resolve your issues.

**Comment by sstone1** [comment]
No response to last question, closing.

**Comment by LuisBrime** [comment]
I also get this issue, is there any way to fix it? I cannot keep working with the historian through the REST Server because of this.

**Comment by alexvicegrab** [comment]
I'm also seeing this issue still. When querying records with only ~300 transactions I start seeing:

```
timeout expired while executing transaction
```

**Comment by futurama92** [comment]
I also having this trouble, with 50 transaction in 1.30 minutes. I don't know if i'm using low resources, but this seems very strange.
