### ISSUE TITLE
Deploying a persistent and secured REST server using Docker not working...

### ISSUE THREAD

**Issue by simonmullaney** [hyperledger/composer#3002]
Hello,

I'm trying to deploy a persistent and secured REST server using Docker as described in this tutorial -> https://hyperledger.github.io/composer/integrating/deploying-the-rest-server.html

but when I run `docker logs -f rest` I get the following result:

```
0|composer | WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
0|composer | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
0|composer | Discovering types from business network definition ...
0|composer | Connection fails: Error: Error trying to ping. Error: Error trying to query business network. Error: REQUEST_TIMEOUT
0|composer | It will be retried for the next request.
0|composer | Exception: Error: Error trying to ping. Error: Error trying to query business network. Error: REQUEST_TIMEOUT
0|composer | Error: Error trying to ping. Error: Error trying to query business network. Error: REQUEST_TIMEOUT
0|composer |     at _checkRuntimeVersions.then.catch (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:713:34)
0|composer |     at <anonymous>
0|composer |     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
PM2        | App [composer-rest-server] with id [0] and pid [17], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:composer-rest-server id:0
PM2        | App name:composer-rest-server id:0 online
0|composer | WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
0|composer | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
0|composer | Discovering types from business network definition ...
 
```
## Context

I have tried cleaning up all my docker containers and images, stopping the fabric, downloading a new fabric and starting the new fabric but it still comes up with the same error..

## Expected Behavior

The command `docker logs -f rest` should finish with `Browse your REST API at http://localhost:3000/explorer`

## Actual Behavior

Get the error as detailed above

## Possible Fix

I tried changing the permissions of  ~/.composer by using the command below but it didn't change the output: `chmod -R 777 ~/.composer`

## Context

My docker containers:

```
c862a54a50f3        myorg/my-composer-rest-server                                                                                               "pm2-docker compos..."   15 minutes ago      Up 15 minutes       0.0.0.0:3000->3000/tcp                           rest
c8bc1d5f01aa        mongo                                                                                                                       "docker-entrypoint..."   17 minutes ago      Up 18 minutes       0.0.0.0:27017->27017/tcp                         mongo
61bd6dd36353        dev-peer0.org1.example.com-block-aviation-network-0.16.2-a03bf114976a6a5a4186c9afaa5f7a38ccfc6320fc4a1cc0c5a728fa803d3fcb   "chaincode -peer.a..."   21 minutes ago      Up 22 minutes                                                        dev-peer0.org1.example.com-block-aviation-network-0.16.2
785560648a61        hyperledger/fabric-peer:x86_64-1.0.4                                                                                        "peer node start -..."   24 minutes ago      Up 24 minutes       0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp   peer0.org1.example.com
ab1a0b8a4583        hyperledger/fabric-ca:x86_64-1.0.4                                                                                          "sh -c 'fabric-ca-..."   24 minutes ago      Up 24 minutes       0.0.0.0:7054->7054/tcp                           ca.org1.example.com
d734cabae60e        hyperledger/fabric-orderer:x86_64-1.0.4                                                                                     "orderer"                24 minutes ago      Up 24 minutes       0.0.0.0:7050->7050/tcp                           orderer.example.com
7a8791879f80        hyperledger/fabric-couchdb:x86_64-1.0.4                                                                                     "tini -- /docker-e..."   24 minutes ago      Up 24 minutes       4369/tcp, 9100/tcp, 0.0.0.0:5984->5984/tcp       couchdb

```

Docker logs for mongo container:
```
docker logs mongo
2017-12-14T10:07:09.663+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=c8bc1d5f01aa
2017-12-14T10:07:09.663+0000 I CONTROL  [initandlisten] db version v3.6.0
2017-12-14T10:07:09.664+0000 I CONTROL  [initandlisten] git version: a57d8e71e6998a2d0afde7edc11bd23e5661c915
2017-12-14T10:07:09.664+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
2017-12-14T10:07:09.664+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2017-12-14T10:07:09.664+0000 I CONTROL  [initandlisten] modules: none
2017-12-14T10:07:09.664+0000 I CONTROL  [initandlisten] build environment:
2017-12-14T10:07:09.664+0000 I CONTROL  [initandlisten]     distmod: debian81
2017-12-14T10:07:09.664+0000 I CONTROL  [initandlisten]     distarch: x86_64
2017-12-14T10:07:09.664+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2017-12-14T10:07:09.664+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
2017-12-14T10:07:09.665+0000 I STORAGE  [initandlisten] 
2017-12-14T10:07:09.665+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2017-12-14T10:07:09.665+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2017-12-14T10:07:09.665+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=487M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2017-12-14T10:07:09.772+0000 I CONTROL  [initandlisten] 
2017-12-14T10:07:09.772+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-12-14T10:07:09.772+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-12-14T10:07:09.772+0000 I CONTROL  [initandlisten] 
2017-12-14T10:07:09.784+0000 I STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: ee57dc97-c72f-4c85-ad63-e08bfd93f10e
2017-12-14T10:07:09.810+0000 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 3.6
2017-12-14T10:07:09.816+0000 I STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: 280cbcb1-b61c-42d0-8731-95ce0b2acf62
2017-12-14T10:07:09.911+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2017-12-14T10:07:09.918+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
2017-12-14T10:10:11.225+0000 I NETWORK  [listener] connection accepted from 172.18.0.8:53360 #1 (1 connection now open)
2017-12-14T10:10:11.269+0000 I NETWORK  [conn1] received client metadata from 172.18.0.8:53360 conn: { driver: { name: "nodejs", version: "2.2.33" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.49-moby" }, platform: "Node.js v8.9.3, LE, mongodb-core: 2.1.17" }
2017-12-14T10:12:09.943+0000 I STORAGE  [thread2] createCollection: config.system.sessions with generated UUID: 2d90be65-5b28-438f-84be-9956ad43ddba
2017-12-14T10:12:09.991+0000 I INDEX    [thread2] build index on: config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 }
2017-12-14T10:12:09.991+0000 I INDEX    [thread2] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2017-12-14T10:12:09.994+0000 I INDEX    [thread2] build index done.  scanned 0 total records. 0 secs
2017-12-14T10:15:14.369+0000 I NETWORK  [conn1] end connection 172.18.0.8:53360 (0 connections now open)
2017-12-14T10:15:19.376+0000 I NETWORK  [listener] connection accepted from 172.18.0.8:53366 #2 (1 connection now open)
2017-12-14T10:15:19.389+0000 I NETWORK  [conn2] received client metadata from 172.18.0.8:53366 conn: { driver: { name: "nodejs", version: "2.2.33" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.49-moby" }, platform: "Node.js v8.9.3, LE, mongodb-core: 2.1.17" }
2017-12-14T10:20:21.213+0000 I NETWORK  [conn2] end connection 172.18.0.8:53366 (0 connections now open)
2017-12-14T10:20:24.417+0000 I NETWORK  [listener] connection accepted from 172.18.0.8:53372 #3 (1 connection now open)
2017-12-14T10:20:24.517+0000 I NETWORK  [conn3] received client metadata from 172.18.0.8:53372 conn: { driver: { name: "nodejs", version: "2.2.33" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.49-moby" }, platform: "Node.js v8.9.3, LE, mongodb-core: 2.1.17" }
2017-12-14T10:25:25.483+0000 I NETWORK  [conn3] end connection 172.18.0.8:53372 (0 connections now open)
2017-12-14T10:25:29.237+0000 I NETWORK  [listener] connection accepted from 172.18.0.8:53378 #4 (1 connection now open)
2017-12-14T10:25:29.248+0000 I NETWORK  [conn4] received client metadata from 172.18.0.8:53378 conn: { driver: { name: "nodejs", version: "2.2.33" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.49-moby" }, platform: "Node.js v8.9.3, LE, mongodb-core: 2.1.17" }
2017-12-14T10:30:30.452+0000 I NETWORK  [conn4] end connection 172.18.0.8:53378 (0 connections now open)
2017-12-14T10:30:36.807+0000 I NETWORK  [listener] connection accepted from 172.18.0.8:53384 #5 (1 connection now open)
2017-12-14T10:30:36.823+0000 I NETWORK  [conn5] received client metadata from 172.18.0.8:53384 conn: { driver: { name: "nodejs", version: "2.2.33" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.49-moby" }, platform: "Node.js v8.9.3, LE, mongodb-core: 2.1.17" }
2017-12-14T10:35:38.424+0000 I NETWORK  [conn5] end connection 172.18.0.8:53384 (0 connections now open)
2017-12-14T10:35:41.846+0000 I NETWORK  [listener] connection accepted from 172.18.0.8:53390 #6 (1 connection now open)
2017-12-14T10:35:41.856+0000 I NETWORK  [conn6] received client metadata from 172.18.0.8:53390 conn: { driver: { name: "nodejs", version: "2.2.33" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.49-moby" }, platform: "Node.js v8.9.3, LE, mongodb-core: 2.1.17" }
```
## Your Environment

Composer version: v0.16.2
Node: v8.9.3

**Comment by rthatcher** [comment]
This likely the known problem where the Business Network Cards are created with `localhost` as the address for all the Fabric servers.  When the REST server is started in a container the REST server resolves localhost as an address inside the container and can't connect to the Fabric.
The short term solution is to edit the connection.json file for the Card to replace localhost with the Host address of the machine running the Docker Containers.
See #2898 and #2908

**Comment by simonmullaney** [comment]
Thanks for your reply @rthatcher.

I edited the connection.json file for the card and replaced local host with the host address of the machine running the docker containers, but I'm still getting an error...

I just want to go over what I did to make sure I did it correctly...

My docker containers:

```
Simons-MacBook-Pro:~ simonmullaney$ docker ps
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS              PORTS                                            NAMES
c862a54a50f3        myorg/my-composer-rest-server             "pm2-docker compos..."   2 weeks ago         Up 2 hours          0.0.0.0:3000->3000/tcp                           rest
c8bc1d5f01aa        mongo                                     "docker-entrypoint..."   2 weeks ago         Up 2 hours          0.0.0.0:27017->27017/tcp                         mongo
785560648a61        hyperledger/fabric-peer:x86_64-1.0.4      "peer node start -..."   2 weeks ago         Up 2 hours          0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp   peer0.org1.example.com
ab1a0b8a4583        hyperledger/fabric-ca:x86_64-1.0.4        "sh -c 'fabric-ca-..."   2 weeks ago         Up 2 hours          0.0.0.0:7054->7054/tcp                           ca.org1.example.com
d734cabae60e        hyperledger/fabric-orderer:x86_64-1.0.4   "orderer"                2 weeks ago         Up 2 hours          0.0.0.0:7050->7050/tcp                           orderer.example.com
7a8791879f80        hyperledger/fabric-couchdb:x86_64-1.0.4   "tini -- /docker-e..."   2 weeks ago         Up 2 hours          4369/tcp, 9100/tcp, 0.0.0.0:5984->5984/tcp       couchdb
```

I then got the host address of all my containers shown above:

```
Simons-MacBook-Pro:~ simonmullaney$ docker inspect c862a54a50f3 | awk '/IPAddress/ || /HostPort/'
                        "HostPort": "3000"
                        "HostPort": "3000"
            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "172.18.0.3",
Simons-MacBook-Pro:~ simonmullaney$ docker inspect c8bc1d5f01aa | awk '/IPAddress/ || /HostPort/'
                        "HostPort": "27017"
                        "HostPort": "27017"
            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "172.18.0.4",
Simons-MacBook-Pro:~ simonmullaney$ docker inspect 785560648a61 | awk '/IPAddress/ || /HostPort/'
                        "HostPort": "7051"
                        "HostPort": "7053"
                        "HostPort": "7051"
                        "HostPort": "7053"
            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "172.18.0.2",
Simons-MacBook-Pro:~ simonmullaney$ docker inspect ab1a0b8a4583 | awk '/IPAddress/ || /HostPort/'
                        "HostPort": "7054"
                        "HostPort": "7054"
            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "172.18.0.5",
Simons-MacBook-Pro:~ simonmullaney$ docker inspect d734cabae60e | awk '/IPAddress/ || /HostPort/'
                        "HostPort": "7050"
                        "HostPort": "7050"
            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "172.18.0.6",
Simons-MacBook-Pro:~ simonmullaney$ docker inspect 7a8791879f80 | awk '/IPAddress/ || /HostPort/'
                        "HostPort": "5984"
                        "HostPort": "5984"
            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "172.18.0.7",
```

I then made changes to the following files replacing 'localhost' with the respective ip address that I got from above.

connection.json -> /Users/simonmullaney/.composer/cards/admin@block-aviation-network/connection.json 

```
Simons-MacBook-Pro:admin@block-aviation-network simonmullaney$ pwd
/Users/simonmullaney/.composer/cards/admin@block-aviation-network
Simons-MacBook-Pro:admin@block-aviation-network simonmullaney$ cat connection.json 
{"name":"hlfv1","type":"hlfv1","orderers":[{"url":"grpc://172.18.0.6:7050"}],"ca":{"url":"http://172.18.0.5:7054","name":"ca.org1.example.com"},"peers":[{"requestURL":"grpc://172.18.0.2:7051","eventURL":"grpc://172.18.0.2:7053"}],"channel":"composerchannel","mspID":"Org1MSP","timeout":300}
```

connection.json -> /Users/simonmullaney/.composer-connection-profiles/hlfv1/connection.json

```
Simons-MacBook-Pro:hlfv1 simonmullaney$ pwd
/Users/simonmullaney/.composer-connection-profiles/hlfv1
Simons-MacBook-Pro:hlfv1 simonmullaney$ cat connection.json 
{
    "type": "hlfv1",
    "orderers": [
       { "url" : "grpc://172.18.0.6:7050" }
    ],
    "ca": { "url": "http://172.18.0.5:7054",
            "name": "ca.org1.example.com"
    },
    "peers": [
        {
            "requestURL": "grpc://172.18.0.2:7051",
            "eventURL": "grpc://172.18.0.2:7053"
        }
    ],
    "keyValStore": "/Users/simonmullaney/.composer-credentials",
    "channel": "composerchannel",
    "mspID": "Org1MSP",
    "timeout": "300"
}
```

However, then if I run `npm start` in my angular app directory I get an error `Error: Error trying to ping. Error: Error trying to query business network. Error: Connect Failed` and the following output:

```
Simons-MacBook-Pro:block-aviation-angular simonmullaney$ npm start

> block-aviation-angular@0.0.1 start /Users/simonmullaney/block-aviation_angular/block-aviation-angular
> concurrently "ng serve --host 0.0.0.0" "npm run app"

[1] 
[1] > block-aviation-angular@0.0.1 app /Users/simonmullaney/block-aviation_angular/block-aviation-angular
[1] > composer-rest-server --card admin@block-aviation-network -a true -m true -n never -p 3000 -t true -e /Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/composer-rest-server/cert.pem -k /Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/composer-rest-server/key.pem
[1] 
[1] Discovering types from business network definition ...
[0] ** NG Live Development Server is running on http://0.0.0.0:4200 **
[0] Hash: fa16db08053dedf1c3f4                                                               
[0] Time: 15379ms
[0] chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 265 kB {5} [initial] [rendered]
[0] chunk    {1} main.bundle.js, main.bundle.js.map (main) 67.8 kB {4} [initial] [rendered]
[0] chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 184 kB {5} [initial] [rendered]
[0] chunk    {3} scripts.bundle.js, scripts.bundle.js.map (scripts) 435 kB {5} [initial] [rendered]
[0] chunk    {4} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.83 MB [initial] [rendered]
[0] chunk    {5} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
[0] webpack: Compiled successfully.
[1] Connection fails: Error: Error trying to ping. Error: Error trying to query business network. Error: Connect Failed
[1] It will be retried for the next request.
[1] Exception: Error: Error trying to ping. Error: Error trying to query business network. Error: Connect Failed
[1] Error: Error trying to ping. Error: Error trying to query business network. Error: Connect Failed
[1]     at _checkRuntimeVersions.then.catch (/Users/simonmullaney/block-aviation_angular/block-aviation-angular/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:713:34)
[1]     at <anonymous>
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! block-aviation-angular@0.0.1 app: `composer-rest-server --card admin@block-aviation-network -a true -m true -n never -p 3000 -t true -e /Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/composer-rest-server/cert.pem -k /Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/composer-rest-server/key.pem`
[1] npm ERR! Exit status 1
[1] npm ERR! 
npm ERR! Failed at the block-aviation-angular@0.0.1 app script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1] 
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /Users/simonmullaney/.npm/_logs/2018-01-01T13_00_46_936Z-debug.log
[1] npm run app exited with code 1
```

The logs show the following:

```
Simons-MacBook-Pro:block-aviation-angular simonmullaney$ vi /Users/simonmullaney/.npm/_logs/2018-01-01T13_00_46_936Z-debug.log

1 verbose cli   'run',
1 verbose cli   'app' ]
2 info using npm@5.6.0
3 info using node@v8.9.3
4 verbose run-script [ 'preapp', 'app', 'postapp' ]
5 info lifecycle block-aviation-angular@0.0.1~preapp: block-aviation-angular@0.0.1
6 info lifecycle block-aviation-angular@0.0.1~app: block-aviation-angular@0.0.1
7 verbose lifecycle block-aviation-angular@0.0.1~app: unsafe-perm in lifecycle true
8 verbose lifecycle block-aviation-angular@0.0.1~app: PATH: /Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/simonmullaney/block-aviation_angular/block-aviation-angular/node_modules/.bin:/Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/simonmullaney/block-aviation_angular/block-aviation-angular/node_modules/.bin:/Users/simonmullaney/.nvm/versions/node/v8.9.3/bin:/Users/simonmullaney/.cargo/bin:/opt/local/bin:/opt/local/sbin:/Users/simonmullaney/Desktop/Hyperledger/fabric-samples/bin:/Users/simonmullaney/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/go/bin:/usr/local/go/bin
9 verbose lifecycle block-aviation-angular@0.0.1~app: CWD: /Users/simonmullaney/block-aviation_angular/block-aviation-angular
10 silly lifecycle block-aviation-angular@0.0.1~app: Args: [ '-c',
10 silly lifecycle   'composer-rest-server --card admin@block-aviation-network -a true -m true -n never -p 3000 -t true -e /Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/composer-rest-server/cert.pem -k /Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/composer-rest-server/key.pem' ]
11 silly lifecycle block-aviation-angular@0.0.1~app: Returned: code: 1  signal: null
12 info lifecycle block-aviation-angular@0.0.1~app: Failed to exec app script
13 verbose stack Error: block-aviation-angular@0.0.1 app: `composer-rest-server --card admin@block-aviation-network -a true -m true -n never -p 3000 -t true -e /Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/composer-rest-server/cert.pem -k /Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/composer-rest-server/key.pem`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid block-aviation-angular@0.0.1
15 verbose cwd /Users/simonmullaney/block-aviation_angular/block-aviation-angular
16 verbose Darwin 17.2.0
17 verbose argv "/Users/simonmullaney/.nvm/versions/node/v8.9.3/bin/node" "/Users/simonmullaney/.nvm/versions/node/v8.9.3/bin/npm" "run" "app"
18 verbose node v8.9.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error block-aviation-angular@0.0.1 app: `composer-rest-server --card admin@block-aviation-network -a true -m true -n never -p 3000 -t true -e /Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/composer-rest-server/cert.pem -k /Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/composer-rest-server/key.pem`
22 error Exit status 1
23 error Failed at the block-aviation-angular@0.0.1 app script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by simonmullaney** [comment]
Got it sorted changed IP addresses to 0.0.0.0 instead of the Ip addresses of the individual docker containers.

**Comment by nikosheng** [comment]
May I know that how to change the IP address to 0.0.0.0?

**Comment by nikosheng** [comment]
@simonmullaney May I know that how to change the IP address to 0.0.0.0? I encountered the same issue as you mentioned above. Thanks in advance.

**Comment by simonmullaney** [comment]
@nikosheng I changed it from localhost to 0.0.0.0 in the connection.json file which is located in .composer directory from your home directory

**Comment by nikosheng** [comment]
@simonmullaney Thank you so much for your reply.  And the modification will be applied to PeerAdmin card?

**Comment by simonmullaney** [comment]
no worries, Yeah PeerAdmin card

**Comment by nikosheng** [comment]
@simonmullaney sorry to bother you again. As I still encountered another issue about REQUEST_TIMEOUT.
`[2018-03-07 02:28:12] PM2 log: Launching in no daemon mode
[2018-03-07 02:28:12] PM2 log: Starting execution sequence in -fork mode- for app name:composer-rest-server id:0
[2018-03-07 02:28:12] PM2 log: App name:composer-rest-server id:0 online
WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
Discovering types from business network definition ...
Connection fails: Error: Error trying to ping. Error: Error trying to query business network. Error: REQUEST_TIMEOUT
It will be retried for the next request.
Error: Error trying to ping. Error: Error trying to query business network. Error: REQUEST_TIMEOUT
    at _checkRuntimeVersions.then.catch (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:713:34)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
`
Is that something wrong of my settings? I have already replace localhost with 0.0.0.0 in PeerAdmin connection.json.

**Comment by nikosheng** [comment]
@simonmullaney I am able to connect without mongodb integration. Is there any configuration which is not mentioned in the tutorial for the mongo

**Comment by nikosheng** [comment]
@simonmullaney I solved the problem.  The connection.json file belongs to the deployed chaincode needs to be modified to your IP address as well

**Comment by nikosheng** [comment]
@simonmullaney Do you know how to solve the authorization issue as I have already set up the OAuth App in github and fill in the client id and secret, but I still cannot navigate to /auth/github to authorize the rest request

**Comment by nikosheng** [comment]
Finally fix the issue by install passport-github2 instead of passport-github, and remember to clear the browser cache

**Comment by sun337** [comment]
> I solved the problem. The connection.json file belongs to the deployed chaincode needs to be modified to your IP address as well
@nikosheng  what do you mean by that? I am facing the same issue, even after changing to 0.0.0.0

**Comment by nikosheng** [comment]
@sun337 you have to npm install passport-github2 instead of passport-github

**Comment by Worst-dilemma** [comment]
>  I solved the problem. The connection.json file belongs to the deployed chaincode needs to be modified to your IP address as well

Where to modify the IP address?

**Comment by wellstyler** [comment]
@Worst-dilemma If you're using the .createPeerAdminCard script and v1.1, then you'll want to use your machine IP in that script instead of ${HOST}, as ${HOST} is using localhost.

Should be in /fabric-scripts/hlfv11/createPeerAdminCard

**Comment by wellstyler** [comment]
@sweetalidinesh I'm not sure. If you can share your connection.json here, I'll look at it.

**Comment by ivangsp** [comment]
> Got it sorted changed IP addresses to 0.0.0.0 instead of the Ip addresses of the individual docker containers.

Hello @simonmullaney , 

Am facing a similar problem I tried recreating the cards using the  ip address to 0.0.0.0  as you recommended but the error still persists. Here is my  connection profile. I also tried following the the instruction given from this [tutorial ](https://hyperledger.github.io/composer/latest/tutorials/google_oauth2_rest)

```
{
    "name": "byfn-network",
    "x-type": "hlfv1",
    "version": "1.0.0",
    "channels": {
        "mychannel": {
            "orderers": [
                "orderer.trade.com"
            ],
            "peers": {
                "peer0.exporterorg.trade.com": {
                    "endorsingPeer": true,
                    "chaincodeQuery": true,
                    "eventSource": true
                },
                "peer0.importerorg.trade.com": {
                    "endorsingPeer": true,
                    "chaincodeQuery": true,
                    "eventSource": true
                },
                "peer0.carrierorg.trade.com": {
                    "endorsingPeer": true,
                    "chaincodeQuery": true,
                    "eventSource": true
                },
                "peer0.regulatororg.trade.com": {
                    "endorsingPeer": true,
                    "chaincodeQuery": true,
                    "eventSource": true
                },
                "peer0.bankorg.trade.com": {
                    "endorsingPeer": true,
                    "chaincodeQuery": true,
                    "eventSource": true
                }
            }
        }
    },
    "organizations": {
        "exporterorg": {
            "mspid": "ExporterOrgMSP",
            "peers": [
                "peer0.exporterorg.trade.com"
            ],
            "certificateAuthorities": [
                "ca.exporterorg.trade.com"
            ]
        },
        "importerorg": {
            "mspid": "ImporterOrgMSP",
            "peers": [
                "peer0.importerorg.trade.com"
            ],
            "certificateAuthorities": [
                "ca.importerorg.trade.com"
            ]
        },
        "bankorg": {
            "mspid": "BankOrgMSP",
            "peers": [
                "peer0.bankorg.trade.com"
            ],
            "certificateAuthorities": [
                "ca.bankorg.trade.com"
            ]
        },
        "regulatororg": {
            "mspid": "RegulatorOrgMSP",
            "peers": [
                "peer0.regulatororg.trade.com"            
            ],
            "certificateAuthorities": [
                "ca.regulatororg.trade.com"
            ]
        },
        "carrierorg": {
            "mspid": "CarrierOrgMSP",
            "peers": [
                "peer0.carrierorg.trade.com"  
            ],
            "certificateAuthorities": [
                "ca.carrierorg.trade.com"
            ]
        }
    },
    "orderers": {
        "orderer.trade.com": {
            "url": "grpcs://0.0.0.0:7050",
            "grpcOptions": {
                "ssl-target-name-override": "orderer.trade.com"
            },
            "tlsCACerts": {
                "pem": "-----BEGIN CERTIFICATE---------END CERTIFICATE-----\n"
            }
        }
    },
    "peers": {
        "peer0.exporterorg.trade.com": {
            "url": "grpcs://0.0.0.0:7051",
            "grpcOptions": {
                "ssl-target-name-override": "peer0.exporterorg.trade.com"
            },
            "tlsCACerts": {
                "pem":"-----BEGIN CERTIFICATE---------END CERTIFICATE-----\n"
            }        },
        "peer0.importerorg.trade.com": {
            "url": "grpcs://0.0.0.0:8051",
            "grpcOptions": {
                "ssl-target-name-override": "peer0.importerorg.trade.com"
            },
            "tlsCACerts": {
                "pem": "-----BEGIN CERTIFICATE----------END CERTIFICATE-----\n"
            }
        },
        "peer0.carrierorg.trade.com": {
            "url": "grpcs://0.0.0.0:9051",
            "grpcOptions": {
                "ssl-target-name-override": "peer0.carrierorg.trade.com"
            },
            "tlsCACerts": {
                "pem": "-----BEGIN CERTIFICATE---------END CERTIFICATE-----\n"
            }
        },
        "peer0.regulatororg.trade.com": {
            "url": "grpcs://0.0.0.0:10051",
            "grpcOptions": {
                "ssl-target-name-override": "peer0.regulatororg.trade.com"
            },
            "tlsCACerts": {
                "pem": "-----END CERTIFICATE-----\n"
            }
        },
        "peer0.bankorg.trade.com": {
            "url": "grpcs://0.0.0.0:11051",
            "grpcOptions": {
                "ssl-target-name-override": "peer0.bankorg.trade.com"
            },
            "tlsCACerts": {
                "pem": "-----BEGIN CERTIFICATE----------END CERTIFICATE-----\n"
            }
        }
    },
    "certificateAuthorities": {
        "ca.exporterorg.trade.com": {
            "url": "https://0.0.0.0:7054",
            "caName": "ca-exporterorg",
            "httpOptions": {
                "verify": false
            }
        },
        "ca.importerorg.trade.com": {
            "url": "https://0.0.0.0:8054",
            "caName": "ca-importerorg",
            "httpOptions": {
                "verify": false
            }
        },
        "ca.carrierorg.trade.com": {
            "url": "https://0.0.0.0:9054",
            "caName": "ca-carrierorg",
            "httpOptions": {
                "verify": false
            }
        },
        "ca.regulatororg.trade.com": {
            "url": "https://0.0.0.0:10054",
            "caName": "ca-regulatororg",
            "httpOptions": {
                "verify": false
            }
        },
        "ca.bankorg.trade.com": {
            "url": "https://0.0.0.0:11054",
            "caName": "ca-bankorg",
            "httpOptions": {
                "verify": false
            }
        }
    }
}
```

thanks you
