### ISSUE TITLE
How to register identities for composer V0.16.2

### ISSUE THREAD

**Issue by simonmullaney** [hyperledger/composer#3094]
I'm just having a problem finding a resource to explain how to register identities to a network. I have an angular web app interacting with the composer rest server but when ever I try to interact with any of the assets I get the following error:

```
Unhandled error for request GET /api/Contract: Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered: admin)
```

I've seen answers like #2585 but that was for an older version of composer and I think it may have changed since then.

## Your Environment
composer - v0.16.2
node - v8.9.3

**Comment by sstone1** [comment]
@simonmullaney can you provide details on how you are running the Composer REST server? Did you deploy it on another machine to the one that you deployed the business network on? Are you using the Composer REST server installed via npm or from Docker image?

This error message usually means that the `admin` identity has been enrolled twice, resulting in two completely different certificates. The first one will be recognised by the business network, but the second one is not recognised, resulting in the error message.

If you are using the Docker image, there is some guidance here around making sure you use a business network card with enrolled certificates in to avoid this problem:
https://hyperledger.github.io/composer/integrating/deploying-the-rest-server.html

**Comment by simonmullaney** [comment]
Thanks for your reply @sstone1.

I tried deploying the rest server as in the document above but I was having issues with it. when I ran:

`docker logs -f rest` 

I got the following output:

```
0|composer | WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
0|composer | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
0|composer | Discovering types from business network definition ...
0|composer | Connection fails: Error: Error trying to ping. Error: Error trying to query business network. Error: Connect Failed
0|composer | It will be retried for the next request.
0|composer | Exception: Error: Error trying to ping. Error: Error trying to query business network. Error: Connect Failed
0|composer | Error: Error trying to ping. Error: Error trying to query business network. Error: Connect Failed
0|composer |     at _checkRuntimeVersions.then.catch (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:713:34)
0|composer |     at <anonymous>
PM2        | App [composer-rest-server] with id [0] and pid [17], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:composer-rest-server id:0
PM2        | App name:composer-rest-server id:0 online
0|composer | WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
0|composer | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
0|composer | Discovering types from business network definition ...
0|composer | Connection fails: Error: Error trying to ping. Error: Error trying to query business network. Error: Connect Failed
0|composer | It will be retried for the next request.
0|composer | Exception: Error: Error trying to ping. Error: Error trying to query business network. Error: Connect Failed
0|composer | Error: Error trying to ping. Error: Error trying to query business network. Error: Connect Failed
0|composer |     at _checkRuntimeVersions.then.catch (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:713:34)
```

I suspect this has something to do with the connection.json file ? I edited mine by changing 'localhost' to 0.0.0.0:

connection.json -> /Users/simonmullaney/.composer-connection-profiles/hlfv1/connection.json

```
{
    "type": "hlfv1",
    "orderers": [
       { "url" : "grpc://0.0.0.0:7050" }
    ],
    "ca": { "url": "http://0.0.0.0:7054",
            "name": "ca.org1.example.com"
    },
    "peers": [
        {
            "requestURL": "grpc://0.0.0.0:7051",
            "eventURL": "grpc://0.0.0.0:7053"
        }
    ],
    "keyValStore": "/Users/simonmullaney/.composer-credentials",
    "channel": "composerchannel",
    "mspID": "Org1MSP",
    "timeout": "300"
}
```
connection.json -> /Users/simonmullaney/.composer/cards/admin@block-aviation-network/connection.json

```
{"name":"hlfv1","type":"hlfv1","orderers":[{"url":"grpc://0.0.0.0:7050"}],"ca":{"url":"http://0.0.0.0:7054","name":"ca.org1.example.com"},"peers":[{"requestURL":"grpc://0.0.0.0:7051","eventURL":"grpc://0.0.0.0:7053"}],"channel":"composerchannel","mspID":"Org1MSP","timeout":300}

```

The envars.txt file I used was:

```
COMPOSER_CARD=admin@block-aviation-network
COMPOSER_TLS=true
COMPOSER_TLS_CERTIFICATE=/Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/composer-rest-server/cert.pem
COMPOSER_TLS_KEY=/Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/composer-rest-server/key.pem
COMPOSER_NAMESPACES=never
COMPOSER_AUTHENTICATION=true
COMPOSER_MULTIUSER=true
COMPOSER_PROVIDERS='{
    "github": {
        "provider": "github",
        "module": "passport-github",
        "clientID": "ed692bfbb796f877f11d",
        "clientSecret": "22318ac96f2952e42c13e50a986f3554ce68eff3",
        "authPath": "/auth/github",
        "callbackURL": "/auth/github/callback",
        "successRedirect": "/",
        "failureRedirect": "/"
    }
}'
COMPOSER_DATASOURCES='{
    "db": {
        "name": "db",
        "connector": "mongodb",
        "host": "mongo"
    }
}'
```

The command I used to set up the rest server was:

```
docker run \
    -d \
    -e COMPOSER_CARD=${COMPOSER_CARD} \
    -e COMPOSER_NAMESPACES=${COMPOSER_NAMESPACES} \
    -e COMPOSER_AUTHENTICATION=${COMPOSER_AUTHENTICATION} \
    -e COMPOSER_MULTIUSER=${COMPOSER_MULTIUSER} \
    -e COMPOSER_PROVIDERS="${COMPOSER_PROVIDERS}" \
    -e COMPOSER_DATASOURCES="${COMPOSER_DATASOURCES}" \
    -e COMPOSER_TLS="${COMPOSER_TLS}" \
    -e COMPOSER_TLS_CERTIFICATE="${COMPOSER_TLS_CERTIFICATE}" \
    -e COMPOSER_TLS_KEY="${COMPOSER_TLS_KEY}" \
    -v ~/.composer:/home/composer/.composer \
    --name rest \
    --network composer_default \
    -p 3000:3000 \
    myorg/my-composer-rest-server
```

Some additional info:

```
 docker inspect composer_default
[
    {
        "Name": "composer_default",
        "Id": "0f408e3eb68601e6a8b012f7dc4a96cc2b67d1c20e73e145d907a7836e68a08d",
        "Created": "2018-01-02T11:09:30.3938878Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "189c850427e3b582b1812705df14bfd1c68c13bd8bbdf57148d8ec98eec693ee": {
                "Name": "mongo",
                "EndpointID": "46cd675cf4059425cb803d049b920f0faf8d3408859cb65de9d976d649afacc1",
                "MacAddress": "02:42:ac:12:00:07",
                "IPv4Address": "172.18.0.7/16",
                "IPv6Address": ""
            },
            "1f9393ff38ca9035ca15d3fc036b142d148375189b3436aa58cd97c5109f8b4b": {
                "Name": "couchdb",
                "EndpointID": "0c6852cece9286e71cb00a0dcd0bb857143874c330657ea342083fc1905d0da0",
                "MacAddress": "02:42:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            },
            "2abb6dd730bc59f386a6e055fe078542d033454d4ab79d459087770ff0d3de0b": {
                "Name": "ca.org1.example.com",
                "EndpointID": "7d2e3dce8602ecd0b393591119edbec79a4d93dff5433a6c660feff85ee7dea6",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "694d547954ef825f3569b11a922ac4310b143af2dbfa5643abf4e2b02fb8947b": {
                "Name": "rest",
                "EndpointID": "ec6bf5cd5eea4ff838e2145f2fcf74636daa923f49f54db57eaa5659fa03987e",
                "MacAddress": "02:42:ac:12:00:08",
                "IPv4Address": "172.18.0.8/16",
                "IPv6Address": ""
            },
            "7e6cd2f25db76a3db0fc2cf7001595a6f88333ad097d9306068caf4c503948b0": {
                "Name": "peer0.org1.example.com",
                "EndpointID": "e837457bd6aa4ff1838584ad8a7bb3dd4cf79c877628b6a6976db71b47b650b3",
                "MacAddress": "02:42:ac:12:00:05",
                "IPv4Address": "172.18.0.5/16",
                "IPv6Address": ""
            },
            "cfd42bab003e9afc7c205909ec4f5392947a6b30a93df8e1e9129ecd0fd02984": {
                "Name": "dev-peer0.org1.example.com-block-aviation-network-0.16.2",
                "EndpointID": "508d11ba71ec5ad61ed212595b57992bfa6ca4733e1712782f3c09e9f0aa1247",
                "MacAddress": "02:42:ac:12:00:06",
                "IPv4Address": "172.18.0.6/16",
                "IPv6Address": ""
            },
            "fdb3d2651ef57036b7f10228b2813437f301531fb7bd97b9bb29dd5eeb3790c5": {
                "Name": "orderer.example.com",
                "EndpointID": "9a2d97ee8bd4c3a717bd3d898947a7f317c255740697fb5612946b0c5959a223",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

My docker containers:

```
 docker ps
CONTAINER ID        IMAGE                                                                                                                       COMMAND                  CREATED             STATUS              PORTS                                            NAMES
694d547954ef        myorg/my-composer-rest-server                                                                                               "pm2-docker compos..."   14 minutes ago      Up 14 minutes       0.0.0.0:3000->3000/tcp                           rest
189c850427e3        mongo                                                                                                                       "docker-entrypoint..."   3 hours ago         Up 3 hours          0.0.0.0:27017->27017/tcp                         mongo
cfd42bab003e        dev-peer0.org1.example.com-block-aviation-network-0.16.2-a03bf114976a6a5a4186c9afaa5f7a38ccfc6320fc4a1cc0c5a728fa803d3fcb   "chaincode -peer.a..."   3 hours ago         Up 3 hours                                                           dev-peer0.org1.example.com-block-aviation-network-0.16.2
7e6cd2f25db7        hyperledger/fabric-peer:x86_64-1.0.4                                                                                        "peer node start -..."   3 hours ago         Up 3 hours          0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp   peer0.org1.example.com
1f9393ff38ca        hyperledger/fabric-couchdb:x86_64-1.0.4                                                                                     "tini -- /docker-e..."   3 hours ago         Up 3 hours          4369/tcp, 9100/tcp, 0.0.0.0:5984->5984/tcp       couchdb
fdb3d2651ef5        hyperledger/fabric-orderer:x86_64-1.0.4                                                                                     "orderer"                3 hours ago         Up 3 hours          0.0.0.0:7050->7050/tcp                           orderer.example.com
2abb6dd730bc        hyperledger/fabric-ca:x86_64-1.0.4                                                                                          "sh -c 'fabric-ca-..."   3 hours ago         Up 3 hours          0.0.0.0:7054->7054/tcp                           ca.org1.example.com
Simons-MacBook-Pro:mongo_docker simonmullaney$ 
```

**Comment by sstone1** [comment]
@simonmullaney 0.0.0.0 isn't the right IP address; because you're now on the Docker network, you need the IP addresses or hostnames of the right Docker containers, for example `peer0.org1.example.com`.

**Comment by simonmullaney** [comment]
Thanks @sstone1.

I think I have it all connected up right now.

However, `docker logs rest` is now giving m the output:

```
PM2        | App [composer-rest-server] with id [0] and pid [720], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:composer-rest-server id:0
PM2        | App name:composer-rest-server id:0 online
0|composer | WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
0|composer | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
0|composer | Discovering types from business network definition ...
0|composer | Discovered types from business network definition
0|composer | Generating schemas for all types in business network definition ...
0|composer | Generated schemas for all types in business network definition
0|composer | Adding schemas for all types to Loopback ...
0|composer | Swagger: skipping unknown type "AddPart".
0|composer | Swagger: skipping unknown type "MonitorPlane".
0|composer | Swagger: skipping unknown type "Location".
0|composer | Swagger: skipping unknown type "AddPart".
0|composer | Swagger: skipping unknown type "MonitorPlane".
0|composer | Swagger: skipping unknown type "Location".
0|composer | Swagger: skipping unknown type "AddPart".
0|composer | Swagger: skipping unknown type "MonitorPlane".
0|composer | Swagger: skipping unknown type "AddPart".
0|composer | Swagger: skipping unknown type "MonitorPlane".
0|composer | Swagger: skipping unknown type "AddPart".
0|composer | Swagger: skipping unknown type "MonitorPlane".
0|composer | Swagger: skipping unknown type "AddPart".
0|composer | Swagger: skipping unknown type "MonitorPlane".
0|composer | Swagger: skipping unknown type "AddPart".
0|composer | Swagger: skipping unknown type "MonitorPlane".
0|composer | Swagger: skipping unknown type "AddPart".
0|composer | Swagger: skipping unknown type "MonitorPlane".
0|composer | Swagger: skipping unknown type "AddPart".
0|composer | Swagger: skipping unknown type "MonitorPlane".
0|composer | Swagger: skipping unknown type "AddPart".
0|composer | Swagger: skipping unknown type "MonitorPlane".
0|composer | Swagger: skipping unknown type "MonitorPlane".
0|composer | Added schemas for all types to Loopback
0|composer | { Error: ENOENT: no such file or directory, open '/Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/composer-rest-server/cert.pem'
0|composer |     at Object.fs.openSync (fs.js:646:18)
0|composer |     at Object.fs.readFileSync (fs.js:551:33)
0|composer |     at Promise.then (/home/composer/.npm-global/lib/node_modules/composer-rest-server/server/server.js:158:29)
0|composer |     at <anonymous>
0|composer |     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
0|composer |   errno: -2,
0|composer |   code: 'ENOENT',
0|composer |   syscall: 'open',
0|composer |   path: '/Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/composer-rest-server/cert.pem' }
```

I do have a cert.pem file at: /Users/simonmullaney/.nvm/versions/node/v8.9.3/lib/node_modules/composer-rest-server/cert.pem 

```
-----BEGIN CERTIFICATE-----
MIIGMDCCBBigAwIBAgIJAN/lALhnrM8dMA0GCSqGSIb3DQEBBQUAMG0xCzAJBgNV
BAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNp
c2NvMR0wGwYDVQQKExRIeXBlcmxlZGdlciBDb21wb3NlcjESMBAGA1UEAxMJbG9j
YWxob3N0MB4XDTE3MDcyMzE2MDAxM1oXDTQyMDcxNzE2MDAxM1owbTELMAkGA1UE
BhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lz
Y28xHTAbBgNVBAoTFEh5cGVybGVkZ2VyIENvbXBvc2VyMRIwEAYDVQQDEwlsb2Nh
bGhvc3QwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCc8ePUNTS/HbOm
d4xrCYwViyvkGNAfL5/4FLc9evbnC8qLpVxnWNkpF/bdBVEMEjgsZUp//dqhkNOP
qt6vlVQUi3+gYljuVEzc8bCJOc0b3JWajUnTYz9MItEnLZA3tywjL0E8fD6LfwUv
HLKk3p2nKfZuDYaL5Xd/93lxfSLGLVRtH++A+5drVeBNOPEaGglccvJQWbcoM1mF
j/PWq1OKhZqMQ1Ud5HpqQWIplP2yl8JPaC1JCMEJRjeNeEiPzQ2T5P8T/SJExe3I
KxmNIwKq35+JVw7E4+7ew0rAc76LwF/E4D64sarGyrKiRDl0mZAX4K7o4dtpNvtx
uGHdzJg1LlajjY/RwVtuYKQtkHst4EZ/cg0wWz+lwOwAVDA7PcRHhOk2OlruhSIf
mjb1FDXRuS37GtZqhzIonWdlDeu5rmuwvfm5tLlIFvpiN3ZBY2TDSEZQ9//CCDaM
xJhQA8xa/jylxooupGqFb8stwP844rJO7JrozS3IircPEmNazt9/Oa1WAvhepq2w
D99SJtl2PGfq7ugMmc0eqxJB9zOPCp8CNtBxNSGbP30N/Fts+LAaDMphweOf4TAg
dPddHuyYOLvgx/krh9qSSeE2TvEdtPwR0BOS6/f+W3ZJ8WDRbzyifY78S8bQGOKE
KcmOzNAf6t4TZz2rIufkAAe/20TciwIDAQABo4HSMIHPMB0GA1UdDgQWBBRyehOx
L8ZGgdsGmylTdOxMUewNrTCBnwYDVR0jBIGXMIGUgBRyehOxL8ZGgdsGmylTdOxM
UewNraFxpG8wbTELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAU
BgNVBAcTDVNhbiBGcmFuY2lzY28xHTAbBgNVBAoTFEh5cGVybGVkZ2VyIENvbXBv
c2VyMRIwEAYDVQQDEwlsb2NhbGhvc3SCCQDf5QC4Z6zPHTAMBgNVHRMEBTADAQH/
MA0GCSqGSIb3DQEBBQUAA4ICAQAu9fpGOkUNX9yuyYfn8tp4Wheg3VudLjTbWAww
Amee33nd93MGKCtZUn5RaFzlCHFlLhHI7tzT87ZXVx5oK9wiHDAsS+Pc63OYuO3A
bgldQz3lD6MoefKpo4Cukmimz5eZ2uVOhgLPfkl6WR5VLCUV2odMmpr2wpvcqU9t
CknZ1XqDa2l3XP0JZvtEUNBgqwN9s6nNflBrQukGuv7ueIbl0+ZOqvpmRZlWEvin
4t3ji5s1GfAgK4JfR0tpJah2KfnEQtFXO4OpvyvE7gDxF+J158Xv8Nivl7qwSm0n
tTc5lgbATNia+2sDmMSOGu/cnwsgm/12iqZL06hcKg44aGqPMjJ1ZWjvT2fXCtus
Mgn1Llm6yNj6f/dkb7ZafszSVqSCZQbj0bxkHFH7zFW6jGev8IxlVYCUQJeeEzAB
lCS5jIRU3RcbnzNv9q5Ck2lNYDZWrb7DetOxaDTmSn1TGu61BnLcfrTF+w4ufbGv
xQjvkaO7zkls27yDnZkVH8Nt/zm4apCf5Yov882aq3A5YHB9kfUhZZgsyflaTyqZ
sqGunmOCOGu/izVUssLvmvYPE4QiFboUJcujSoCdLgvJBATlyikZTpAtQ2dYU6/B
leRT9It7GtAHIKJJ6Q2x8SSHVn3DvXf/V8d+7114/wl1vjhPHUF1gFJPL2r+X3/V
cU3fIQ==
-----END CERTIFICATE-----
```

Do I have to copy this file into my docker container so that it can open it?
