### ISSUE TITLE
ms build failed with exit code 1

### ISSUE THREAD

**Issue by giridhari1** [hyperledger/composer#3129]
I'm Running the hyperledger fabric samples,i get into the fabcar directory and do an npm install to get all project dependencies but an error always shows up,here is the log-

   
```
> pkcs11js@1.0.12 install C:\Users\Vishal\fabric-samples\fabcar\node_modules\pkc
s11js
> node-gyp rebuild


C:\Users\Vishal\fabric-samples\fabcar\node_modules\pkcs11js>if not defined npm_c
onfig_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\
\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targ
ets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\Vis
hal\fabric-samples\fabcar\node_modules\pkcs11js\build\pkcs11.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Vishal\fabric-samples\fabcar\node_modules\pkcs11js
gyp ERR! node -v v6.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
fabcar@1.0.0 C:\Users\Vishal\fabric-samples\fabcar
`-- (empty)

npm WARN fabcar@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pkcs11js@1.0.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pkcs11js@1.0.12 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pkcs11js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pkcs11js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pkcs11js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Vishal\fabric-samples\fabcar\npm-debug.log
npm ERR! code 1
```

i am using windows 7 64 bit 
node version 6.9.3
npm version .10.10
python 2.7 and vc++2015(from npm install --global windows-build-tools)

Error is not fixed even after i update npm and node to higher versions.

Need  help
Thanks

**Comment by sstone1** [comment]
Wrong project @giridhari1, you need to raise this against Hyperledger Fabric.
