### ISSUE TITLE
Running "~/fabric-tools/createPeerAdminCard.sh" gives syntax error

### ISSUE THREAD

**Issue by praveeng145** [hyperledger/composer#3186]
## Issue
Unable to set up the dev env of Hyperledger composer

## Context
Am new to Hyperledger Composer and setting up my dev env following instructions [here](https://hyperledger.github.io/composer/installing/development-tools.html) and followed all the recommended paths. Finally when I run the `~/fabric-tools/createPeerAdminCard.sh` from VS code terminal I got the following error (looks like a syntax error from composer-cli)

> readyshout-lm:Blockchain praveen$ ~/fabric-tools/createPeerAdminCard.sh
Development only script for Hyperledger Fabric control
Running 'createPeerAdminCard.sh'
FABRIC_VERSION is unset, assuming hlfv1
FABRIC_START_TIMEOUT is unset, assuming 15 (seconds)
Using composer-cli at v0.16.3
/usr/local/lib/node_modules/composer-cli/node_modules/composer-common/lib/modelmanager.js:418
    getAssetDeclarations(includeSystemType = true) {
                                           ^
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/composer-cli/node_modules/composer-common/lib/businessnetworkdefinition.js:28:22)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
/usr/local/lib/node_modules/composer-cli/node_modules/composer-common/lib/modelmanager.js:418
    getAssetDeclarations(includeSystemType = true) {
                                           ^
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/composer-cli/node_modules/composer-common/lib/businessnetworkdefinition.js:28:22)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)

## Expected Behavior
Expected behavior is to launch a web page as mentioned in the documentation.

## Actual Behavior
Actual behavior is seeing this error.

## My Environment
Mac OS : 10.12.6
MS VS Code : Version 1.15.0 (1.15.0)
Hyperledger Composer VS Code Plugin : 0.11.3

**Comment by praveeng145** [comment]
I was able to resolve this issue by setting the node to v8.9.5 by running `npm use --lts` on MSVS Code's terminal.

**Comment by kaelvergara** [comment]
I encountered and same error and changing the node version doesn't fix the problem.

**Comment by rajatsvits** [comment]
I also encountered the same error and changing the node version doesn't fix the problem for me

**Comment by CoverYourII** [comment]
I used "nvm ls-remote", and there is no 8.9.5 as a version, don't know how you solved this issue.

**Comment by skarlekar** [comment]
Has anyone had luck in getting past this error? I am having the same issue and would like pointers on how to get around it. Looking forward!

**Comment by nsdeo12** [comment]
I have node version 8.10.0 ,getting the same error while running as a node service(when adding a participant).While running as  a file getting no error.

**Comment by nsdeo12** [comment]
I have node version 8.10.0 ,getting the same error while running as a node service(when adding a participant).While running as  a file getting no error.
