### ISSUE TITLE
Error generating Angular app with yo generator

### ISSUE THREAD

**Issue by samjsmith** [hyperledger/composer#3302]
```
510 samsmith:test-sandbox$ yo hyperledger-composer
Welcome to the Hyperledger Composer project generator
? Please select the type of project: Angular
You can run this generator using: 'yo hyperledger-composer:angular'
Welcome to the Hyperledger Composer Angular project generator
? Do you want to connect to a running Business Network? No
? Project name: SamsTradingApp
? Description: Sams Trading Application
? Author name: Sam
? Author email: smithsj@uk.ibm.com
? License: Apache-2.0
? Business network archive file (Path from the current working directory): SamsTradingApp.bna
? REST server address: http://localhost:3000
? REST server port: 3000
? Are namespaces used in the generated REST API:  Namespaces are not used
/usr/local/lib/node_modules/generator-hyperledger-composer/node_modules/composer-common/lib/businessnetworkdefinition.js:180
        LOG.entry(method, Buffer.length);
                                 ^

TypeError: Cannot read property 'length' of undefined
    at Function.fromArchive (/usr/local/lib/node_modules/generator-hyperledger-composer/node_modules/composer-common/lib/businessnetworkdefinition.js:180:34)
    at ReadFileContext.fs.readFile [as callback] (/usr/local/lib/node_modules/generator-hyperledger-composer/generators/angular/index.js:367:54)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

**Comment by samjsmith** [comment]
This is because a LOG.entry [here](https://github.com/hyperledger/composer/blob/master/packages/composer-common/lib/businessnetworkdefinition.js#L180) isn't checking whether Buffer is defined or not.

**Comment by Genysys** [comment]
Any luck with solving this? Have the same issue

**Comment by samjsmith** [comment]
I haven't tried it yet to be honest but it should be a pretty quick fix. What version are you using?

**Comment by Genysys** [comment]
composer version: v.16.2
yo: 2.0.1

Not well versed at node but would happily take directions on fixing it

**Comment by samjsmith** [comment]
Looking at this a bit closer, I can see that I made an error when trying to use the `yo hyperledger-generator` command because I wasn't in the same directory as the .bna file that it asked me for. 
So, it's basically an error because the generator can't find the .bna file that you want to use. 
I think that it's still not very nice that you get the error that you do and that it would maybe be better to use Path.resolve on the fileName which will throw an ENOENT error and make it clearer what the problem actually is.

**Comment by samjsmith** [comment]
@Gensys this could do with being fixed and I can help you get started if you'd like to start contributing to the project :)

**Comment by Genysys** [comment]
I would love to!!

Not sure about the error as it asks you if you want to use an existing
business network or not.

Anyways help getting started with contributing will be very much
appreciated.

**Comment by davidkel** [comment]
@KaiUsher Is this still an issue ?

**Comment by Genysys** [comment]
Works fine for me now

**Comment by davidkel** [comment]
Closing as Kai says it's not an issue now and also confirmed above.

**Comment by jdockter** [comment]
@davidkel @KaiUsher 
I'm also getting a similar error when trying to generate an Angular app.  Following error on either a standalone bna or running network:

```events.js:183
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /home/ibm/.nvm/versions/node/v8.9.0/lib/node_modules/generator-hyperledger-composer/generators/angular/templates/src/app/concept/concept.component.ts
    at EditionInterface.exports._copySingle (/home/ibm/.nvm/versions/node/v8.9.0/lib/node_modules/generator-hyperledger-composer/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/home/ibm/.nvm/versions/node/v8.9.0/lib/node_modules/generator-hyperledger-composer/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/home/ibm/.nvm/versions/node/v8.9.0/lib/node_modules/generator-hyperledger-composer/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at Promise (/home/ibm/.nvm/versions/node/v8.9.0/lib/node_modules/generator-hyperledger-composer/generators/angular/index.js:834:25)
    at new Promise (<anonymous>)
    at child._createApp (/home/ibm/.nvm/versions/node/v8.9.0/lib/node_modules/generator-hyperledger-composer/generators/angular/index.js:393:26)
    at businessNetworkConnection.connect.then.then (/home/ibm/.nvm/versions/node/v8.9.0/lib/node_modules/generator-hyperledger-composer/generators/angular/index.js:364:38)
    at <anonymous>
```
```

**Comment by caroline-church** [comment]
done so closing

**Comment by mhamzawey** [comment]
Any luck with this? I still have this problem
