### ISSUE TITLE
MultiUser REST server error

### ISSUE THREAD

**Issue by majkowski** [hyperledger/composer#3553]
REST server throws error after successfully authenticating and importing .card to wallet.

## Context
I'm currently experimenting with Composer Fabric 1.1RC and have encountered an issue with multiple user mode of REST server. Authentication proceeds OK (I'm using passport-local with MongoDB as storage backend), .card import also finishes without error. But when I attempt to do GET /system/ping to check my identity, then error occurs.

## Expected Behavior
GET /system/ping should return structure like 
```
{
  "participant": "string",
  "identity": "string",
  "version": "string"
}
```
and HTTP 200 code

## Actual Behavior
Instead, this error and HTTP 500 code is returned:
```
{
  "error": {
    "statusCode": 500,
    "name": "Error",
    "message": "Error trying login and get user Context. TypeError: this.wallet.contains is not a function",
    "stack": "Error: Error trying login and get user Context. TypeError: this.wallet.contains is not a function\n    at client.getUserContext.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:285:34)\n    at <anonymous>"
  }
}
```
composer-rest-server also returns traceback on console:
```
(node:7228) UnhandledPromiseRejectionWarning: Error: BusinessNeworkCardStore Abstract function called - getWallet
    at LoopBackCardStore.getWallet (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-common/lib/cardstore/businessnetworkcardstore.js:105:31)
    at cardStore.get.then (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-client/lib/businessnetworkconnection.js:402:66)
    at tryCatcher (/usr/local/lib/node_modules/composer-rest-server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/composer-rest-server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/composer-rest-server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/composer-rest-server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/composer-rest-server/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/local/lib/node_modules/composer-rest-server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/composer-rest-server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/composer-rest-server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
(node:7228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Unhandled error for request GET /api/system/ping: Error: Error trying login and get user Context. TypeError: this.wallet.contains is not a function
    at client.getUserContext.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:285:34)
    at <anonymous>
```

I also noticed, that ID for this user stays as ISSUED in ID Registry in Playground.

## Steps to Reproduce
1. Create a new identity linked to some Participant in Playground, make sure to select "Give it to someone else" when prompted what to do with .card file and save it on disk
2. Start ```composer-rest-server``` with ```-m true```
3. Authenticate to REST server
4. Import the .card file you created in step 1 using POST /wallet/import
5. Attempt to GET /system/ping

## Your Environment
* Node v9.5.0
* Fabric v1.1RC
* composer-rest-server v0.18.0
* composer-playground 0.18
* composer v0.18.0

**Comment by davidkel** [comment]
This has been fixed in pull requests 
#3550 & #3543 and will go out in the next release, probably 0.18.1
