### ISSUE TITLE
Failures in before step for FV tests

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3589]
The following is causing test fails:

```
Historian "before all" hook:
     Error: Error trying invoke business network. Error: Peer localhost:7051 has rejected transaction 'dc3adabf8b6ab0ba82aff66dfbbfc72cd5a861959a33b71c1244b99353731c60' with code ENDORSEMENT_POLICY_FAILURE
      at _initializeChannel.then.then.then.then.catch (/home/travis/build/hyperledger/composer/packages/composer-connector-hlfv1/lib/hlfconnection.js:1004:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

We could/should be wrapping sensitive functions like the above in a sensible way.

**Comment by davidkel** [comment]
@nklincoln see #1840
