### ISSUE TITLE
Composer Report Command Failing

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3614]
Composer report command is failing within the integration tests ... this is sub optimal!

Could do with investigating and fixing 👍 

Frustratingly, the integration tests were hiding this failure :(

**Comment by samjsmith** [comment]
@nklincoln can you give more details on this please? 
How is it failing? What's changed? How were the tests hiding this failure?

**Comment by samjsmith** [comment]
I've just pulled master and run the integration tests and none of the queries/rest tests pass for me :(

**Comment by nklincoln** [comment]
hmmm, all passing in the travis builds ....

Not sure what has changed, turns out that in the builds tests were failing but Travis wasn't picking up on the non-zero return code ... it is now tho

**Comment by mbwhite** [comment]
Running on master I've encountered this
```
1) Scenario: Using the CLI, I can run a composer report command to create a file about the current environment - features/cli-report.feature:7
   Step: When I run the following expected pass CLI command - features/cli-report.feature:8
   Step Definition: lib/clisteps.js:39
   Message:
     Error: { code: 1,
       stdout: 'Creating Composer report\nCollecting diagnostic data...\n',
       stderr: '\nWriting Node.js report to file: node-report.20180319.141743.16078.001.txt\nNode.js report completed\n\nWriting Node.js report to file: node-report.20180319.141743.16078.002.txt\nNode.js report completed\n/home/matthew/.nvm/versions/node/v8.9.4/lib/node_modules/composer-cli/node_modules/yargs/yargs.js:1100\n      else throw err\n           ^\n\nError: ENOENT: no such file or directory, lstat \'/tmp/TMMewt/composer-report-20180319T141743/composer-report-20180319T141743.txt\'\n    at Object.fs.lstatSync (fs.js:941:11)\n    at PackSync.[stat] (/home/matthew/.nvm/versions/node/v8.9.4/lib/node_modules/composer-cli/node_modules/tar/lib/pack.js:358:31)\n    at PackSync.[processJob] (/home/matthew/.nvm/versions/node/v8.9.4/lib/node_modules/composer-cli/node_modules/tar/lib/pack.js:251:19)\n    at PackSync.[process] (/home/matthew/.nvm/versions/node/v8.9.4/lib/node_modules/composer-cli/node_modules/tar/lib/pack.js:207:23)\n    at PackSync.[addFSEntry] (/home/matthew/.nvm/versions/node/v8.9.4/lib/node_modules/composer-cli/node_modules/tar/lib/pack.js:153:18)\n    at PackSync.write (/home/matthew/.nvm/versions/node/v8.9.4/lib/node_modules/composer-cli/node_modules/tar/lib/pack.js:125:23)\n    at PackSync.add (/home/matthew/.nvm/versions/node/v8.9.4/lib/node_modules/composer-cli/node_modules/tar/lib/pack.js:106:10)\n    at files.forEach.file (/home/matthew/.nvm/versions/node/v8.9.4/lib/node_modules/composer-cli/node_modules/tar/lib/create.js:78:9)\n    at Array.forEach (<anonymous>)\n    at addFilesSync (/home/matthew/.nvm/versions/node/v8.9.4/lib/node_modules/composer-cli/node_modules/tar/lib/create.js:69:9)\n' }
         at Function.<anonymous> (/home/matthew/github/composer/node_modules/cucumber/lib/user_code_runner.js:105:21)
         at Generator.throw (<anonymous>)
         at Generator.tryCatcher (/home/matthew/github/composer/node_modules/bluebird/js/release/util.js:16:23)
         at PromiseSpawn._promiseRejected (/home/matthew/github/composer/node_modules/bluebird/js/release/generators.js:107:10)
         at Promise._settlePromise (/home/matthew/github/composer/node_modules/bluebird/js/release/promise.js:576:26)
         at Promise._settlePromise0 (/home/matthew/github/composer/node_modules/bluebird/js/release/promise.js:614:10)
         at Promise._settlePromises (/home/matthew/github/composer/node_modules/bluebird/js/release/promise.js:689:18)
         at Async._drainQueue (/home/matthew/github/composer/node_modules/bluebird/js/release/async.js:133:16)
         at Async._drainQueues (/home/matthew/github/composer/node_modules/bluebird/js/release/async.js:143:10)
         at Immediate.Async.drainQueues [as _onImmediate] (/home/matthew/github/composer/node_modules/bluebird/js/release/async.js:17:14)
         at runCallback (timers.js:789:20)
         at tryOnImmediate (timers.js:751:5)
         at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by mbwhite** [comment]
```
Error: ENOENT: no such file or directory, lstat \'/tmp/TMMewt/composer-report-20180319T141743/composer-report-20180319T141743.txt
```

I do have 
[TMMewt] ls -l /tmp/TMMewt/composer-report-20180319T141743.txt                                                                                                              
-rw-r--r-- 1 matthew matthew 31 Mar 19 14:17 /tmp/TMMewt/composer-report-20180319T141743.txt

**Comment by mbwhite** [comment]
..because of the version of tar should be 4.3.0; recent work to harmonise module versions put tar back to a lower version.

**Comment by sstone1** [comment]
Why was this not tagged as a bug?! 😡
