### ISSUE TITLE
Cannot find module 'jsrsasign' when loading composer-common

### ISSUE THREAD

**Issue by PPCM** [hyperledger/composer#3761]
## Context
```
npm install composer-common@next && node -r composer-common
npm WARN deprecated fs-promise@1.0.0: Use mz or fs-extra^3.0 with Promise Support
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ composer-common@0.18.2
updated 1 package in 76.066s
module.js:549
    throw err;
    ^

Error: Cannot find module 'jsrsasign'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/node_modules/composer-common/lib/certificate.js:17:33)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

## Expected Behavior
Should not get this error.

## Actual Behavior
Do get this error.

## Possible Fix
```
npm install --save jsrsasign
```

**Comment by davidkel** [comment]
@PPCM the next tag is now pointing to an older release 0.18.2. latest is at 0.19, so would encourage you to move to latest from next.
The missing dependency has been fixed and should be in the next 0.19 release (ie 0.19.1)
