### ISSUE TITLE
composer query format compilation fails

### ISSUE THREAD

**Issue by akshatbh** [hyperledger/composer#3771]
A query like the following fails compilation when starting up the business network app:
```
query selectOrdersForProvisioning {
  description: "Select orders ready for provisioning"
  statement:
      SELECT com.biznet.sre.Order
      WHERE (status != 'CANCELLED' AND status != 'RESERVED_IP')
}
```
fails with this error:
running start.js
TypeError: Cannot redefine property: $ne
    at Function.defineProperty (<anonymous>)
    at QueryCompiler.visitArrayCombinationOperator (/usr/local/src/node_modules/composer-runtime/lib/querycompiler.js:549:36)
    at QueryCompiler.visitBinaryExpression (/usr/local/src/node_modules/composer-runtime/lib/querycompiler.js:477:27)
    at QueryCompiler.visit (/usr/local/src/node_modules/composer-runtime/lib/querycompiler.js:84:27)
    at QueryCompiler.visitWhere (/usr/local/src/node_modules/composer-runtime/lib/querycompiler.js:351:31)
    at QueryCompiler.visit (/usr/local/src/node_modules/composer-runtime/lib/querycompiler.js:76:27)
    at Where.accept (/usr/local/src/node_modules/composer-common/lib/query/where.js:55:24)
    at QueryCompiler.visitSelect (/usr/local/src/node_modules/composer-runtime/lib/querycompiler.js:300:42)
    at QueryCompiler.visit (/usr/local/src/node_modules/composer-runtime/lib/querycompiler.js:74:27)
    at Select.accept (/usr/local/src/node_modules/composer-common/lib/query/select.js:58:24)

It appears that multiple NEQ comparisons are not supported for the same field? 

## Expected Behavior
Query should compile

## Possible Fix
If this is not the correct format and a different  format is supported then that format and examples must be documented and then the issue can be closed, otherwise the query compiler needs to support multiple NEQ comparisons on the same field.

## Context
This is a limitation in how I can query effectively and therefore requiring inefficient workarounds.

## Your Environment
* Version used: composer 0.19.0, fabric 1.1
* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

**Comment by sstone1** [comment]
@andrew-coleman this one might be up your street

**Comment by MonarthS** [comment]
@sstone1 Any update in this?
