### ISSUE TITLE
Rest API Multiuser error "Error trying login and get user Context"

### ISSUE THREAD

**Issue by driesvb** [hyperledger/composer#3915]
Error occurs when trying to call any API endpoint (except the /wallet/ endpoints) while in multi user mode and authenticated with a valid activate identity. 

## Context
Everything is done conforming to the specifications. User is authenticated using Passport's Github strategy and has an active identity card in its wallet. Using endpoint /api/system/ping in this example but the problem occurs with any non-/wallet/ API endpoint.

## Expected Behavior
When calling endpoint /api/system/ping it should return a response formatted as
`{
  "participant": "string",
  "identity": "string",
  "version": "string"
}`

with the values corresponding to the values of the authenticated identity.

## Actual Behavior
The following response is returned instead

`{"error":{"statusCode":500,"name":"Error","message":"Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{\"code\":20,\"message\":\"Authorization failure\"}]]","stack":"Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{\"code\":20,\"message\":\"Authorization failure\"}]]\n    at client.getUserContext.then.then.catch (/home/dries/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:395:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}}`

and the following in the composer-rest-server console

```
Unhandled error for request GET /api/system/ping: Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{"code":20,"message":"Authorization failure"}]]
    at client.getUserContext.then.then.catch (/home/dries/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:395:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

## Possible Fix
N/A

## Steps to Reproduce

1. Start the Composer Rest API in multi user mode with Passport's Github strategy as the strategy. (success)
2. Create a new identity card (e.g. using Playground) (success)
3. Authenticate with Github (success)
4. Import the identity card with the /wallet/import/ endpoint (success)
5. Call the /api/system/ping endpoint (failure)

## Existing issues

- [ ] [GitHub issue #3553 ](https://github.com/hyperledger/composer/issues/3553) (closed but doesn't seem fixed to me)

## Context
Being able to authenticate and perform authenticated transactions is a big part of the client application I am building. 

## Your Environment
* Versions used: Composer v0.19.2, Composer Rest Server v0.19.2, NodeJS v8.9.4
* Operating System and version (desktop or mobile): Ubuntu 16.04.4 (LTS)

**Comment by driesvb** [comment]
*not* a bug. Did not include the "name" field when uploading the card using the /wallet/import endpoint.

**Comment by prtk418** [comment]
I am also facing this issue, is this fixed??

**Comment by yuva670** [comment]
I am facing the same issue with version 0.19.8

**Comment by kathunsinger** [comment]
I am also facing this issue, has a solution been found?

**Comment by yuva670** [comment]
It started working from me when I just cleared all the cards from ~./.composer

**Comment by yuva670** [comment]
It started working from me when I just cleared all the cards from ~./.composer

**Comment by iamprajyot** [comment]
I am also facing this issue.. Anyone found any solution. ?
I am using version 0.20.1 for composer

**Comment by XBITSwitzerland** [comment]
Same issue here. Someone found a solution?
