### ISSUE TITLE
REST GET /Asset/{id} TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by majkowski** [hyperledger/composer#3918]
REST Server throws this error when trying to access some asset by its ID. When accessing all assets from registry by GET /Asset the error does not occur. The complete backtrace from REST server is:
`
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at sendJson (/Users/patrikmajkowski/Code/HL-CRM-BE/node_modules/strong-error-handler/lib/send-json.js:9:22)
    at strongErrorHandler (/Users/patrikmajkowski/Code/HL-CRM-BE/node_modules/strong-error-handler/lib/handler.js:60:5)
    at Layer.handle_error (/Users/patrikmajkowski/Code/HL-CRM-BE/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/patrikmajkowski/Code/HL-CRM-BE/node_modules/express/lib/router/index.js:315:13)
    at /Users/patrikmajkowski/Code/HL-CRM-BE/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/patrikmajkowski/Code/HL-CRM-BE/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/patrikmajkowski/Code/HL-CRM-BE/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Users/patrikmajkowski/Code/HL-CRM-BE/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/patrikmajkowski/Code/HL-CRM-BE/node_modules/express/lib/router/index.js:315:13)
    at /Users/patrikmajkowski/Code/HL-CRM-BE/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/patrikmajkowski/Code/HL-CRM-BE/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/Users/patrikmajkowski/Code/HL-CRM-BE/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/Users/patrikmajkowski/Code/HL-CRM-BE/node_modules/express/lib/router/index.js:635:15)
    at runCallback (timers.js:764:11)
    at tryOnImmediate (timers.js:734:5)
`

Playground is not affected by this issue.

## Context
I confirmed, that this issue occurs only when extending abstract Asset with primary identifier. We want to have UUIDs on all assets, so I made an abstract asset to not have to repeat UUID RegEx every time:
`
namespace org.whatever.assets

abstract asset Identifiable {
  o String uuid regex=/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/
}

asset Account identified by uuid extends Identifiable {
  o String name
}
`

## Expected Behavior
When I do GET /Account/{uuid} I expect to get HTTP 200 code and asset, assuming it exists and

## Actual Behavior
When I do GET /Account/{uuid} I get error in title and HTTP 500 code

## Possible Fix
Workaround for now is not to use abstract asset and just duplicate the UUID RegEx for every asset. This fixes the issue, but is not optimal for reasons of code duplication. In case of model in Context section, the working version is:
asset Account identified by uuid {
  o String uuid regex=/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/
  o String name
}

## Steps to Reproduce
1. Deploy business network with model in Context section
2. Use Composer Playground to create a new Account
3. Run Composer REST server and try GET /Account/{uuid} you just created

## Existing issues
Google search revealed no such issues in connection with Composer, only generic JSON.stringify errors

## Context
We are unable to use abstract assets with primary key with this issue present.

## Your Environment
Composer 0.19.2
Fabric 1.1

**Comment by olesyakorovina** [comment]
Hello,

Any updates or fixes? We are facing the same issue

**Comment by pradeeppadmarajaiah** [comment]
Same issue for us as well. Planning to use Query API to fetch it

**Comment by bhayward93** [comment]
Stuck with this now, I'll try the fix listed above tomorrow and report back if there are any issues. Thanks for taking the time to list it.
