### ISSUE TITLE
Error generating angular app using yo when following dev tutorial 

### ISSUE THREAD

**Issue by mazzoul** [hyperledger/composer#3935]
When I try to follow the tutorial (https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial, Step 6) run "yo" to generate an Angular app, I receive error when I try to ask you to connect to an existing running Composer Rest server

I have the Composer Rest API running (during the previous tutorial step):
Matt-MacBook-Pro:tutorial-network matt_so$ composer-rest-server
? Enter the name of the business network card to use: 

Matt-MacBook-Pro:tutorial-network matt_so$ 
Matt-MacBook-Pro:tutorial-network matt_so$ 
Matt-MacBook-Pro:tutorial-network matt_so$ composer-rest-server -c admin@tutorial-network -n never -w true
Discovering types from business network definition ...
Discovered types from business network definition
Generating schemas for all types in business network definition ...
Generated schemas for all types in business network definition
Adding schemas for all types to Loopback ...
Added schemas for all types to Loopback
Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer

Then when i try to run step 6, I receive the following error:
Matt-MacBook-Pro:tutorial-network matt_so$ yo
? 'Allo Matthew! What would you like to do? Hyperledger Composer

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo hyperledger-composer

Welcome to the Hyperledger Composer project generator
? Please select the type of project: Angular
You can run this generator using: 'yo hyperledger-composer:angular'
Welcome to the Hyperledger Composer Angular project generator
? Do you want to connect to a running Business Network? Yes
? Project name: angular-app
? Description: Hyperledger Composer Angular project
? Author name: Matt So
? Author email: matt.so@gmx.com
? License: Apache-2.0
? Name of the Business Network card: admin@tutorial-network
? Do you want to generate a new REST API or connect to an existing REST API?  Connect to an existing REST API

     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Unable to load requested module composer-wallet-filesystem
    at Function.getCardStore (/usr/local/lib/node_modules/generator-hyperledger-composer/node_modules/composer-common/lib/cardstore/networkcardstoremanager.js:58:23)
    at new BusinessNetworkConnection (/usr/local/lib/node_modules/generator-hyperledger-composer/node_modules/composer-client/lib/businessnetworkconnection.js:61:71)
    at _optionOrPrompt.then.then.then (/usr/local/lib/node_modules/generator-hyperledger-composer/generators/angular/index.js:301:49)
    at <anonymous>

I followed the Dev tutorial.  I am running the tutorial on MacOS (10.13.4), and the environment (composer, fabric and fabric-tool) were all created using the installation tutorial (https://hyperledger.github.io/composer/latest/installing/development-tools.html).

**Comment by zachgoll** [comment]
@mazzoul what version of Node are you running?

**Comment by mazzoul** [comment]
I have 8.11.1, as shown below.  Thanks.
...
...
...
? License: Apache-2.0
? Name of the Business Network card: admin@tutorial-network
? Do you want to generate a new REST API or connect to an existing REST API?  Connect to an existing REST API

     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Unable to load requested module composer-wallet-filesystem
    at Function.getCardStore (/usr/local/lib/node_modules/generator-hyperledger-composer/node_modules/composer-common/lib/cardstore/networkcardstoremanager.js:58:23)
    at new BusinessNetworkConnection (/usr/local/lib/node_modules/generator-hyperledger-composer/node_modules/composer-client/lib/businessnetworkconnection.js:61:71)
    at _optionOrPrompt.then.then.then (/usr/local/lib/node_modules/generator-hyperledger-composer/generators/angular/index.js:301:49)
    at <anonymous>
Matt-MacBook-Pro:tutorial-network matt_so$ node -v
v8.11.1
Matt-MacBook-Pro:tutorial-network matt_so$

**Comment by zachgoll** [comment]
I followed exactly what you did, and did not have any problems.  I know you said you followed the installation tutorial, but maybe you could double check and run through it once more, or at least list the versions of composer packages that are being used here?

**Comment by smorrisfv** [comment]
I'm seeing this issue in a docker container.

Container image: node:8.11-alpine

I'd installed some build tooks, `apk add python make g++` so that it could build the various dependencies.

```javascript
this.composer.initialize();
```
The error is
```
Error: Unable to load requested module composer-wallet-filesystem
         at Function.getCardStore (/root/microinsurancenetwork/node_modules/composer-common/lib/cardstore/networkcardstoremanager.js:58:23)
         at new AdminConnection (/root/microinsurancenetwork/node_modules/composer-admin/lib/adminconnection.js:69:71)
         at Composer.createAdminConnection (/root/microinsurancenetwork/node_modules/composer-cucumber-steps/lib/composer.js:175:33)
         at Composer.initialize (/root/microinsurancenetwork/node_modules/composer-cucumber-steps/lib/composer.js:89:21)
         at World.<anonymous> (/root/microinsurancenetwork/steps/hooks.js:27:30)
```

**Comment by davidkel** [comment]
Unable to recreate and have tried a few times, closing.
