### ISSUE TITLE
Chrome developer tools causes websockets to not work correctly with Angular generator

### ISSUE THREAD

**Issue by zachgoll** [hyperledger/composer#3949]
When a developer goes to debug their newly generated Angular application by opening Chrome Developer tools, what seems to be a websocket error is thrown over and over again making it impossible to debug.

## Context
Developers who have generated a new Angular application will most likely use Chrome development tools to tweak their application, and shouldn't deal with this issue.  Not sure why opening Chrome development tools triggers this?

## Expected Behavior
Developer should be able to open Chrome dev tools and debug their newly generated Angular application

## Actual Behavior
Upon opening Chrome dev tools, developer receives websocket error

## Possible Fix
In `proxy.conf.js`, change the `context` of the second object to `/api`, or just set `ws: true` to `ws: false`.

Neither of these fixes seem like long term solutions though?

## Steps to Reproduce

1. Deploy and run the perishable sample network from [composer-sample-networks repo](https://github.com/hyperledger/composer-sample-networks).
2. Run the Angular generator like so: 

```
yo hyperledger-composer:angular --liveNetwork true --appName perishable-network --appDescription "Hyperledger composer angular project" --authorName "Zach" --authorEmail zach@email.com --license "apache-2.0" --cardName admin@perishable-network --apiServer generate --apiPort 3000 --apiNamespace never
```

3. Navigate to the angular application directory and run the application

```
cd perishable-network
npm start
```

4. Open Google Chrome, navigate to `http://localhost:4200`
5. Open Chrome Developer tools (everything should be fine at this step)
6. Navigate to one of the assets in the network (ex: `http://localhost:4200/Grower`)
7. Refresh the page 

You should now see a never-ending websocket error: 

```
[0] [HPM] Upgrading to WebSocket
[0] [HPM] Error occurred while trying to proxy request /sockjs-node/083/tyk4brer/websocket from localhost:4200 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

## Existing issues

May fall under #3136 

## Your Environment

* Version used: All composer tools - `v0.19.4`
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome (Official build), Node v8.10.0
* Operating System and version (desktop or mobile): OSX 10.13.3

**Comment by sstone1** [comment]
@zachgoll the error suggests that the REST server is not running:

`http://localhost:3000 (ECONNREFUSED)`

Can you confirm that the REST server is up and running and available on that port?

**Comment by zachgoll** [comment]
@sstone1 On my machine, at step 7 listed above, the terminal window which is running the rest server crashes with the error described above.  It may be highly specific to the case where the Angular generator generates a new REST server, but nonetheless this error has something to do with websockets because the error is not thrown when I set `ws: false` in `proxy.conf.js`.  

When I turn off websockets, the REST server behaves normally and returns me a list of assets.

**Comment by sstone1** [comment]
@zachgoll none of the errors above can come from the REST server - the proxy configuration in `proxy.conf.js` is only used by the Angular application being served on port 4200, and the `[HPM]` errors are coming from a web browser accessing port 4200... I don't see any errors from the `composer-rest-server`. Fair enough that the WebSocket connection might cause the REST server to crash, but we need the REST server errors to diagnose why.

If you can't start the `composer-rest-server` manually, can you paste the errors from the output of running `composer-rest-server` in please?

**Comment by zachgoll** [comment]
@sstone1 Ah that's my bad, I should have included all the logs.  Here is everything I am seeing from the moment I refresh the page in step 7 above.

```
[1] Unhandled error for request GET /bootstrap.min.css.map: Error: Cannot GET /bootstrap.min.css.map
[1]     at raiseUrlNotFoundError (/Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/loopback/server/middleware/url-not-found.js:21:17)
[1]     at Layer.handle [as handle_request] (/Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/express/lib/router/layer.js:95:5)
[1]     at trim_prefix (/Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/express/lib/router/index.js:317:13)
[1]     at /Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/express/lib/router/index.js:284:7
[1]     at Function.process_params (/Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/express/lib/router/index.js:335:12)
[1]     at next (/Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/express/lib/router/index.js:275:10)
[1]     at /Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/express/lib/router/index.js:635:15
[1]     at next (/Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/express/lib/router/index.js:260:14)
[1]     at Function.handle (/Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/express/lib/router/index.js:174:3)
[1]     at router (/Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/express/lib/router/index.js:47:12)
[1]     at Layer.handle [as handle_request] (/Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/express/lib/router/layer.js:95:5)
[1]     at trim_prefix (/Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/express/lib/router/index.js:317:13)
[1]     at /Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/express/lib/router/index.js:284:7
[1]     at Function.process_params (/Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/express/lib/router/index.js:335:12)
[1]     at next (/Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/express/lib/router/index.js:275:10)
[1]     at urlencodedParser (/Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/body-parser/lib/types/urlencoded.js:91:7)
[0] [HPM] Upgrading to WebSocket
[1] events.js:183
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1]
[1] Error: invalid status code: 51317
[1]     at Receiver.controlMessage (/Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/ws/lib/Receiver.js:414:22)
[1]     at Receiver.getData (/Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/ws/lib/Receiver.js:325:12)
[1]     at Receiver.startLoop (/Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/ws/lib/Receiver.js:165:16)
[1]     at Receiver.add (/Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/ws/lib/Receiver.js:139:10)
[1]     at Socket._ultron.on (/Users/Zach/github/composer-sample-networks/packages/perishable-network/perishable-network/perishable-network/node_modules/ws/lib/WebSocket.js:142:22)
[1]     at emitOne (events.js:116:13)
[1]     at Socket.emit (events.js:211:7)
[1]     at addChunk (_stream_readable.js:263:12)
[1]     at readableAddChunk (_stream_readable.js:250:11)
[1]     at Socket.Readable.push (_stream_readable.js:208:10)
[1]     at TCP.onread (net.js:607:20)
[0] [HPM] Error occurred while trying to proxy request /api/Shipment from localhost:4200 to http://localhost:3000 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! perishable-network@0.0.1 api: `composer-rest-server --card admin@perishable-network --namespaces never --port 3000`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the perishable-network@0.0.1 api script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /Users/Zach/.npm/_logs/2018-05-02T14_32_55_060Z-debug.log
[1] npm run api exited with code 1
[0] [HPM] Upgrading to WebSocket
[0] [HPM] Error occurred while trying to proxy request /sockjs-node/994/dz3434an/websocket from localhost:4200 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Comment by RameshJhajharia** [comment]
I am facing the same issue and it happens only on opening dev toolbar in the chrome.

`Unhandled error for request GET /bootstrap.min.css.map: Error: Cannot GET /bootstrap.min.css.map
    at raiseUrlNotFoundError (/Users/rjhajharia/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/Users/rjhajharia/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/rjhajharia/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /Users/rjhajharia/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/rjhajharia/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/rjhajharia/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at /Users/rjhajharia/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:635:15
    at next (/Users/rjhajharia/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/Users/rjhajharia/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/rjhajharia/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/rjhajharia/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/rjhajharia/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /Users/rjhajharia/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/rjhajharia/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/rjhajharia/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/Users/rjhajharia/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/body-parser/lib/types/urlencoded.js:91:7)
`

**Comment by mgosk** [comment]
I have same error. Chrome dev tools request `/bootstrap.min.css.map` and crash app.

```
Unhandled error for request GET /bootstrap.min.css.map: Error: Cannot GET /bootstrap.min.css.map
    at raiseUrlNotFoundError (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at /home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:635:15
    at next (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:174:3)
    at router (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/body-parser/lib/types/urlencoded.js:91:7)
Unhandled error for request GET /bootstrap.min.css.map: Error: Cannot GET /bootstrap.min.css.map
    at raiseUrlNotFoundError (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at /home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:635:15
    at next (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:174:3)
    at router (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/body-parser/lib/types/urlencoded.js:91:7)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: invalid status code: 13127
    at Receiver.controlMessage (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/ws/lib/Receiver.js:414:22)
    at Receiver.getData (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/ws/lib/Receiver.js:325:12)
    at Receiver.startLoop (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/home/mgosk/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/ws/lib/WebSocket.js:142:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)

```

**Comment by prtk418** [comment]
I am getting the same error, did anyone found a solution to this??

**Comment by cll69** [comment]
I am also getting the same error, anyone got a solution?

**Comment by AiDirex** [comment]
I get this error even when the dev tools is not open, there is no pattern and the server crashes randomly.
@sstone1

```
  loopback:model createOptionsFromRemotingContext for Trade.find +40s
  loopback:datasource Datasource composer: connected=true connecting=true +40s
  loopback:connector:composer all Trade {} { accessToken: undefined } +5ms
  loopback:connector:composer getComposerModelName Trade +0ms
  loopback:connector:composer ensureConnected +0ms
  loopback:connector:composer ensureConnected +0ms
  loopback:connector:composer getRegistryForModel org.aidin.testnet.Trade +1ms
  loopback:connector:composer isResolveSet {} +36ms
  loopback:connector:composer No `where` filter, about to perform getAll +0ms
  loopback:connector:composer Got Result: [] +32ms
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: invalid status code: 55097
    at Receiver.controlMessage (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/ws/lib/Receiver.js:414:22)
    at Receiver.getData (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/ws/lib/Receiver.js:325:12)
    at Receiver.startLoop (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/home/aidin/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/node_modules/ws/lib/WebSocket.js:142:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-network@0.0.3 rest-server: `composer-rest-server -c admin@test-network -n never -w true`
npm ERR! Exit status 1
```

**Comment by hirsche** [comment]
I'm getting the same error (REST API at http://localhost:3000/explorer events.js:183 throw er; // Unhandled 'error' event) when using the yeoman web-template as explained in the hyperledger tutorial!

However, manually it is possible for me to navigate to http://localhost:3000/explorer without getting an error. But when opening the web-app which is connecting to the same server the composer-rest-server ist crashing with the given error message.

Any help would be appreciated!

**Comment by salimtalout** [comment]
Delete the line `/*# sourceMappingURL=bootstrap.css.map */` from node_modules/bootstrap/dist/css/bootstrap.css

**Comment by David-Kim-TPE** [comment]
Can anyone elaborate some more information about this?
It'd be nice to know some more about the cause and solution. Especially when it is so unthinkable.

**Comment by grimmer0125** [comment]
I got the same error but every time `Error: invalid status code:` is different.

`? Specify if you want to enable event publication over WebSockets: (Y/n)` If I choose n. Then no more crash happening.

**Comment by davidkel** [comment]
I've set ws to false as it isn't required for the code generated by angular generator. Developers can then then take the code and add it back in as required (although I would expect developers to remove the angular-cli part that provides the hosting and passthrough to the rest server as I don't think it is a suitable production ready capability).
This is in master and is not being backported to 0.19

**Comment by riskyRahul** [comment]
PS E:\VSCodeProject\quickstartgame> flutter run -d Chrome
Launching lib\main.dart on Chrome in debug mode...
Building application for the web...                               124.5s
Attempting to connect to browser instance..
  303.0s (!)
Failed to establish connection with the application instance in Chrome.
This can happen if the websocket connection used by the web tooling is unabled to correctly establish a connection, for example due toa firewall.

**Comment by umair-ilyas** [comment]
Iam also facing the same issue. Do you find any solution?

Launching lib\main.dart on Chrome in debug mode...
Building application for the web...
Attempting to connect to browser instance..
Finished with error: Failed to establish connection with the application instance in Chrome.
This can happen if the websocket connection used by the web tooling is unabled to correctly establish a connection, for example due to a firewall.

**Comment by umair-ilyas** [comment]
> PS E:\VSCodeProject\quickstartgame> flutter run -d Chrome
> Launching lib\main.dart on Chrome in debug mode...
> Building application for the web... 124.5s
> Attempting to connect to browser instance..
> 303.0s (!)
> Failed to establish connection with the application instance in Chrome.
> This can happen if the websocket connection used by the web tooling is unabled to correctly establish a connection, for example due toa firewall.

Do you find any solution of it?
