### ISSUE TITLE
Failed to create client from connection profile. RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by PPCM** [hyperledger/composer#3970]
After a few hours of use and around 1 500 transactions, the following error is throw
```
Error: Failed to create client from connection profile. RangeError: Maximum call stack size exceeded
    at Function.createClient (/home/deploy/node_modules/composer-connector-hlfv1/lib/hlfconnectionmanager.js:247:28)
    at HLFConnectionManager.connect (/home/deploy/node_modules/composer-connector-hlfv1/lib/hlfconnectionmanager.js:467:51)
    at Promise.resolve.then.then (/home/deploy/node_modules/composer-common/lib/connectionprofilemanager.js:194:42)
    at <anonymous>
```
And no more connections are possible

## Context
For each transaction, a new `BusinessNetworkConnection` is made and connected. At the end, a disconnect is called.

## Possible Fix
Restart the application, but it is not a solution for production

**Comment by sstone1** [comment]
> For each transaction, a new BusinessNetworkConnection is made and connected. At the end, a disconnect is called.

**Comment by sstone1** [comment]
Valid bug, but connections should be held for the lifetime of the application (not per transaction), so marking as P3. Needs investigation to see if it lies in Composer code or Fabric code.
