### ISSUE TITLE
Cannot GET /auth/github

### ISSUE THREAD

**Issue by vivekamin** [hyperledger/composer#4061]
After updating Hyperledger 0.19.6, GitHub authentication redirection is not working on http://localhost:3000/auth/github

Result of `echo $COMPOSER_PROVIDERS` is perfect

## My Environment
* Version used: 0.19.6
* Environment name and version:Node v8.11.2, 
* Operating System and version (desktop or mobile): Mac OS

## Error Log

Unhandled error for request GET /auth/github: Error: Cannot GET /auth/github
    at raiseUrlNotFoundError (/usr/local/lib/node_modules/composer-rest-server/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:635:15
    at next (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/usr/local/lib/node_modules/composer-rest-server/node_modules/body-parser/lib/types/urlencoded.js:91:7)
Unhandled error for request GET /auth/github: Error: Cannot GET /auth/github
    at raiseUrlNotFoundError (/usr/local/lib/node_modules/composer-rest-server/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:635:15
    at next (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/usr/local/lib/node_modules/composer-rest-server/node_modules/body-parser/lib/types/urlencoded.js:91:7)

**Comment by bashimr** [comment]
Did you find the solution to this problem? How did you fix it?

**Comment by vivekamin** [comment]
@bashimr please check how are you exporting the $COMPOSER_PROVIDERS. If you are running using source you have to check whether you are using export or not. https://askubuntu.com/questions/205688/whats-the-difference-between-set-export-and-env-and-when-should-i-use-each
