### ISSUE TITLE
Error during the deployment of the REST server :  " SyntaxError: Unexpected end of JSON input "

### ISSUE THREAD

**Issue by maxgfr** [hyperledger/composer#4066]
Hello everyone,

## Context
I tried to follow this tutorial : https://hyperledger.github.io/composer/latest/integrating/deploying-the-rest-server

## Problem
At the end of the tutorial, I had an error when I launch `docker logs -f rest`  :

```shell
[2018-05-28 10:33:36] PM2 log: Starting execution sequence in -fork mode- for app name:composer-rest-server id:0
[2018-05-28 10:33:36] PM2 log: App name:composer-rest-server id:0 online
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Promise (/home/composer/.npm-global/lib/node_modules/composer-rest-server/server/server.js:53:32)
    at new Promise (<anonymous>)
    at module.exports (/home/composer/.npm-global/lib/node_modules/composer-rest-server/server/server.js:39:12)
    at module.exports.promise.then (/home/composer/.npm-global/lib/node_modules/composer-rest-server/cli.js:128:12)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
[2018-05-28 10:33:38] PM2 log: App [composer-rest-server] with id [0] and pid [2398], exited with code [1] via signal [SIGINT]
```

## Expected Behavior
The command `docker logs -f rest` should finish with `Browse your REST API at http://localhost:3000/explorer`

## Actual Behavior
Get the error as detailed above

## Possible Fix
I tried changing the permissions of ~/.composer by using the command below but it didn't change the output: `chmod -R 777 ~/.composer`

## My Environment
* composer-cli and composer-rest-server 0.19.6
* node 10.1.0

**Comment by maxgfr** [comment]
Ok thanks, I try with docker 8.0.0 and I have the same error.

I also try to run my network without docker thanks to this command : `composer-rest-server --card admin@my-network`
The output is  :
```shell
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Promise (/home/ubuntu/.nvm/versions/node/v8.0.0/lib/node_modules/composer-rest-server/server/server.js:53:32)
    at Promise (<anonymous>)
    at module.exports (/home/ubuntu/.nvm/versions/node/v8.0.0/lib/node_modules/composer-rest-server/server/server.js:39:12)
    at module.exports.promise.then (/home/ubuntu/.nvm/versions/node/v8.0.0/lib/node_modules/composer-rest-server/cli.js:128:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by davidkel** [comment]
@maxgfr Sorry when I said node 8, I meant the latest version of node 8 which is currently 8.11.2 I believe. Node 8.0.0 isn't supported. However looking at the code, I would say that you have set the `COMPOSER_DATASOURCES` environment variable incorrectly and it's that which is causing the error you are seeing.

**Comment by maxgfr** [comment]
Indeed, the problem provide of the JSON. 

To fix it, I create a file : datasources.json which contains COMPOSER_DATASOURCES

Then, I run :
```shell
export COMPOSER_CARD=admin@magma-network
export COMPOSER_NAMESPACES=never
export COMPOSER_AUTHENTICATION=false
export COMPOSER_MULTIUSER=false
export COMPOSER_DATASOURCES=$(<datasources.json)
```

**Comment by RainbowArea** [comment]
can you please provide the datasources.json  in here ?

**Comment by malengatiger** [comment]
seconded: what is in the datasources.json and where does it live?
