### ISSUE TITLE
composer-playground Error trying to enroll user 

### ISSUE THREAD

**Issue by yulong12** [hyperledger/composer#4143]
## when I click the connect now button ,there is something wrong with "Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: unsupported certificate purpose

## Context
 I use the connections file to connect fabric network with command line ,and it success.
now I want wo use composer-playground to create card and deployed,I fished create card according to my connections file,and deploy a business network,but when I click this connection now button,it is wrong

create card according to "Creating a peer admin card using Playground" in:
[https://hyperledger.github.io/composer/latest/playground/id-cards-playground](https://hyperledger.github.io/composer/latest/playground/id-cards-playground)

## Your Environment
docker :Version 18.05.0-ce-mac67 (25042)
mac:0.13.4 (17E202)

the composer-playground log is 
```
zhangyuongdeair:first-network zhangyulong$ composer-playground
info: [Hyperledger-Composer] :LoadModule               :loadModule()              Loading composer-wallet-filesystem from /Users/zhangyulong/.nvm/versions/node/v8.11.1/lib/node_modules/composer-playground/node_modules/composer-wallet-filesystem
info: [Hyperledger-Composer] :PlaygroundAPI            :createServer()            Playground API started on port 8080
info: [Hyperledger-Composer] :PlaygroundAPI            :createServer()            Client with ID 'dh2PXV-V_BgPaZ1oAAAA' on host '::1' connected
info: [Hyperledger-Composer] :PlaygroundAPI            :createServer()            Client with ID 'JTX2hz25BUzAeJdCAAAB' on host '::1' connected
info: [Hyperledger-Composer] :ConnectionProfileManager :getConnectionManagerByTyp Looking up a connection manager for type 0=hlfv1
info: [Hyperledger-Composer] :ConnectionProfileManager :getConnectionManagerByTyp Using this connection manager  
error: [Hyperledger-Composer] :HLFConnection            :enroll()                  Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: unsupported certificate purpose]
    at caClient.enroll.then.then.then.then.catch (/Users/zhangyulong/.nvm/versions/node/v8.11.1/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:220:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error: [Hyperledger-Composer] :HLFConnection            :login()                   Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: unsupported certificate purpose]
    at caClient.enroll.then.then.then.then.catch (/Users/zhangyulong/.nvm/versions/node/v8.11.1/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:220:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error: [Hyperledger-Composer] :ConnectorServer          :connectionLogin()         Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: unsupported certificate purpose]
    at client.getUserContext.then.then.catch (/Users/zhangyulong/.nvm/versions/node/v8.11.1/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:395:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
info: [Hyperledger-Composer] :ConnectionProfileManager :getConnectionManagerByTyp Looking up a connection manager for type 0=hlfv1
error: [Hyperledger-Composer] :HLFConnection            :enroll()                  Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: unsupported certificate purpose]
    at caClient.enroll.then.then.then.then.catch (/Users/zhangyulong/.nvm/versions/node/v8.11.1/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:220:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error: [Hyperledger-Composer] :HLFConnection            :login()                   Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: unsupported certificate purpose]
    at caClient.enroll.then.then.then.then.catch (/Users/zhangyulong/.nvm/versions/node/v8.11.1/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:220:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error: [Hyperledger-Composer] :ConnectorServer          :connectionLogin()         Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: unsupported certificate purpose]
    at client.getUserContext.then.then.catch (/Users/zhangyulong/.nvm/versions/node/v8.11.1/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:395:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by rthatcher** [comment]
This issue was raised due to some confusion about cards with a BYFN Fabric with Multi Orgs.  It has highlighted an inconsistency in Playground - but this particular issue is due to a misunderstanding of orgs and cards.
