### ISSUE TITLE
Composer network start error

### ISSUE THREAD

**Issue by Jithinqw** [hyperledger/composer#4343]
I am trying to install a network by 

composer network install --card PeerAdmin@hlfv1 --archiveFile perishable-network.bna 

and when ever I am starting the network by giving 

composer network start --card PeerAdmin@hlfv1 --networkName perishable-network --networkVersion 0.2.6 --networkAdmin admin -S adminpw --file networkAdmin.card
It gives me this error,
Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 2 UNKNOWN: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm WARN deprecated hoek@2.16.3: The major version is no longer supported.

Please help.

**Comment by davidkel** [comment]
Not enough info, is it the same as this one ?
#4344

**Comment by Jithinqw** [comment]
I try start a business network in Linux. Also, only occurs in composer 0.19.0 in Linux (with version 0.19.13 and HLF 1.1 ). I test it with the prishable-network example and using Hyperledger Fabric 1.2

 # Context
Using fabric-dev-servers project to HLF 1.1. 

# Expected Behavior

Should start business network

#Actual Behaviour
 composer network start --card PeerAdmin@hlfv1 --networkName perishable-network --networkVersion 0.2.6 --networkAdmin admin -S adminpw --file networkAdmin.card
Starting business network perishable-network at version 0.2.6

Processing these Network Admins: 
	userName: admin

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 2 UNKNOWN: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
npm WARN notice [SECURITY] hoek has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=hoek&version=2.16.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] hoek has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=hoek&version=2.16.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] protobufjs has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=protobufjs&version=5.0.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.6.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> x509@0.3.3 install /chaincode/output/node_modules/x509
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
gyp ERR! stack     at emitNone (events.js:106:13)
gyp ERR! stack     at TLSSocket.emit (events.js:208:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:637:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
gyp ERR! System Linux 4.15.0-32-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /chaincode/output/node_modules/x509
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN The package composer-common is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! x509@0.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the x509@0.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-21T04_47_53_941Z-debug.log
"
Command failed

#  Steps to Reproduce

 1.   Deploy dev server of HLF 1.2 using fabric-dev-servers (./startFabric.sh)
  2.  Create Peer Admin Card (./createPeerAdminCard.sh)
   3. Install business Network (composer network install -c PeerAdmin@hlfv1 -a dist/perishable-network.bna)
   4. Start business Network (composer network start --networkName tutorial-network --networkVersion 0.0.1 -A admin -S adminpw -c PeerAdmin@hlfv1)

# Environment

    Version used: Composer 0.19.0, Fabric 1.2
    Environment name and version: node 8.9.4, npm 5.4.0, docker 18.06.0-ce
    Operating System and version (desktop or mobile): Ubunutu 17

**Comment by Jithinqw** [comment]
#4344 is issue with version 0.20

**Comment by davidkel** [comment]
Composer 0.19 won't work with Fabric 1.2, you either need to use fabric 1.1 with composer 0.19 or composer 0.20 with Fabric 1.2

**Comment by Jithinqw** [comment]
I have downgraded my Fabric to 1.2 and still shows the same error.

**Comment by davidkel** [comment]
Looks like the error indicates that you cannot make an https connection to the npm registry from the chaincode image builder container. You would need to provide an appropriate .npmrc file when you install the business network that is relevant to your particular network setup in order to allow this to occur. The info about passing npmrc files can be found here
https://hyperledger.github.io/composer/latest/managing/connector-information
but I couldn't tell you what you would need, that is dependent on your network environment.

**Comment by Jithinqw** [comment]
In the .npmrc file,  have made strict-ssl=false and made registry as http from https. What all parameters I have to pass?

**Comment by Jithinqw** [comment]
I tried upgrading my hyperledger version to 
Version used: Composer 0.20.0, Fabric 1.2
Environment name and version: node 8.9.4, npm 5.4.0, docker 18.06.0-ce
Operating System and version (desktop or mobile): Ubunutu 17

I am still getting the following error

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: failed to execute transaction ead504cd41e62da8327a6bfc924530e9cd3fd3d74e4d45a6150286c3e1c434f6: error starting container: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.6.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] hoek has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=hoek&version=2.16.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> x509@0.3.3 install /chaincode/output/node_modules/x509
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
gyp ERR! stack     at emitNone (events.js:106:13)
gyp ERR! stack     at TLSSocket.emit (events.js:208:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:637:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
gyp ERR! System Linux 4.15.0-32-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /chaincode/output/node_modules/x509
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN The package composer-common is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! x509@0.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the x509@0.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-30T04_23_08_292Z-debug.log
"
Command failed

**Comment by andreasebire** [comment]
Hi,

I am running composer 0.2 fabric 1.2 it with npm 6.2 I had the same issue on a virtual box behind a company proxy. Configured the proxy in the virtual box network and now it is working.

I hope it can help

**Comment by jeydi243** [comment]
> Hi,
> 
> I am running composer 0.2 fabric 1.2 it with npm 6.2 I had the same issue on a virtual box behind a company proxy. Configured the proxy in the virtual box network and now it is working.
> 
> I hope it can help

@andreasebire can you please give us more details. am using VMware
