### ISSUE TITLE
composer network start error in OS X

### ISSUE THREAD

**Issue by benitojcv** [hyperledger/composer#4344]
I try start a business network in OS X platform and get an error. I have no problem in Linux. Also, only occurs in composer 0.20.0 in OSX (with version 0.19.13 and HLF 1.1 in OS X, its ok!). I test it with the tutorial-network example and using Hyperledger Fabric 1.2

## Context

Using fabric-dev-servers project updated to HLF 1.2. No problem in deploy HLF 1.2. No problem installing composer business network.

No problem in linux environment. It seems a bug in composer 0.20 in OS X

## Expected Behavior

Should start business network

## Actual Behavior

`$ composer network start --networkName tutorial-network --networkVersion 0.0.1 -A admin -S adminpw -c PeerAdmin@hlfv1
Starting business network tutorial-network at version 0.0.1

Processing these Network Admins: 
	userName: admin

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: failed to execute transaction 4f4097d1236108382e23383a80387f29c894483a11a7200f76a3caa73482963f: error starting container: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.6.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN notice [SECURITY] hoek has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=hoek&version=2.16.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> x509@0.3.3 install /chaincode/output/node_modules/x509
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.9.93-linuxkit-aufs
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /chaincode/output/node_modules/x509
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN tutorial-network@0.0.1 No repository field.
npm WARN The package composer-common is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! x509@0.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the x509@0.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-20T07_32_09_789Z-debug.log
"
Command failed
`

## Steps to Reproduce
1. Deploy dev server of HLF 1.2 using fabric-dev-servers (`./startFabric.sh`)
2. Create Peer Admin Card (`./createPeerAdminCard.sh`)
3. Create tutorial-network (`yo hyperledger-composer:businessnetwork`). See [Developer Tutorial](https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial).
4. Install business Network (`composer network install -c PeerAdmin@hlfv1 -a dist/tutorial-network.bna`)
5. Start business Network (`composer network start --networkName tutorial-network --networkVersion 0.0.1 -A admin -S adminpw -c PeerAdmin@hlfv1`)

## Existing issues

Almost this [issue](https://github.com/hyperledger/composer/issues/4343)?

## Your Environment

* Version used: Composer 0.20.0, Fabric 1.2
* Environment name and version: node 8.11.1, npm 6.4.0, docker 18.06.0-ce
* Operating System and version (desktop or mobile): OS X High Sierra (10.13.6)

**Comment by davidkel** [comment]
Fabric 1.2 has annoyingly changed how it references the `ccenv` docker image it uses to create chaincode container images. It looks like you have an old version of this image which it is using. you need to remove this image by doing
```
docker rmi hyperledger/fabric-ccenv:latest
```

**Comment by benitojcv** [comment]
Perfect. It is already solved!

Thanks!

**Comment by A1kartikey** [comment]
Actually, I am also having the same issues but I did not understand the solution, can you please explain a bit more.

**Comment by benitojcv** [comment]
Hi @A1kartikey ,

Following instructions of @davidkel , I checked my docker images and saw a lot of versions of docker image `hyperledger/fabric-ccenv`. How I am in development environment, I decided reinitialize docker service to factory defaults. That cleans all images! Then run my proyect again and it worked!

I hope I've helped

**Comment by Monclee** [comment]
@benitojcv how do you reinitialize docker service to factory defaults?

**Comment by benitojcv** [comment]
In Docker for Mac is really simple. Select -> Preferences from the menu bar, then click Reset to reset factory defaults.
In Linux, you always can reinstall docker.

**Comment by jack-solutions** [comment]
> Perfect. It is already solved!
> 
> Thanks!

hey @benitojcv  how you have solved this issue please tell me i am facing the issue from several days tried many ways but no luck

**Comment by adidhn** [comment]
> Perfect. It is already solved!
> 
> Thanks!

hey @benitojcv how you solved this issue please tell me i am facing this issue from several days and tried many ways but no luck

**Comment by benitojcv** [comment]
Hello,

I explanined it in post. just keep reading. 

Enviado desde mi iPhone
