### ISSUE TITLE
Connection fails: MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongo mongo:27017]

### ISSUE THREAD

**Issue by parismollo** [hyperledger/composer#4357]
## Context
Following this tutorial:  https://hyperledger.github.io/composer/latest/integrating/deploying-the-rest-server

## Expected Behavior
After running:
`docker run \
    -d \
    -e COMPOSER_CARD=${COMPOSER_CARD} \
    -e COMPOSER_NAMESPACES=${COMPOSER_NAMESPACES} \
    -e COMPOSER_AUTHENTICATION=${COMPOSER_AUTHENTICATION} \
    -e COMPOSER_MULTIUSER=${COMPOSER_MULTIUSER} \
    -e COMPOSER_PROVIDERS="${COMPOSER_PROVIDERS}" \
    -e COMPOSER_DATASOURCES="${COMPOSER_DATASOURCES}" \
    -v ~/.composer:/home/composer/.composer \
    --name rest \
    --network composer_default \
    -p 3000:3000 \
    myorg/my-composer-rest-server`

The output from the command : 
`docker logs -f rest` 
should be something like this :
 `Browse your REST API at http://localhost:3000/explorer`

## Actual Behavior
Connection fails: MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongo mongo:27017]
It will be retried for the next request.
MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongo mongo:27017]
    at Pool.<anonymous> (/home/composer/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/home/composer/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/home/composer/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at args.(anonymous function) (/home/composer/.npm-global/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:133:29)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

## Possible Fix
I believe that there is something to do with the envvars.txt file in MongoDB parameter. 

### dock ps 
`CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                      NAMES
2022ef22f4ae        wcu/wcu-composer-rest-server   "pm2-docker composer…"   7 minutes ago       Up 7 minutes        0.0.0.0:3000->3000/tcp     rest
75ce0520ce86        mongo                          "docker-entrypoint.s…"   13 minutes ago      Up 13 minutes       0.0.0.0:27017->27017/tcp`

### dockerfiile 

FROM hyperledger/composer-rest-server:0.19.14
RUN npm install --production loopback-connector-mongodb passport-github && \
    npm cache clean --force && \
    ln -s node_modules .node_modules

### envvars.txt file 

`COMPOSER_CARD=admin@xxxxx
COMPOSER_NAMESPACES=never
COMPOSER_AUTHENTICATION=false
COMPOSER_MULTIUSER=false
COMPOSER_PROVIDERS='{
    "github": {
        "provider": "github",
        "module": "passport-github",
        "clientID": "REPLACE_WITH_CLIENT_ID",
        "clientSecret": "REPLACE_WITH_CLIENT_SECRET",
        "authPath": "/auth/github",
        "callbackURL": "/auth/github/callback",
        "successRedirect": "/",
        "failureRedirect": "/"
    }
}'
COMPOSER_DATASOURCES='{
    "db": {
        "name": "db",
        "connector": "mongodb",
        "host": "mongo"
    }
}'
`

Someone know's what modification i can make for resolving this isssue ?

**Comment by parismollo** [comment]
I'm closing the issue because I figure it out a solution...not sure is the best one but:
`}'
COMPOSER_DATASOURCES='{
    "db": {
        "name": "db",
        "connector": "memory",
        "host": "mongo"
    }
}'
`
I replace the connector value with "memory" and not mongodb
