### ISSUE TITLE
composer --help SyntaxError: Unexpected identifier 

### ISSUE THREAD

**Issue by siddjain** [hyperledger/composer#4462]
I installed composer-cli suing below command
```
sudo npm install -g composer-cli
```
and get this error when I try to run `composer --help`
```
$ composer --help
/usr/lib/node_modules/composer-cli/node_modules/composer-common/lib/cardstore/businessnetworkcardstore.js:54
    async get(cardName) {
          ^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/composer-cli/node_modules/composer-common/index.js:56:43)
```

## Expected Behavior
It should show help screen

## Actual Behavior
```
$ composer --help
/usr/lib/node_modules/composer-cli/node_modules/composer-common/lib/cardstore/businessnetworkcardstore.js:54
    async get(cardName) {
          ^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/composer-cli/node_modules/composer-common/index.js:56:43)
```

## Your Environment
Ubuntu

**Comment by davidkel** [comment]
You are using the wrong version of node. You need to be using node 8. Currently Node 8.12.0 is the latest version so please install `nvm` as per our installation guide (remove any previous installation of node you might have done via you linux repo package manager for example).
https://hyperledger.github.io/composer/latest/installing/installing-prereqs.html

**Comment by jcjollant** [comment]
> You are using the wrong version of node. You need to be using node 8. Currently Node 8.12.0 is the latest version so please install `nvm` as per our installation guide (remove any previous installation of node you might have done via you linux repo package manager for example).
> https://hyperledger.github.io/composer/latest/installing/installing-prereqs.html

This ought to be mentioned in EdX MOOC as right now it clearly states 6 is required.
