### ISSUE TITLE
Syntax Error when start composer rest server

### ISSUE THREAD

**Issue by tuanp703** [hyperledger/composer#4506]
I am keep getting the error below when attempt to start the composer rest server. The bna and the playground both run normally and everything else seems to be working. 

Not sure what is going on here.  I am running hlfv 1.2 with 0.2 composer. Thanks for your help.

cx@ubuntu:~/fabric-dev-servers$ composer-rest-server
/home/cx/.nvm/versions/node/v8.12.0/lib/node_modules/composer-rest-server/node_modules/bluebird/js/release/finally.js:1
(function (exports, require, module, __filename, __dirname) {

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at module.exports (/home/cx/.nvm/versions/node/v8.12.0/lib/node_modules/composer-rest-server/node_modules/bluebird/js/release/promise.js:55:5)
    at Object.<anonymous> (/home/cx/.nvm/versions/node/v8.12.0/lib/node_modules/composer-rest-server/node_modules/bluebird/js/release/bluebird.js:9:36)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
cx@ubuntu:~/fabric-dev-servers$

**Comment by tuanp703** [comment]
I verified that I have composer-rest-server installed v.20.4

cx@ubuntu:~/fabric-dev-servers$ npm install -g composer-rest-server
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN deprecated swagger-ui@2.2.10: No longer maintained, please upgrade to swagger-ui@3.
/home/cx/.nvm/versions/node/v8.12.0/bin/composer-rest-server -> /home/cx/.nvm/versions/node/v8.12.0/lib/node_modules/composer-rest-server/cli.js
+ composer-rest-server@0.20.4
updated 1 package in 17.207s
cx@ubuntu:~/fabric-dev-servers$ composer-rest-server --version
/home/cx/.nvm/versions/node/v8.12.0/lib/node_modules/composer-rest-server/node_modules/bluebird/js/release/finally.js:1
(function (exports, require, module, __filename, __dirname) {


SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at module.exports (/home/cx/.nvm/versions/node/v8.12.0/lib/node_modules/composer-rest-server/node_modules/bluebird/js/release/promise.js:55:5)
    at Object.<anonymous> (/home/cx/.nvm/versions/node/v8.12.0/lib/node_modules/composer-rest-server/node_modules/bluebird/js/release/bluebird.js:9:36)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
cx@ubuntu:~/fabric-dev-servers$

**Comment by tuanp703** [comment]
I reinstalled all components and was able to address the issue.
