### ISSUE TITLE
Error while creating the channel for kafka implementation. 

### ISSUE THREAD

**Issue by dattajadhav44** [hyperledger/composer#4548]
HI Team, I am facing an error while creating the channel for the kakfa implementation. My network has Org1, 5peer,3orderer, 3zookeeper and 4brokers but i am getting below error while creating the channel. 

can someone please suggest. 

[2018-12-12 12:47:53.727] [ERROR] Join-Channel - Error: "orderer" request parameter is missing and there are no orderers defined on this channel in the network configuration
    at Client.getTargetOrderer (/home/djadhav/Desktop/Blockchain/ncb-2.0-app_old/node_modules/fabric-client/lib/Client.js:1668:12)
    at Channel.getGenesisBlock (/home/djadhav/Desktop/Blockchain/ncb-2.0-app_old/node_modules/fabric-client/lib/Channel.js:1041:39)
    at Object.joinChannel (/home/djadhav/Desktop/Blockchain/ncb-2.0-app_old/app/join-channel.js:46:37)
    at <anonymous>
[2018-12-12 12:47:53.727] [ERROR] Join-Channel - Failed to join all peers to channel. cause:Error: "orderer" request parameter is missing and there are no orderers defined on this channel in the network configuration
(node:16563) UnhandledPromiseRejectionWarning: Error: Failed to join all peers to channel. cause:Error: "orderer" request parameter is missing and there are no orderers defined on this channel in the network configuration

**Comment by sstone1** [comment]
@dattajadhav44 this is a Fabric question, not a Composer question... please raise this in the Fabric community instead.
