### ISSUE TITLE
Composer Network fails to start

### ISSUE THREAD

**Issue by venkyt2411** [hyperledger/composer#4575]
Overview:
I am trying to learn blockchain development basics using the resource
https://medium.freecodecamp.org/how-to-build-a-blockchain-network-using-hyperledger-fabric-and-composer-e06644ff801d
Composer version: v0.20.6
## Context
I completed all the steps till composer network start without any error. When I try to start the network I get below error:
composer network start --networkName cards-trading-network --networkVersion 0.0.1 --networkAdmin admin --networkAdminEnrollSecret adminpw --card PeerAdmin@hlfv1 --file cards-trading-admin.card
Starting business network cards-trading-network at version 0.0.1

Processing these Network Admins: 
	userName: admin

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: REQUEST_TIMEOUT
Command failed

I also checked docker logs and see belwo error:
docker logs dev-peer0.org1.example.com-cards-trading-network-0.0.1
2019-01-18T13:05:02.355Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Asset:org.hyperledger.composer.system.AssetRegistry' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.378Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Asset:org.hyperledger.composer.system.ParticipantRegistry' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.398Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Asset:org.hyperledger.composer.system.TransactionRegistry' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.415Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Participant:org.hyperledger.composer.system.NetworkAdmin' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.434Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Asset:org.hyperledger.composer.system.HistorianRecord' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.453Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Transaction:org.hyperledger.composer.system.AddAsset' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.474Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Transaction:org.hyperledger.composer.system.UpdateAsset' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.515Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Transaction:org.hyperledger.composer.system.RemoveAsset' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.536Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Transaction:org.hyperledger.composer.system.AddParticipant' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.588Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Transaction:org.hyperledger.composer.system.UpdateParticipant' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.607Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Transaction:org.hyperledger.composer.system.RemoveParticipant' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.632Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Asset:org.hyperledger.composer.system.Identity' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.659Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Transaction:org.hyperledger.composer.system.IssueIdentity' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.680Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Transaction:org.hyperledger.composer.system.BindIdentity' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.700Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Transaction:org.hyperledger.composer.system.ActivateCurrentIdentity' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.723Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Transaction:org.hyperledger.composer.system.RevokeIdentity' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.742Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Transaction:org.hyperledger.composer.system.StartBusinessNetwork' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.761Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Transaction:org.hyperledger.composer.system.ResetBusinessNetwork' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.779Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Transaction:org.hyperledger.composer.system.SetLogLevel' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.805Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Asset:org.example.biznet.TradingCard' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.831Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Participant:org.example.biznet.Trader' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.856Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'Transaction:org.example.biznet.TradeCard' in collection with ID '$sysregistries' does not exist
2019-01-18T13:05:02.896Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'org.hyperledger.composer.system.NetworkAdmin' in collection with ID 'Asset:org.hyperledger.composer.system.ParticipantRegistry' does not exist
2019-01-18T13:05:02.897Z ERROR    :Resolver                 :resolveRelationship()     Failed to resolve relationship {"stack":["{Error}Object with ID 'org.hyperledger.composer.system.NetworkAdmin' in collection with ID 'Asset:org.hyperledger.composer.system.ParticipantRegistry' does not exist Error: Object with ID 'org.hyperledger.composer.system.NetworkAdmin' in collection with ID 'Asset:org.hyperledger.composer.system.ParticipantRegistry' does not exist","    at NodeDataCollection.get (/usr/local/src/node_modules/composer-runtime-hlfv1/lib/nodedatacollection.js:73:28)","    at <anonymous>","    at process._tickCallback (internal/process/next_tick.js:188:7)"]}
2019-01-18T13:05:02.942Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'admin' in collection with ID 'Participant:org.hyperledger.composer.system.NetworkAdmin' does not exist
2019-01-18T13:05:02.942Z ERROR    :Resolver                 :resolveRelationship()     Failed to resolve relationship {"stack":["{Error}Object with ID 'admin' in collection with ID 'Participant:org.hyperledger.composer.system.NetworkAdmin' does not exist Error: Object with ID 'admin' in collection with ID 'Participant:org.hyperledger.composer.system.NetworkAdmin' does not exist","    at NodeDataCollection.get (/usr/local/src/node_modules/composer-runtime-hlfv1/lib/nodedatacollection.js:73:28)","    at <anonymous>","    at process._tickCallback (internal/process/next_tick.js:188:7)"]}
2019-01-18T13:05:03.002Z ERROR    :NodeDataCollection       :get()                     Error: Object with ID 'org.hyperledger.composer.system.NetworkAdmin' in collection with ID 'Asset:org.hyperledger.composer.system.ParticipantRegistry' does not exist
2019-01-18T13:05:03.002Z ERROR    :Resolver                 :resolveRelationship()     Failed to resolve relationship {"stack":["{Error}Object with ID 'org.hyperledger.composer.system.NetworkAdmin' in collection with ID 'Asset:org.hyperledger.composer.system.ParticipantRegistry' does not exist Error: Object with ID 'org.hyperledger.composer.system.NetworkAdmin' in collection with ID 'Asset:org.hyperledger.composer.system.ParticipantRegistry' does not exist","    at NodeDataCollection.get (/usr/local/src/node_modules/composer-runtime-hlfv1/lib/nodedatacollection.js:73:28)","    at <anonymous>","    at process._tickCallback (internal/process/next_tick.js:188:7)"]}

What could be the reason for this error ? 

## Expected Behavior
composer network start command should run without any error

## Actual Behavior
composer network fails to start 

## Possible Fix
Yet to be identified

## Steps to Reproduce
Follow the url  https://medium.freecodecamp.org/how-to-build-a-blockchain-network-using-hyperledger-fabric-and-composer-e06644ff801d

## Existing issues
https://github.com/hyperledger/composer/issues/3731

## Context
I am stuck at this step and unable to proceed since composer network unable to start

## Your Environment

* Version used: composer v0.20.6
* Environment name and version :Docker version 18.09.1, build 4c52b90
* Operating System and version (desktop or mobile): Ubuntu 16.04 amd64
* Link to your project: https://medium.freecodecamp.org/how-to-build-a-blockchain-network-using-hyperledger-fabric-and-composer-e06644ff801d

**Comment by venkyt2411** [comment]
Hi All,

I was able to solve the above issue by adding below in permission.acl and I understand this issue is related to permissions.

rule GrantSysAccess {

     description: "Grant access to all Participants to target system registries"

     participant: "org.hyperledger.composer.system.Participant"

     operation: ALL

     resource: "org.hyperledger.composer.system.**"

     action: ALLOW

   }

After adding this i restarted fabric, generated BNY archive file , installed network and started. Network started without any error this time:
composer network start --networkName cards-trading-network --networkVersion 0.0.1 --networkAdmin admin --networkAdminEnrollSecret adminpw --card PeerAdmin@hlfv1 --file cards-trading-admin.card
Starting business network cards-trading-network at version 0.0.1

Processing these Network Admins: 
	userName: admin

✔ Starting business network definition. This may take a minute...
Successfully created business network card:
	Filename: cards-trading-admin.card

Command succeeded

**Comment by anujpahade** [comment]
@venkyt2411  I have the same issue. Did you find any solution? I tried setting the timeout to 1200s as mentioned [here](https://github.com/hyperledger/composer-knowledge-wiki/blob/latest/knowledge.md#startissues) But it does not solve my problem. 
I have the same rule in my permissions.acl But it still does not work.

**Comment by pierre-dlsi** [comment]
I got a similar issue, a REQUEST_TIMEOUT error trying to start a bussines network. Im my case, I try to deploy the network on a Fabric instance like the one in fabric-dev-servers (one orderer, one peer, one ca, everyone in the same organization/same machine). 

The problem is that a fabric:ccenv container is launched to build the chaincode, executing a 'npm install' command. This container is, for some unknown reason, launched on a different docker network ('bridge' network) than the rest of Fabric containers (composer_default). This network has no internet access (at least in my machine, running Ubuntu 18.04.1 on a VMWare instance), so 'npm install' gets stuck.

Apparently, this doesn't happen when installing chaincode natively (i.e., using 'peer chaincode instantiate') as the fabric-samples/first-network example from the Fabric site does.

Running the same scenario on other machines works fine, so I'm not sure this is a composer issue or a docker/VM configuration issue.

**Comment by anujpahade** [comment]
@pierre-dlsi When I run `docker ps` after the `./startFabric.sh`  command I see 4 docker containers: peer, orderer, ca, couchdb
I cannot see a ccenv container. Where can I see that? And how do we have internet enabled for it?

**Comment by pierre-dlsi** [comment]
@anujpahade You have to install ('_composeer network install_...') a bussiness network, then start it ('_composer network start_...'). This 'start' step launches a _ccenv_ container that builds your chaincode. Here is where i got the timeout error. I'm no docker expert, so I don't know how to enable internet access for a container.

Anyway, that container should be on the same network as the rest of containers. This is the normal behaviour, but in some VM instances I got the timeout error.

**Comment by anujpahade** [comment]
@pierre-dlsi  I have found a [solution](https://github.com/hyperledger/composer/issues/3731#issuecomment-387600862)

**Comment by pierre-dlsi** [comment]
Thanks, @anujpahade! I'm trying that solution, but don't know which address to put in the npmConfig.txt file:

    registry=http://xxxxx:4873/

 which IP address goes there?? I tried several possible ips, including the npmregistry container address... to no avail. However, now the error I get is different:

> ✖ Starting business network definition. This may take a minute...
> Error: Error trying to start business network. Error: No valid responses from any peers.
> Response from attempted peer comms was an error: Error: error starting container: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code E500
> npm ERR! 500 Internal Server Error: composer-common@0.20.7
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-02-15T16_50_04_352Z-debug.log
> "
> 

Unfortunately, the ccenv container was shutdown after the error, so I can't see the above npm log. 

Any further insights on this would be greatly appreciated!!

**Comment by anujpahade** [comment]
I put `registry=http://localhost:4873/`
Try that
