### ISSUE TITLE
enrollment failed with error

### ISSUE THREAD

**Issue by SirisetyManeela** [hyperledger/composer#4599]
Store path:/home/maneela/.hfc-key-store
Error: Enrollment failed with errors [[{"code":19,"message":"CA 'ca.example.com' does not exist"}]]
    at IncomingMessage.<anonymous> (/home/maneela/education/LFS171x/fabric-material/tuna-app/node_modules/fabric-ca-client/lib/FabricCAClientImpl.js:698:22)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
Failed to enroll admin: Error: Failed to enroll admin

i tried rm -rf .hfc-key-store/
but it is still not working

**Comment by Kevin-Kinyua** [comment]
I attempted to downgrade my npm and node to 5.6.0 and v8.9.0 respectively, however this did not change the error.

**Comment by davidkel** [comment]
This doesn't look like it is related to composer, so closing
