### ISSUE TITLE
Installing composer-cli@0.19

### ISSUE THREAD

**Issue by yehia67** [hyperledger/composer#4660]
Hey,
I am trying to install composer using command
```
npm install -g composer-cli@0.19
```
node version: v10.15.1
npm version: 6.9.0

but it give me this error:

```
npm WARN deprecated core-js@2.3.0: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
/home/yehia/.nvm/versions/node/v10.15.1/bin/composer -> /home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/cli.js

> dtrace-provider@0.8.7 install /home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

make: Entering directory '/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory '/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/dtrace-provider/build'

> node-report@2.2.1 install /home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/node-report
> node-gyp rebuild

make: Entering directory '/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/node-report/build'
  CXX(target) Release/obj.target/api/src/node_report.o
  CXX(target) Release/obj.target/api/src/module.o
  CXX(target) Release/obj.target/api/src/utilities.o
  SOLINK_MODULE(target) Release/obj.target/api.node
  COPY Release/api.node
  COPY /home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/node-report/api.node
  TOUCH Release/obj.target/install.stamp
make: Leaving directory '/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/node-report/build'

> pkcs11js@1.0.18 install /home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/pkcs11js
> node-gyp rebuild

make: Entering directory '/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/pkcs11js/build'
  CXX(target) Release/obj.target/pkcs11/src/main.o
  CXX(target) Release/obj.target/pkcs11/src/dl.o
  CXX(target) Release/obj.target/pkcs11/src/const.o
  CXX(target) Release/obj.target/pkcs11/src/pkcs11/error.o
  CXX(target) Release/obj.target/pkcs11/src/pkcs11/v8_convert.o
  CXX(target) Release/obj.target/pkcs11/src/pkcs11/template.o
  CXX(target) Release/obj.target/pkcs11/src/pkcs11/mech.o
  CXX(target) Release/obj.target/pkcs11/src/pkcs11/param.o
  CXX(target) Release/obj.target/pkcs11/src/pkcs11/param_aes.o
  CXX(target) Release/obj.target/pkcs11/src/pkcs11/param_rsa.o
  CXX(target) Release/obj.target/pkcs11/src/pkcs11/param_ecdh.o
  CXX(target) Release/obj.target/pkcs11/src/pkcs11/pkcs11.o
  CXX(target) Release/obj.target/pkcs11/src/async.o
  CXX(target) Release/obj.target/pkcs11/src/node.o
  SOLINK_MODULE(target) Release/obj.target/pkcs11.node
  COPY Release/pkcs11.node
make: Leaving directory '/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/pkcs11js/build'

> grpc@1.10.1 install /home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.10.1/node-v64-linux-x64-glibc.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.10.1 and node@10.15.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Pre-built binaries not installable for grpc@1.10.1 and node@10.15.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Hit error Connection closed while downloading tarball file 
make: Entering directory '/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
make: Entering directory '/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
rm: cannot remove './Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw': No such file or directory
grpc.target.mk:394: recipe for target 'Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o' failed
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1
make: Leaving directory '/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-50-generic
gyp ERR! command "/home/yehia/.nvm/versions/node/v10.15.1/bin/node" "/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
gyp ERR! cwd /home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/grpc
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/yehia/.nvm/versions/node/v10.15.1/bin/node /home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.15.0-50-generic
node-pre-gyp ERR! command "/home/yehia/.nvm/versions/node/v10.15.1/bin/node" "/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/grpc
node-pre-gyp ERR! node -v v10.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.7.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/yehia/.nvm/versions/node/v10.15.1/bin/node /home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.oe
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o
make: *** No rule to make target '../deps/grpc/src/core/lib/channel/channel_stack.cc', needed by 'Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.o'.  Stop.
make: Leaving directory '/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/grpc/build'
gyp ERR! build error | install: info lifecycle grpc@1.10.1~install: Failed to e
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-50-generic
gyp ERR! command "/home/yehia/.nvm/versions/node/v10.15.1/bin/node" "/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
gyp ERR! cwd /home/yehia/.nvm/versions/node/v10.15.1/lib/node_modules/composer-cli/node_modules/grpc
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/composer-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.10.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yehia/.npm/_logs/2019-06-08T13_41_39_950Z-debug.log
```

```

**Comment by davidkel** [comment]
Composer 0.19 and 0.20 only work with Node 8 and will not work with any higher version of node.
