### ISSUE TITLE
Error: Error trying to start business network. Error: No valid responses from any peers. Response from attempted peer comms was an error: Error: REQUEST_TIMEOUT

### ISSUE THREAD

**Issue by zhaizhonghao** [hyperledger/composer#4673]
I follow the steps 

> Deploying a Business Network to a real Fabric.

 from https://hyperledger.github.io/composer/latest/tutorials/playground-tutorial.html, trying to deploy the BNA using composer-playground locally, but after clicking the deploy button, I waited for a long time and it failed to start.
## Context

**the error is** :
 Error: Error trying to start business network. Error: No valid responses from any peers. Response from attempted peer comms was an error: Error: REQUEST_TIMEOUT
**the log from composer-playground is** 
info attempt registry request try #1 at 15:50:24
http request GET https://api.npms.io/v2/search?q=keywords:composer-network+maintainer:hyperledger-ci
info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:45631
info attempt registry request try #2 at 15:50:26
http request GET https://api.npms.io/v2/search?q=keywords:composer-network+maintainer:hyperledger-ci
info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:45631
info attempt registry request try #3 at 15:50:31
http request GET https://api.npms.io/v2/search?q=keywords:composer-network+maintainer:hyperledger-ci
2019-07-15T07:50:31.681Z ERROR   :NPM                      :getSampleNames()          {"message":"tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:45631","stack":"Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:45631\n    at ClientRequest.onError (/home/zhai/.nvm/versions/node/v8.16.0/lib/node_modules/composer-playground/node_modules/tunnel-agent/index.js:177:17)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at ClientRequest.emit (events.js:211:7)\n    at Socket.socketErrorListener (_http_client.js:401:9)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:66:8)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickCallback (internal/process/next_tick.js:181:9)","code":"ECONNRESET"}$
2019-07-15T07:53:43.236Z INFO    :ConnectionProfileManager :getConnectionManagerByTyp Looking up a connection manager for type {"0":"hlfv1"}$
2019-07-15T07:53:43.383Z INFO    :HLFConnection            :constructor()             Creating a connection using profile fabric-network to fabric (no business network) {}$
2019-07-15T07:53:43.383Z INFO    :HLFConnection            :createQueryHandler()      attemping to load query handler module ./hlfqueryhandler {}$
2019-07-15T07:53:44.360Z INFO    :ConnectionProfileManager :getConnectionManagerByTyp Looking up a connection manager for type {"0":"hlfv1"}$
2019-07-15T07:53:44.376Z INFO    :HLFConnection            :constructor()             Creating a connection using profile fabric-network to fabric (no business network) {}$
2019-07-15T07:53:44.377Z INFO    :HLFConnection            :createQueryHandler()      attemping to load query handler module ./hlfqueryhandler {}$
2019-07-15T07:58:44.639Z ERROR   :HLFConnectionManager     :fabric-client()           [Peer.js]: sendProposal - timed out after:300000 {}$
2019-07-15T07:58:44.640Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/zhai/.nvm/versions/node/v8.16.0/lib/node_modules/composer-playground/node_modules/fabric-client/lib/Peer.js:94:20)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) {}$
2019-07-15T07:58:44.641Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: REQUEST_TIMEOUT {}$
2019-07-15T07:58:44.642Z ERROR   :HLFConnection            :start()                   {"message":"No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: REQUEST_TIMEOUT","stack":"Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: REQUEST_TIMEOUT\n    at HLFConnection._validatePeerResponses (/home/zhai/.nvm/versions/node/v8.16.0/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:855:19)\n    at HLFConnection._sendTransaction (/home/zhai/.nvm/versions/node/v8.16.0/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:778:37)\n    at HLFConnection.start (/home/zhai/.nvm/versions/node/v8.16.0/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:756:24)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)"}$
2019-07-15T07:58:44.642Z ERROR   :ConnectorServer          :connectionStart()         {"message":"Error trying to start business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: REQUEST_TIMEOUT","stack":"Error: Error trying to start business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: REQUEST_TIMEOUT\n    at HLFConnection.start (/home/zhai/.nvm/versions/node/v8.16.0/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:758:30)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)"}$
## Expected Behavior

It should start the BNA as I did using composer-playground online.
## Actual Behavior

It failed to start.
## Possible Fix

I have no idea, but there is a similar issue that has not been solved in https://github.com/hyperledger/composer/issues/4634
## Steps to Reproduce

steps in [Playground Tutorial](https://hyperledger.github.io/composer/latest/tutorials/playground-tutorial.html)

## Existing issues

- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues/4634)

## Context

I can't create the admin card which make me stop my studying.
## Your Environment

* Version used: Fabric v1.2
* Environment name and version:
node -v
v8.16.0
npm -v
6.4.1
docker -v
18.09.7
composer -v
v0.20.8
* Operating System and version: unbuntu 16.04 VM in visualbox

**Comment by ashbringerf** [comment]
have same problem tried 3 VM instances, and 1 actual ubuntu 1604 system, followed every step and the ./startFabric.sh is started and docker ps is updated, but it keeps saying 
✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: REQUEST_TIMEOUT
Command failed

cost me 3 days

**Comment by ashbringerf** [comment]
> I follow the steps
> 
> > Deploying a Business Network to a real Fabric.
> 
> from https://hyperledger.github.io/composer/latest/tutorials/playground-tutorial.html, trying to deploy the BNA using composer-playground locally, but after clicking the deploy button, I waited for a long time and it failed to start.
> ## Context
> 
> **the error is** :
> Error: Error trying to start business network. Error: No valid responses from any peers. Response from attempted peer comms was an error: Error: REQUEST_TIMEOUT
> **the log from composer-playground is**
> info attempt registry request try #1 at 15:50:24
> http request GET https://api.npms.io/v2/search?q=keywords:composer-network+maintainer:hyperledger-ci
> info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:45631
> info attempt registry request try #2 at 15:50:26
> http request GET https://api.npms.io/v2/search?q=keywords:composer-network+maintainer:hyperledger-ci
> info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:45631
> info attempt registry request try #3 at 15:50:31
> http request GET https://api.npms.io/v2/search?q=keywords:composer-network+maintainer:hyperledger-ci
> 2019-07-15T07:50:31.681Z ERROR :NPM :getSampleNames() {"message":"tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:45631","stack":"Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:45631\n at ClientRequest.onError (/home/zhai/.nvm/versions/node/v8.16.0/lib/node_modules/composer-playground/node_modules/tunnel-agent/index.js:177:17)\n at Object.onceWrapper (events.js:315:30)\n at emitOne (events.js:116:13)\n at ClientRequest.emit (events.js:211:7)\n at Socket.socketErrorListener (_http_client.js:401:9)\n at emitOne (events.js:116:13)\n at Socket.emit (events.js:211:7)\n at emitErrorNT (internal/streams/destroy.js:66:8)\n at _combinedTickCallback (internal/process/next_tick.js:139:11)\n at process._tickCallback (internal/process/next_tick.js:181:9)","code":"ECONNRESET"}$
> 2019-07-15T07:53:43.236Z INFO :ConnectionProfileManager :getConnectionManagerByTyp Looking up a connection manager for type {"0":"hlfv1"}$
> 2019-07-15T07:53:43.383Z INFO :HLFConnection :constructor() Creating a connection using profile fabric-network to fabric (no business network) {}$
> 2019-07-15T07:53:43.383Z INFO :HLFConnection :createQueryHandler() attemping to load query handler module ./hlfqueryhandler {}$
> 2019-07-15T07:53:44.360Z INFO :ConnectionProfileManager :getConnectionManagerByTyp Looking up a connection manager for type {"0":"hlfv1"}$
> 2019-07-15T07:53:44.376Z INFO :HLFConnection :constructor() Creating a connection using profile fabric-network to fabric (no business network) {}$
> 2019-07-15T07:53:44.377Z INFO :HLFConnection :createQueryHandler() attemping to load query handler module ./hlfqueryhandler {}$
> 2019-07-15T07:58:44.639Z ERROR :HLFConnectionManager :fabric-client() [Peer.js]: sendProposal - timed out after:300000 {}$
> 2019-07-15T07:58:44.640Z ERROR :HLFConnectionManager :fabric-client() [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT
> at Timeout._onTimeout (/home/zhai/.nvm/versions/node/v8.16.0/lib/node_modules/composer-playground/node_modules/fabric-client/lib/Peer.js:94:20)
> at ontimeout (timers.js:498:11)
> at tryOnTimeout (timers.js:323:5)
> at Timer.listOnTimeout (timers.js:290:5) {}$
> 2019-07-15T07:58:44.641Z WARN :HLFConnection :_validatePeerResponses() Response from attempted peer comms was an error: Error: REQUEST_TIMEOUT {}$
> 2019-07-15T07:58:44.642Z ERROR :HLFConnection :start() {"message":"No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: REQUEST_TIMEOUT","stack":"Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: REQUEST_TIMEOUT\n at HLFConnection._validatePeerResponses (/home/zhai/.nvm/versions/node/v8.16.0/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:855:19)\n at HLFConnection._sendTransaction (/home/zhai/.nvm/versions/node/v8.16.0/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:778:37)\n at HLFConnection.start (/home/zhai/.nvm/versions/node/v8.16.0/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:756:24)\n at \n at process._tickCallback (internal/process/next_tick.js:189:7)"}$
> 2019-07-15T07:58:44.642Z ERROR :ConnectorServer :connectionStart() {"message":"Error trying to start business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: REQUEST_TIMEOUT","stack":"Error: Error trying to start business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: REQUEST_TIMEOUT\n at HLFConnection.start (/home/zhai/.nvm/versions/node/v8.16.0/lib/node_modules/composer-playground/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:758:30)\n at \n at process._tickCallback (internal/process/next_tick.js:189:7)"}$
> ## Expected Behavior
> 
> It should start the BNA as I did using composer-playground online.
> ## Actual Behavior
> 
> It failed to start.
> ## Possible Fix
> 
> I have no idea, but there is a similar issue that has not been solved in #4634
> ## Steps to Reproduce
> 
> steps in [Playground Tutorial](https://hyperledger.github.io/composer/latest/tutorials/playground-tutorial.html)
> ## Existing issues
> 
>     * [ ]  [GitHub Issues](https://github.com/hyperledger/composer/issues/4634)
> 
> 
> ## Context
> 
> I can't create the admin card which make me stop my studying.
> ## Your Environment
> 
>     * Version used: Fabric v1.2
> 
>     * Environment name and version:
>       node -v
>       v8.16.0
>       npm -v
>       6.4.1
>       docker -v
>       18.09.7
>       composer -v
>       v0.20.8
> 
>     * Operating System and version: unbuntu 16.04 VM in visualbox

hi do you managed to solved the issue?

**Comment by ryjones** [comment]
⚠️ ⚠️ ⚠️

As of the 29th August 2019, the Hyperledger Composer project is in deprecated status. None of the maintainers are actively developing new features. None of the maintainers are actively providing support via GitHub issues. However, if you wish to submit code changes via pull requests, these will be merged.

It is highly recommended that you use Hyperledger Fabric v1.4+ instead, which features significant improvements to the developer experience, including a new programming model.

More information available here: What's new in Hyperledger Fabric v1.4

⚠️ ⚠️ ⚠️

**Comment by alexrosenfeld10** [comment]
@ryjones I think you might have forgotten to hyperlink your last line there
