### ISSUE TITLE
test won't pass on Chapter06

### ISSUE THREAD

**Issue by elnirs** [hyperledger/composer#4700]
hi. on Chapter06 i was trying to perform npm run test
i don't know how to fix the problem or if it is interfering to continue with the course.
this is what i got when i tried this:

npm run test

> zerotoblockchain-network@0.1.6 pretest /home/segev/Documents/github/ZeroToBlockchain/Chapter06
> npm run lint

> zerotoblockchain-network@0.1.6 lint /home/segev/Documents/github/ZeroToBlockchain/Chapter06
> eslint ./network

> zerotoblockchain-network@0.1.6 postlint /home/segev/Documents/github/ZeroToBlockchain/Chapter06
> npm run licchk

> zerotoblockchain-network@0.1.6 licchk /home/segev/Documents/github/ZeroToBlockchain/Chapter06
> echo license-check

license-check

> zerotoblockchain-network@0.1.6 postlicchk /home/segev/Documents/github/ZeroToBlockchain/Chapter06
> npm run doc

> zerotoblockchain-network@0.1.6 doc /home/segev/Documents/github/ZeroToBlockchain/Chapter06
> jsdoc --readme ./README.md --pedantic --recurse -c jsdoc.json -d network/out

> zerotoblockchain-network@0.1.6 test /home/segev/Documents/github/ZeroToBlockchain/Chapter06
> mocha network/test --recursive -t 4000

  Finance Network
    #createOrder
      ✓ should be able to create an order (8979ms)
    #issueBuyRequest
      ✓ should be able to issue a buy request (3417ms)
    #issueOrderFromSupplier
      ✓ should be able to issue a supplier order (3978ms)
    #issueRequestShipment
      ✓ should be able to issue a request to ship product (6529ms)
    #issueDelivery
      ✓ should be able to record a product delivery (3615ms)
    #issueRequestPayment
      ✓ should be able to issue a request to request payment for a product (6589ms)
    #authorizePayment
      ✓ should be able to record a approval for order payment (3685ms)
    #Pay
      ✓ should be able to record an order payment (3537ms)
    #issueDispute
      ✓ should be able to record a product dispute (3643ms)
    #issueResolution
      ✓ should be able to record a dispute resolution (3624ms)
    #issueBackorder
      ✓ should be able to record a product backorder (4013ms)
    #issueCancel
      1) should be able to record an order cancellation

  11 passing (1m)
  1 failing

  1) Finance Network #issueCancel should be able to record an order cancellation:

      AssertionError: expected 'Order Backordered' to equal 'Order Cancelled'
      + expected - actual

      -Order Backordered
      +Order Cancelled
      
      at businessNetworkConnection.submitTransaction.then.then.then (network/test/sample.js:628:69)
      at <anonymous>

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zerotoblockchain-network@0.1.6 test: `mocha network/test --recursive -t 4000`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zerotoblockchain-network@0.1.6 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/segev/.npm/_logs/2020-01-11T15_51_15_383Z-debug.log

**Comment by elnirs** [comment]
also
on chapter05 when i run npm start i get the following error which i cannot resolve:
npm start 
> zerotoblockchain-network@0.1.6 start /home/segev/Documents/github/ZeroToBlockchain/Chapter05
> node index

module.js:550
    throw err;
    ^

Error: Cannot find module 'fabric-client/lib/EventHub'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/segev/Documents/github/ZeroToBlockchain/Chapter05/controller/restapi/features/composer/queryBlockChain.js:25:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zerotoblockchain-network@0.1.6 start: `node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zerotoblockchain-network@0.1.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/segev/.npm/_logs/2020-01-11T16_04_39_630Z-debug.log
