### ISSUE TITLE
HLFv1 chaincode sporadically crashes

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#775]
The HLFv1 system tests sporadically fail with this crash:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x6c pc=0x896ebc]

runtime stack:
runtime.throw(0xae394e, 0x2a)
	/opt/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/opt/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 5081 [syscall, locked to thread]:
runtime.cgocall(0x8723d7, 0xc420346ef0, 0x7f9600000000)
	/opt/go/src/runtime/cgocall.go:131 +0x110 fp=0xc420346ea8 sp=0xc420346e68
composer/vendor/gopkg.in/olebedev/go-duktape%2ev3._Cfunc_duk_pcall(0x7f96b8003bc0, 0x7f9600000000, 0x0)
	composer/vendor/gopkg.in/olebedev/go-duktape.v3/_obj/_cgo_gotypes.go:2207 +0x4d fp=0xc420346ef0 sp=0xc420346ea8
composer/vendor/gopkg.in/olebedev/go-duktape%2ev3.(*Context).Pcall(0xc420318110, 0x0, 0x6)
	/chaincode/input/src/composer/vendor/gopkg.in/olebedev/go-duktape.v3/api.go:773 +0x85 fp=0xc420346f38 sp=0xc420346ef0
composer/vendor/gopkg.in/olebedev/go-duktape%2ev3.setTimeout.func1(0x3ff0000000000000, 0xc420318110, 0x40a2fe0000000000)
	/chaincode/input/src/composer/vendor/gopkg.in/olebedev/go-duktape.v3/timers.go:55 +0x12a fp=0xc420346f98 sp=0xc420346f38
runtime.goexit()
	/opt/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420346fa0 sp=0xc420346f98
created by composer/vendor/gopkg.in/olebedev/go-duktape%2ev3.setTimeout
	/chaincode/input/src/composer/vendor/gopkg.in/olebedev/go-duktape.v3/timers.go:58 +0xab

goroutine 1 [chan receive]:
github.com/hyperledger/fabric/core/chaincode/shim.chatWithPeer(0xc420012017, 0x21, 0x7f96beed3770, 0xc420134e80, 0x122e840, 0xc42013e0b0, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/shim/chaincode.go:279 +0x523
github.com/hyperledger/fabric/core/chaincode/shim.Start(0x122e840, 0xc42013e0b0, 0x1, 0x1)
	/opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/shim/chaincode.go:109 +0x738
main.main()
	/chaincode/input/src/composer/main.go:34 +0x11d

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/opt/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 13 [IO wait]:
net.runtime_pollWait(0x7f96bee92350, 0x72, 0x3)
	/opt/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4201e0450, 0x72, 0xc4200b7b18, 0xc420016140)
	/opt/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4201e0450, 0x122d600, 0xc420016140)
	/opt/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4201e03f0, 0xc4200bc000, 0x8000, 0x8000, 0x0, 0x122d600, 0xc420016140)
	/opt/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc4201441d0, 0xc4200bc000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/opt/go/src/net/net.go:173 +0x70
bufio.(*Reader).fill(0xc420150660)
	/opt/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc420150660, 0xc4200ae038, 0x9, 0x9, 0x460a10, 0x460910, 0x43b061)
	/opt/go/src/bufio/bufio.go:209 +0x1bc
io.ReadAtLeast(0x1229bc0, 0xc420150660, 0xc4200ae038, 0x9, 0x9, 0x9, 0x73947a, 0xc4201ded28, 0xc420150840)
	/opt/go/src/io/io.go:307 +0xa4
io.ReadFull(0x1229bc0, 0xc420150660, 0xc4200ae038, 0x9, 0x9, 0x30, 0xc4201ded28, 0x122ab80)
	/opt/go/src/io/io.go:325 +0x58
github.com/hyperledger/fabric/vendor/golang.org/x/net/http2.readFrameHeader(0xc4200ae038, 0x9, 0x9, 0x1229bc0, 0xc420150660, 0x0, 0xc400000000, 0x753, 0x753)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/hyperledger/fabric/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc4200ae000, 0x122e500, 0xc4210784b0, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/golang.org/x/net/http2/frame.go:464 +0xa4
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.(*framer).readFrame(0xc4201debd0, 0xc4210784b0, 0xc4210784b0, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http_util.go:430 +0x2f
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc42008e000)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http2_client.go:820 +0xb6
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http2_client.go:167 +0x89f

goroutine 14 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.(*http2Client).controller(0xc42008e000)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http2_client.go:898 +0x597
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http2_client.go:197 +0xdd0

goroutine 15 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc4201aa120)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:623 +0x36a
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*ClientConn).newAddrConn
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:409 +0x447

goroutine 50 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.NewClientStream.func1(0x1234b20, 0xc42008e000, 0xc42008e0f0, 0xc42015c000)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/stream.go:186 +0x393
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc.NewClientStream
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/stream.go:203 +0x96d

goroutine 51 [select]:
github.com/hyperledger/fabric/core/chaincode/shim.chatWithPeer.func1(0xc420150a20, 0xc420135010, 0x7f96beed3770, 0xc420134e80, 0xc420150a80, 0xc4201e0690)
	/opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/shim/chaincode.go:228 +0xe81
created by github.com/hyperledger/fabric/core/chaincode/shim.chatWithPeer
	/opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/shim/chaincode.go:278 +0x500

goroutine 5080 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc4201ded50, 0xc420140d50, 0x5, 0x5, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/transport.go:142 +0x5ed
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.(*Stream).Read(0xc42008e0f0, 0xc420140d50, 0x5, 0x5, 0xc42048a4e0, 0xc4201a8300, 0x1cb5d3982048a4b0)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/transport.go:301 +0x56
io.ReadAtLeast(0x122aa80, 0xc42008e0f0, 0xc420140d50, 0x5, 0x5, 0x5, 0x0, 0xc42048a548, 0x53fda9)
	/opt/go/src/io/io.go:307 +0xa4
io.ReadFull(0x122aa80, 0xc42008e0f0, 0xc420140d50, 0x5, 0x5, 0x7f96a849ba01, 0x43f300, 0x0)
	/opt/go/src/io/io.go:325 +0x58
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*parser).recvMsg(0xc420140d40, 0xc42048a501, 0x8, 0x0, 0x0, 0x43af5c, 0xc42048a620)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/rpc_util.go:231 +0x61
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.recv(0xc420140d40, 0x12324c0, 0x126f058, 0xc42008e0f0, 0x0, 0x0, 0xa814a0, 0xc421076320, 0x5, 0xc4201d6000)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/rpc_util.go:312 +0x40
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc42015c000, 0xa814a0, 0xc421076320, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/stream.go:291 +0xbb
github.com/hyperledger/fabric/protos/peer.(*chaincodeSupportRegisterClient).Recv(0xc420134e80, 0xc4201e0690, 0xc4210760a0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/protos/peer/chaincodeshim.pb.go:276 +0x62
github.com/hyperledger/fabric/core/chaincode/shim.chatWithPeer.func1.1(0xc420135010, 0x7f96beed3770, 0xc420134e80, 0xc420150ae0)
	/opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/shim/chaincode.go:224 +0x35
created by github.com/hyperledger/fabric/core/chaincode/shim.chatWithPeer.func1
	/opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/shim/chaincode.go:226 +0xebf

goroutine 5079 [chan receive]:
main.(*Composer).Invoke(0xc42012d8c0, 0x12369e0, 0xc420e5d480, 0xc420d72f20, 0x11, 0xc421078700, 0x2, 0x2, 0x0, 0x0, ...)
	/chaincode/input/src/composer/composer.go:150 +0x394
main.(*Chaincode).Invoke(0xc42013e0b0, 0x12369e0, 0xc420e5d480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/chaincode/input/src/composer/chaincode.go:79 +0x260
github.com/hyperledger/fabric/core/chaincode/shim.(*Handler).handleTransaction.func1(0xc4201e0690, 0xc4210760f0)
	/opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/shim/handler.go:312 +0x770
created by github.com/hyperledger/fabric/core/chaincode/shim.(*Handler).handleTransaction
	/opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/shim/handler.go:327 +0x49
```

**Comment by davidkel** [comment]
So duktape V0.6 version also failed with
```
  1) Transaction (asset specific) system tests should submit and execute a transaction that adds a new asset with a relationship to an asset registry:
     Error: Error:Failed to execute transaction or query(Timeout expired while executing transaction)
      at TransactionContext.transactionContext.on (/home/travis/build/hyperledger/composer/packages/composer-connector-hlf/lib/hfcutil.js:91:28)
      at Object.callback (/home/travis/build/hyperledger/composer/node_modules/hfc/lib/hfc.js:1807:42)
      at /home/travis/build/hyperledger/composer/node_modules/hfc/node_modules/grpc/src/node/src/client.js:422:14
```

**Comment by sstone1** [comment]
Should hopefully be resolved by new levels of go-duktape v3 and duktape v2.1.0 introduced in https://github.com/hyperledger/composer/pull/790.
